package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdvisePartition generated by hbm2java
 */
@Entity
@Table(name="ADVISE_PARTITION"
    ,schema="ALLERGEN"
)
public class AdvisePartition  implements java.io.Serializable {


     private AdvisePartitionId id;
     private AdviseInstance adviseInstance;

    public AdvisePartition() {
    }

	
    public AdvisePartition(AdvisePartitionId id) {
        this.id = id;
    }
    public AdvisePartition(AdvisePartitionId id, AdviseInstance adviseInstance) {
       this.id = id;
       this.adviseInstance = adviseInstance;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="explainRequester", column=@Column(name="EXPLAIN_REQUESTER", nullable=false, length=128) ), 
        @AttributeOverride(name="explainTime", column=@Column(name="EXPLAIN_TIME", nullable=false, length=26) ), 
        @AttributeOverride(name="sourceName", column=@Column(name="SOURCE_NAME", nullable=false, length=128) ), 
        @AttributeOverride(name="sourceSchema", column=@Column(name="SOURCE_SCHEMA", nullable=false, length=128) ), 
        @AttributeOverride(name="sourceVersion", column=@Column(name="SOURCE_VERSION", nullable=false, length=64) ), 
        @AttributeOverride(name="explainLevel", column=@Column(name="EXPLAIN_LEVEL", nullable=false, length=1) ), 
        @AttributeOverride(name="stmtno", column=@Column(name="STMTNO", nullable=false) ), 
        @AttributeOverride(name="sectno", column=@Column(name="SECTNO", nullable=false) ), 
        @AttributeOverride(name="queryno", column=@Column(name="QUERYNO", nullable=false) ), 
        @AttributeOverride(name="querytag", column=@Column(name="QUERYTAG", nullable=false, length=20) ), 
        @AttributeOverride(name="tbname", column=@Column(name="TBNAME", nullable=false, length=128) ), 
        @AttributeOverride(name="tbcreator", column=@Column(name="TBCREATOR", nullable=false, length=128) ), 
        @AttributeOverride(name="pmid", column=@Column(name="PMID", nullable=false) ), 
        @AttributeOverride(name="tbspace", column=@Column(name="TBSPACE", nullable=false, length=128) ), 
        @AttributeOverride(name="colnames", column=@Column(name="COLNAMES", nullable=false) ), 
        @AttributeOverride(name="colcount", column=@Column(name="COLCOUNT", nullable=false) ), 
        @AttributeOverride(name="replicate", column=@Column(name="REPLICATE", nullable=false, length=1) ), 
        @AttributeOverride(name="cost", column=@Column(name="COST", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="useit", column=@Column(name="USEIT", length=1) ), 
        @AttributeOverride(name="runId", column=@Column(name="RUN_ID", length=26) ) } )
    public AdvisePartitionId getId() {
        return this.id;
    }
    
    public void setId(AdvisePartitionId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RUN_ID", insertable=false, updatable=false)
    public AdviseInstance getAdviseInstance() {
        return this.adviseInstance;
    }
    
    public void setAdviseInstance(AdviseInstance adviseInstance) {
        this.adviseInstance = adviseInstance;
    }




}


