package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.sql.Blob;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdviseMqtId generated by hbm2java
 */
@Embeddable
public class AdviseMqtId  implements java.io.Serializable {


     private String explainRequester;
     private Date explainTime;
     private String sourceName;
     private String sourceSchema;
     private String sourceVersion;
     private char explainLevel;
     private int stmtno;
     private int sectno;
     private String name;
     private String creator;
     private short iid;
     private Date createTime;
     private Date statsTime;
     private double numrows;
     private short numcols;
     private double rowsize;
     private double benefit;
     private Character useMqt;
     private Character mqtSource;
     private Clob queryText;
     private Clob creationText;
     private Clob sampleText;
     private Clob colstats;
     private Blob extraInfo;
     private String tbspace;
     private Date runId;
     private char refreshType;
     private char exists;

    public AdviseMqtId() {
    }

	
    public AdviseMqtId(String explainRequester, Date explainTime, String sourceName, String sourceSchema, String sourceVersion, char explainLevel, int stmtno, int sectno, String name, String creator, short iid, Date createTime, double numrows, short numcols, double rowsize, double benefit, Clob queryText, Clob creationText, Clob sampleText, Clob colstats, Blob extraInfo, String tbspace, char refreshType, char exists) {
        this.explainRequester = explainRequester;
        this.explainTime = explainTime;
        this.sourceName = sourceName;
        this.sourceSchema = sourceSchema;
        this.sourceVersion = sourceVersion;
        this.explainLevel = explainLevel;
        this.stmtno = stmtno;
        this.sectno = sectno;
        this.name = name;
        this.creator = creator;
        this.iid = iid;
        this.createTime = createTime;
        this.numrows = numrows;
        this.numcols = numcols;
        this.rowsize = rowsize;
        this.benefit = benefit;
        this.queryText = queryText;
        this.creationText = creationText;
        this.sampleText = sampleText;
        this.colstats = colstats;
        this.extraInfo = extraInfo;
        this.tbspace = tbspace;
        this.refreshType = refreshType;
        this.exists = exists;
    }
    public AdviseMqtId(String explainRequester, Date explainTime, String sourceName, String sourceSchema, String sourceVersion, char explainLevel, int stmtno, int sectno, String name, String creator, short iid, Date createTime, Date statsTime, double numrows, short numcols, double rowsize, double benefit, Character useMqt, Character mqtSource, Clob queryText, Clob creationText, Clob sampleText, Clob colstats, Blob extraInfo, String tbspace, Date runId, char refreshType, char exists) {
       this.explainRequester = explainRequester;
       this.explainTime = explainTime;
       this.sourceName = sourceName;
       this.sourceSchema = sourceSchema;
       this.sourceVersion = sourceVersion;
       this.explainLevel = explainLevel;
       this.stmtno = stmtno;
       this.sectno = sectno;
       this.name = name;
       this.creator = creator;
       this.iid = iid;
       this.createTime = createTime;
       this.statsTime = statsTime;
       this.numrows = numrows;
       this.numcols = numcols;
       this.rowsize = rowsize;
       this.benefit = benefit;
       this.useMqt = useMqt;
       this.mqtSource = mqtSource;
       this.queryText = queryText;
       this.creationText = creationText;
       this.sampleText = sampleText;
       this.colstats = colstats;
       this.extraInfo = extraInfo;
       this.tbspace = tbspace;
       this.runId = runId;
       this.refreshType = refreshType;
       this.exists = exists;
    }
   

    @Column(name="EXPLAIN_REQUESTER", nullable=false, length=128)
    public String getExplainRequester() {
        return this.explainRequester;
    }
    
    public void setExplainRequester(String explainRequester) {
        this.explainRequester = explainRequester;
    }

    @Column(name="EXPLAIN_TIME", nullable=false, length=26)
    public Date getExplainTime() {
        return this.explainTime;
    }
    
    public void setExplainTime(Date explainTime) {
        this.explainTime = explainTime;
    }

    @Column(name="SOURCE_NAME", nullable=false, length=128)
    public String getSourceName() {
        return this.sourceName;
    }
    
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    @Column(name="SOURCE_SCHEMA", nullable=false, length=128)
    public String getSourceSchema() {
        return this.sourceSchema;
    }
    
    public void setSourceSchema(String sourceSchema) {
        this.sourceSchema = sourceSchema;
    }

    @Column(name="SOURCE_VERSION", nullable=false, length=64)
    public String getSourceVersion() {
        return this.sourceVersion;
    }
    
    public void setSourceVersion(String sourceVersion) {
        this.sourceVersion = sourceVersion;
    }

    @Column(name="EXPLAIN_LEVEL", nullable=false, length=1)
    public char getExplainLevel() {
        return this.explainLevel;
    }
    
    public void setExplainLevel(char explainLevel) {
        this.explainLevel = explainLevel;
    }

    @Column(name="STMTNO", nullable=false)
    public int getStmtno() {
        return this.stmtno;
    }
    
    public void setStmtno(int stmtno) {
        this.stmtno = stmtno;
    }

    @Column(name="SECTNO", nullable=false)
    public int getSectno() {
        return this.sectno;
    }
    
    public void setSectno(int sectno) {
        this.sectno = sectno;
    }

    @Column(name="NAME", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="CREATOR", nullable=false, length=128)
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Column(name="IID", nullable=false)
    public short getIid() {
        return this.iid;
    }
    
    public void setIid(short iid) {
        this.iid = iid;
    }

    @Column(name="CREATE_TIME", nullable=false, length=26)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name="STATS_TIME", length=26)
    public Date getStatsTime() {
        return this.statsTime;
    }
    
    public void setStatsTime(Date statsTime) {
        this.statsTime = statsTime;
    }

    @Column(name="NUMROWS", nullable=false, precision=53, scale=0)
    public double getNumrows() {
        return this.numrows;
    }
    
    public void setNumrows(double numrows) {
        this.numrows = numrows;
    }

    @Column(name="NUMCOLS", nullable=false)
    public short getNumcols() {
        return this.numcols;
    }
    
    public void setNumcols(short numcols) {
        this.numcols = numcols;
    }

    @Column(name="ROWSIZE", nullable=false, precision=53, scale=0)
    public double getRowsize() {
        return this.rowsize;
    }
    
    public void setRowsize(double rowsize) {
        this.rowsize = rowsize;
    }

    @Column(name="BENEFIT", nullable=false, precision=53, scale=0)
    public double getBenefit() {
        return this.benefit;
    }
    
    public void setBenefit(double benefit) {
        this.benefit = benefit;
    }

    @Column(name="USE_MQT", length=1)
    public Character getUseMqt() {
        return this.useMqt;
    }
    
    public void setUseMqt(Character useMqt) {
        this.useMqt = useMqt;
    }

    @Column(name="MQT_SOURCE", length=1)
    public Character getMqtSource() {
        return this.mqtSource;
    }
    
    public void setMqtSource(Character mqtSource) {
        this.mqtSource = mqtSource;
    }

    @Column(name="QUERY_TEXT", nullable=false)
    public Clob getQueryText() {
        return this.queryText;
    }
    
    public void setQueryText(Clob queryText) {
        this.queryText = queryText;
    }

    @Column(name="CREATION_TEXT", nullable=false)
    public Clob getCreationText() {
        return this.creationText;
    }
    
    public void setCreationText(Clob creationText) {
        this.creationText = creationText;
    }

    @Column(name="SAMPLE_TEXT", nullable=false)
    public Clob getSampleText() {
        return this.sampleText;
    }
    
    public void setSampleText(Clob sampleText) {
        this.sampleText = sampleText;
    }

    @Column(name="COLSTATS", nullable=false)
    public Clob getColstats() {
        return this.colstats;
    }
    
    public void setColstats(Clob colstats) {
        this.colstats = colstats;
    }

    @Column(name="EXTRA_INFO", nullable=false)
    public Blob getExtraInfo() {
        return this.extraInfo;
    }
    
    public void setExtraInfo(Blob extraInfo) {
        this.extraInfo = extraInfo;
    }

    @Column(name="TBSPACE", nullable=false, length=128)
    public String getTbspace() {
        return this.tbspace;
    }
    
    public void setTbspace(String tbspace) {
        this.tbspace = tbspace;
    }

    @Column(name="RUN_ID", length=26)
    public Date getRunId() {
        return this.runId;
    }
    
    public void setRunId(Date runId) {
        this.runId = runId;
    }

    @Column(name="REFRESH_TYPE", nullable=false, length=1)
    public char getRefreshType() {
        return this.refreshType;
    }
    
    public void setRefreshType(char refreshType) {
        this.refreshType = refreshType;
    }

    @Column(name="EXISTS", nullable=false, length=1)
    public char getExists() {
        return this.exists;
    }
    
    public void setExists(char exists) {
        this.exists = exists;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdviseMqtId) ) return false;
		 AdviseMqtId castOther = ( AdviseMqtId ) other; 
         
		 return ( (this.getExplainRequester()==castOther.getExplainRequester()) || ( this.getExplainRequester()!=null && castOther.getExplainRequester()!=null && this.getExplainRequester().equals(castOther.getExplainRequester()) ) )
 && ( (this.getExplainTime()==castOther.getExplainTime()) || ( this.getExplainTime()!=null && castOther.getExplainTime()!=null && this.getExplainTime().equals(castOther.getExplainTime()) ) )
 && ( (this.getSourceName()==castOther.getSourceName()) || ( this.getSourceName()!=null && castOther.getSourceName()!=null && this.getSourceName().equals(castOther.getSourceName()) ) )
 && ( (this.getSourceSchema()==castOther.getSourceSchema()) || ( this.getSourceSchema()!=null && castOther.getSourceSchema()!=null && this.getSourceSchema().equals(castOther.getSourceSchema()) ) )
 && ( (this.getSourceVersion()==castOther.getSourceVersion()) || ( this.getSourceVersion()!=null && castOther.getSourceVersion()!=null && this.getSourceVersion().equals(castOther.getSourceVersion()) ) )
 && (this.getExplainLevel()==castOther.getExplainLevel())
 && (this.getStmtno()==castOther.getStmtno())
 && (this.getSectno()==castOther.getSectno())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getCreator()==castOther.getCreator()) || ( this.getCreator()!=null && castOther.getCreator()!=null && this.getCreator().equals(castOther.getCreator()) ) )
 && (this.getIid()==castOther.getIid())
 && ( (this.getCreateTime()==castOther.getCreateTime()) || ( this.getCreateTime()!=null && castOther.getCreateTime()!=null && this.getCreateTime().equals(castOther.getCreateTime()) ) )
 && ( (this.getStatsTime()==castOther.getStatsTime()) || ( this.getStatsTime()!=null && castOther.getStatsTime()!=null && this.getStatsTime().equals(castOther.getStatsTime()) ) )
 && (this.getNumrows()==castOther.getNumrows())
 && (this.getNumcols()==castOther.getNumcols())
 && (this.getRowsize()==castOther.getRowsize())
 && (this.getBenefit()==castOther.getBenefit())
 && ( (this.getUseMqt()==castOther.getUseMqt()) || ( this.getUseMqt()!=null && castOther.getUseMqt()!=null && this.getUseMqt().equals(castOther.getUseMqt()) ) )
 && ( (this.getMqtSource()==castOther.getMqtSource()) || ( this.getMqtSource()!=null && castOther.getMqtSource()!=null && this.getMqtSource().equals(castOther.getMqtSource()) ) )
 && ( (this.getQueryText()==castOther.getQueryText()) || ( this.getQueryText()!=null && castOther.getQueryText()!=null && this.getQueryText().equals(castOther.getQueryText()) ) )
 && ( (this.getCreationText()==castOther.getCreationText()) || ( this.getCreationText()!=null && castOther.getCreationText()!=null && this.getCreationText().equals(castOther.getCreationText()) ) )
 && ( (this.getSampleText()==castOther.getSampleText()) || ( this.getSampleText()!=null && castOther.getSampleText()!=null && this.getSampleText().equals(castOther.getSampleText()) ) )
 && ( (this.getColstats()==castOther.getColstats()) || ( this.getColstats()!=null && castOther.getColstats()!=null && this.getColstats().equals(castOther.getColstats()) ) )
 && ( (this.getExtraInfo()==castOther.getExtraInfo()) || ( this.getExtraInfo()!=null && castOther.getExtraInfo()!=null && this.getExtraInfo().equals(castOther.getExtraInfo()) ) )
 && ( (this.getTbspace()==castOther.getTbspace()) || ( this.getTbspace()!=null && castOther.getTbspace()!=null && this.getTbspace().equals(castOther.getTbspace()) ) )
 && ( (this.getRunId()==castOther.getRunId()) || ( this.getRunId()!=null && castOther.getRunId()!=null && this.getRunId().equals(castOther.getRunId()) ) )
 && (this.getRefreshType()==castOther.getRefreshType())
 && (this.getExists()==castOther.getExists());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExplainRequester() == null ? 0 : this.getExplainRequester().hashCode() );
         result = 37 * result + ( getExplainTime() == null ? 0 : this.getExplainTime().hashCode() );
         result = 37 * result + ( getSourceName() == null ? 0 : this.getSourceName().hashCode() );
         result = 37 * result + ( getSourceSchema() == null ? 0 : this.getSourceSchema().hashCode() );
         result = 37 * result + ( getSourceVersion() == null ? 0 : this.getSourceVersion().hashCode() );
         result = 37 * result + this.getExplainLevel();
         result = 37 * result + this.getStmtno();
         result = 37 * result + this.getSectno();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getCreator() == null ? 0 : this.getCreator().hashCode() );
         result = 37 * result + this.getIid();
         result = 37 * result + ( getCreateTime() == null ? 0 : this.getCreateTime().hashCode() );
         result = 37 * result + ( getStatsTime() == null ? 0 : this.getStatsTime().hashCode() );
         result = 37 * result + (int) this.getNumrows();
         result = 37 * result + this.getNumcols();
         result = 37 * result + (int) this.getRowsize();
         result = 37 * result + (int) this.getBenefit();
         result = 37 * result + ( getUseMqt() == null ? 0 : this.getUseMqt().hashCode() );
         result = 37 * result + ( getMqtSource() == null ? 0 : this.getMqtSource().hashCode() );
         result = 37 * result + ( getQueryText() == null ? 0 : this.getQueryText().hashCode() );
         result = 37 * result + ( getCreationText() == null ? 0 : this.getCreationText().hashCode() );
         result = 37 * result + ( getSampleText() == null ? 0 : this.getSampleText().hashCode() );
         result = 37 * result + ( getColstats() == null ? 0 : this.getColstats().hashCode() );
         result = 37 * result + ( getExtraInfo() == null ? 0 : this.getExtraInfo().hashCode() );
         result = 37 * result + ( getTbspace() == null ? 0 : this.getTbspace().hashCode() );
         result = 37 * result + ( getRunId() == null ? 0 : this.getRunId().hashCode() );
         result = 37 * result + this.getRefreshType();
         result = 37 * result + this.getExists();
         return result;
   }   


}


