package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdviseMqt generated by hbm2java
 */
@Entity
@Table(name="ADVISE_MQT"
    ,schema="ALLERGEN"
)
public class AdviseMqt  implements java.io.Serializable {


     private AdviseMqtId id;
     private AdviseInstance adviseInstance;

    public AdviseMqt() {
    }

	
    public AdviseMqt(AdviseMqtId id) {
        this.id = id;
    }
    public AdviseMqt(AdviseMqtId id, AdviseInstance adviseInstance) {
       this.id = id;
       this.adviseInstance = adviseInstance;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="explainRequester", column=@Column(name="EXPLAIN_REQUESTER", nullable=false, length=128) ), 
        @AttributeOverride(name="explainTime", column=@Column(name="EXPLAIN_TIME", nullable=false, length=26) ), 
        @AttributeOverride(name="sourceName", column=@Column(name="SOURCE_NAME", nullable=false, length=128) ), 
        @AttributeOverride(name="sourceSchema", column=@Column(name="SOURCE_SCHEMA", nullable=false, length=128) ), 
        @AttributeOverride(name="sourceVersion", column=@Column(name="SOURCE_VERSION", nullable=false, length=64) ), 
        @AttributeOverride(name="explainLevel", column=@Column(name="EXPLAIN_LEVEL", nullable=false, length=1) ), 
        @AttributeOverride(name="stmtno", column=@Column(name="STMTNO", nullable=false) ), 
        @AttributeOverride(name="sectno", column=@Column(name="SECTNO", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=128) ), 
        @AttributeOverride(name="creator", column=@Column(name="CREATOR", nullable=false, length=128) ), 
        @AttributeOverride(name="iid", column=@Column(name="IID", nullable=false) ), 
        @AttributeOverride(name="createTime", column=@Column(name="CREATE_TIME", nullable=false, length=26) ), 
        @AttributeOverride(name="statsTime", column=@Column(name="STATS_TIME", length=26) ), 
        @AttributeOverride(name="numrows", column=@Column(name="NUMROWS", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="numcols", column=@Column(name="NUMCOLS", nullable=false) ), 
        @AttributeOverride(name="rowsize", column=@Column(name="ROWSIZE", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="benefit", column=@Column(name="BENEFIT", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="useMqt", column=@Column(name="USE_MQT", length=1) ), 
        @AttributeOverride(name="mqtSource", column=@Column(name="MQT_SOURCE", length=1) ), 
        @AttributeOverride(name="queryText", column=@Column(name="QUERY_TEXT", nullable=false) ), 
        @AttributeOverride(name="creationText", column=@Column(name="CREATION_TEXT", nullable=false) ), 
        @AttributeOverride(name="sampleText", column=@Column(name="SAMPLE_TEXT", nullable=false) ), 
        @AttributeOverride(name="colstats", column=@Column(name="COLSTATS", nullable=false) ), 
        @AttributeOverride(name="extraInfo", column=@Column(name="EXTRA_INFO", nullable=false) ), 
        @AttributeOverride(name="tbspace", column=@Column(name="TBSPACE", nullable=false, length=128) ), 
        @AttributeOverride(name="runId", column=@Column(name="RUN_ID", length=26) ), 
        @AttributeOverride(name="refreshType", column=@Column(name="REFRESH_TYPE", nullable=false, length=1) ), 
        @AttributeOverride(name="exists", column=@Column(name="EXISTS", nullable=false, length=1) ) } )
    public AdviseMqtId getId() {
        return this.id;
    }
    
    public void setId(AdviseMqtId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RUN_ID", insertable=false, updatable=false)
    public AdviseInstance getAdviseInstance() {
        return this.adviseInstance;
    }
    
    public void setAdviseInstance(AdviseInstance adviseInstance) {
        this.adviseInstance = adviseInstance;
    }




}


