package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AdviseWorkload generated by hbm2java
 */
@Entity
@Table(name="ADVISE_WORKLOAD"
    ,schema="ALLERGEN"
)
public class AdviseWorkload  implements java.io.Serializable {


     private AdviseWorkloadId id;

    public AdviseWorkload() {
    }

    public AdviseWorkload(AdviseWorkloadId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="workloadName", column=@Column(name="WORKLOAD_NAME", nullable=false, length=128) ), 
        @AttributeOverride(name="statementNo", column=@Column(name="STATEMENT_NO", nullable=false) ), 
        @AttributeOverride(name="statementText", column=@Column(name="STATEMENT_TEXT", nullable=false) ), 
        @AttributeOverride(name="statementTag", column=@Column(name="STATEMENT_TAG", nullable=false, length=256) ), 
        @AttributeOverride(name="frequency", column=@Column(name="FREQUENCY", nullable=false) ), 
        @AttributeOverride(name="importance", column=@Column(name="IMPORTANCE", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="weight", column=@Column(name="WEIGHT", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="costBefore", column=@Column(name="COST_BEFORE", precision=53, scale=0) ), 
        @AttributeOverride(name="costAfter", column=@Column(name="COST_AFTER", precision=53, scale=0) ), 
        @AttributeOverride(name="compilable", column=@Column(name="COMPILABLE", length=17) ) } )
    public AdviseWorkloadId getId() {
        return this.id;
    }
    
    public void setId(AdviseWorkloadId id) {
        this.id = id;
    }




}


