package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExplainStream generated by hbm2java
 */
@Entity
@Table(name="EXPLAIN_STREAM"
    ,schema="ALLERGEN"
)
public class ExplainStream  implements java.io.Serializable {


     private ExplainStreamId id;
     private ExplainStatement explainStatement;

    public ExplainStream() {
    }

    public ExplainStream(ExplainStreamId id, ExplainStatement explainStatement) {
       this.id = id;
       this.explainStatement = explainStatement;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="explainRequester", column=@Column(name="EXPLAIN_REQUESTER", nullable=false, length=128) ), 
        @AttributeOverride(name="explainTime", column=@Column(name="EXPLAIN_TIME", nullable=false, length=26) ), 
        @AttributeOverride(name="sourceName", column=@Column(name="SOURCE_NAME", nullable=false, length=128) ), 
        @AttributeOverride(name="sourceSchema", column=@Column(name="SOURCE_SCHEMA", nullable=false, length=128) ), 
        @AttributeOverride(name="sourceVersion", column=@Column(name="SOURCE_VERSION", nullable=false, length=64) ), 
        @AttributeOverride(name="explainLevel", column=@Column(name="EXPLAIN_LEVEL", nullable=false, length=1) ), 
        @AttributeOverride(name="stmtno", column=@Column(name="STMTNO", nullable=false) ), 
        @AttributeOverride(name="sectno", column=@Column(name="SECTNO", nullable=false) ), 
        @AttributeOverride(name="streamId", column=@Column(name="STREAM_ID", nullable=false) ), 
        @AttributeOverride(name="sourceType", column=@Column(name="SOURCE_TYPE", nullable=false, length=1) ), 
        @AttributeOverride(name="sourceId", column=@Column(name="SOURCE_ID", nullable=false) ), 
        @AttributeOverride(name="targetType", column=@Column(name="TARGET_TYPE", nullable=false, length=1) ), 
        @AttributeOverride(name="targetId", column=@Column(name="TARGET_ID", nullable=false) ), 
        @AttributeOverride(name="objectSchema", column=@Column(name="OBJECT_SCHEMA", length=128) ), 
        @AttributeOverride(name="objectName", column=@Column(name="OBJECT_NAME", length=128) ), 
        @AttributeOverride(name="streamCount", column=@Column(name="STREAM_COUNT", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="columnCount", column=@Column(name="COLUMN_COUNT", nullable=false) ), 
        @AttributeOverride(name="predicateId", column=@Column(name="PREDICATE_ID", nullable=false) ), 
        @AttributeOverride(name="columnNames", column=@Column(name="COLUMN_NAMES") ), 
        @AttributeOverride(name="pmid", column=@Column(name="PMID", nullable=false) ), 
        @AttributeOverride(name="singleNode", column=@Column(name="SINGLE_NODE", length=5) ), 
        @AttributeOverride(name="partitionColumns", column=@Column(name="PARTITION_COLUMNS") ), 
        @AttributeOverride(name="sequenceSizes", column=@Column(name="SEQUENCE_SIZES") ) } )
    public ExplainStreamId getId() {
        return this.id;
    }
    
    public void setId(ExplainStreamId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="EXPLAIN_REQUESTER", referencedColumnName="EXPLAIN_REQUESTER", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EXPLAIN_TIME", referencedColumnName="EXPLAIN_TIME", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SOURCE_NAME", referencedColumnName="SOURCE_NAME", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SOURCE_SCHEMA", referencedColumnName="SOURCE_SCHEMA", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SOURCE_VERSION", referencedColumnName="SOURCE_VERSION", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EXPLAIN_LEVEL", referencedColumnName="EXPLAIN_LEVEL", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="STMTNO", referencedColumnName="STMTNO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SECTNO", referencedColumnName="SECTNO", nullable=false, insertable=false, updatable=false) } )
    public ExplainStatement getExplainStatement() {
        return this.explainStatement;
    }
    
    public void setExplainStatement(ExplainStatement explainStatement) {
        this.explainStatement = explainStatement;
    }




}


