package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExplainInstance generated by hbm2java
 */
@Entity
@Table(name="EXPLAIN_INSTANCE"
    ,schema="ALLERGEN"
)
public class ExplainInstance  implements java.io.Serializable {


     private ExplainInstanceId id;
     private char explainOption;
     private char snapshotTaken;
     private String db2Version;
     private char sqlType;
     private int queryopt;
     private char block;
     private String isolation;
     private int buffpage;
     private int avgAppls;
     private int sortheap;
     private int locklist;
     private short maxlocks;
     private int locksAvail;
     private double cpuSpeed;
     private String remarks;
     private int dbheap;
     private double commSpeed;
     private String parallelism;
     private char datajoiner;
     private Set<ExplainStatement> explainStatements = new HashSet<ExplainStatement>(0);

    public ExplainInstance() {
    }

	
    public ExplainInstance(ExplainInstanceId id, char explainOption, char snapshotTaken, String db2Version, char sqlType, int queryopt, char block, String isolation, int buffpage, int avgAppls, int sortheap, int locklist, short maxlocks, int locksAvail, double cpuSpeed, int dbheap, double commSpeed, String parallelism, char datajoiner) {
        this.id = id;
        this.explainOption = explainOption;
        this.snapshotTaken = snapshotTaken;
        this.db2Version = db2Version;
        this.sqlType = sqlType;
        this.queryopt = queryopt;
        this.block = block;
        this.isolation = isolation;
        this.buffpage = buffpage;
        this.avgAppls = avgAppls;
        this.sortheap = sortheap;
        this.locklist = locklist;
        this.maxlocks = maxlocks;
        this.locksAvail = locksAvail;
        this.cpuSpeed = cpuSpeed;
        this.dbheap = dbheap;
        this.commSpeed = commSpeed;
        this.parallelism = parallelism;
        this.datajoiner = datajoiner;
    }
    public ExplainInstance(ExplainInstanceId id, char explainOption, char snapshotTaken, String db2Version, char sqlType, int queryopt, char block, String isolation, int buffpage, int avgAppls, int sortheap, int locklist, short maxlocks, int locksAvail, double cpuSpeed, String remarks, int dbheap, double commSpeed, String parallelism, char datajoiner, Set<ExplainStatement> explainStatements) {
       this.id = id;
       this.explainOption = explainOption;
       this.snapshotTaken = snapshotTaken;
       this.db2Version = db2Version;
       this.sqlType = sqlType;
       this.queryopt = queryopt;
       this.block = block;
       this.isolation = isolation;
       this.buffpage = buffpage;
       this.avgAppls = avgAppls;
       this.sortheap = sortheap;
       this.locklist = locklist;
       this.maxlocks = maxlocks;
       this.locksAvail = locksAvail;
       this.cpuSpeed = cpuSpeed;
       this.remarks = remarks;
       this.dbheap = dbheap;
       this.commSpeed = commSpeed;
       this.parallelism = parallelism;
       this.datajoiner = datajoiner;
       this.explainStatements = explainStatements;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="explainRequester", column=@Column(name="EXPLAIN_REQUESTER", nullable=false, length=128) ), 
        @AttributeOverride(name="explainTime", column=@Column(name="EXPLAIN_TIME", nullable=false, length=26) ), 
        @AttributeOverride(name="sourceName", column=@Column(name="SOURCE_NAME", nullable=false, length=128) ), 
        @AttributeOverride(name="sourceSchema", column=@Column(name="SOURCE_SCHEMA", nullable=false, length=128) ), 
        @AttributeOverride(name="sourceVersion", column=@Column(name="SOURCE_VERSION", nullable=false, length=64) ) } )
    public ExplainInstanceId getId() {
        return this.id;
    }
    
    public void setId(ExplainInstanceId id) {
        this.id = id;
    }
    
    @Column(name="EXPLAIN_OPTION", nullable=false, length=1)
    public char getExplainOption() {
        return this.explainOption;
    }
    
    public void setExplainOption(char explainOption) {
        this.explainOption = explainOption;
    }
    
    @Column(name="SNAPSHOT_TAKEN", nullable=false, length=1)
    public char getSnapshotTaken() {
        return this.snapshotTaken;
    }
    
    public void setSnapshotTaken(char snapshotTaken) {
        this.snapshotTaken = snapshotTaken;
    }
    
    @Column(name="DB2_VERSION", nullable=false, length=7)
    public String getDb2Version() {
        return this.db2Version;
    }
    
    public void setDb2Version(String db2Version) {
        this.db2Version = db2Version;
    }
    
    @Column(name="SQL_TYPE", nullable=false, length=1)
    public char getSqlType() {
        return this.sqlType;
    }
    
    public void setSqlType(char sqlType) {
        this.sqlType = sqlType;
    }
    
    @Column(name="QUERYOPT", nullable=false)
    public int getQueryopt() {
        return this.queryopt;
    }
    
    public void setQueryopt(int queryopt) {
        this.queryopt = queryopt;
    }
    
    @Column(name="BLOCK", nullable=false, length=1)
    public char getBlock() {
        return this.block;
    }
    
    public void setBlock(char block) {
        this.block = block;
    }
    
    @Column(name="ISOLATION", nullable=false, length=2)
    public String getIsolation() {
        return this.isolation;
    }
    
    public void setIsolation(String isolation) {
        this.isolation = isolation;
    }
    
    @Column(name="BUFFPAGE", nullable=false)
    public int getBuffpage() {
        return this.buffpage;
    }
    
    public void setBuffpage(int buffpage) {
        this.buffpage = buffpage;
    }
    
    @Column(name="AVG_APPLS", nullable=false)
    public int getAvgAppls() {
        return this.avgAppls;
    }
    
    public void setAvgAppls(int avgAppls) {
        this.avgAppls = avgAppls;
    }
    
    @Column(name="SORTHEAP", nullable=false)
    public int getSortheap() {
        return this.sortheap;
    }
    
    public void setSortheap(int sortheap) {
        this.sortheap = sortheap;
    }
    
    @Column(name="LOCKLIST", nullable=false)
    public int getLocklist() {
        return this.locklist;
    }
    
    public void setLocklist(int locklist) {
        this.locklist = locklist;
    }
    
    @Column(name="MAXLOCKS", nullable=false)
    public short getMaxlocks() {
        return this.maxlocks;
    }
    
    public void setMaxlocks(short maxlocks) {
        this.maxlocks = maxlocks;
    }
    
    @Column(name="LOCKS_AVAIL", nullable=false)
    public int getLocksAvail() {
        return this.locksAvail;
    }
    
    public void setLocksAvail(int locksAvail) {
        this.locksAvail = locksAvail;
    }
    
    @Column(name="CPU_SPEED", nullable=false, precision=53, scale=0)
    public double getCpuSpeed() {
        return this.cpuSpeed;
    }
    
    public void setCpuSpeed(double cpuSpeed) {
        this.cpuSpeed = cpuSpeed;
    }
    
    @Column(name="REMARKS", length=254)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    @Column(name="DBHEAP", nullable=false)
    public int getDbheap() {
        return this.dbheap;
    }
    
    public void setDbheap(int dbheap) {
        this.dbheap = dbheap;
    }
    
    @Column(name="COMM_SPEED", nullable=false, precision=53, scale=0)
    public double getCommSpeed() {
        return this.commSpeed;
    }
    
    public void setCommSpeed(double commSpeed) {
        this.commSpeed = commSpeed;
    }
    
    @Column(name="PARALLELISM", nullable=false, length=2)
    public String getParallelism() {
        return this.parallelism;
    }
    
    public void setParallelism(String parallelism) {
        this.parallelism = parallelism;
    }
    
    @Column(name="DATAJOINER", nullable=false, length=1)
    public char getDatajoiner() {
        return this.datajoiner;
    }
    
    public void setDatajoiner(char datajoiner) {
        this.datajoiner = datajoiner;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="explainInstance")
    public Set<ExplainStatement> getExplainStatements() {
        return this.explainStatements;
    }
    
    public void setExplainStatements(Set<ExplainStatement> explainStatements) {
        this.explainStatements = explainStatements;
    }




}


