package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Partners generated by hbm2java
 */
@Entity
@Table(name="PARTNERS"
    ,schema="ALLERGEN"
)
public class Partners  implements java.io.Serializable {


     private PartnersId id;

    public Partners() {
    }

    public Partners(PartnersId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sysid", column=@Column(name="SYSID", nullable=false) ), 
        @AttributeOverride(name="partner", column=@Column(name="PARTNER", nullable=false, length=200) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY", nullable=false) ), 
        @AttributeOverride(name="modifiedBy", column=@Column(name="MODIFIED_BY") ), 
        @AttributeOverride(name="created", column=@Column(name="CREATED", nullable=false, length=26) ), 
        @AttributeOverride(name="modified", column=@Column(name="MODIFIED", length=26) ), 
        @AttributeOverride(name="commentary", column=@Column(name="COMMENTARY") ) } )
    public PartnersId getId() {
        return this.id;
    }
    
    public void setId(PartnersId id) {
        this.id = id;
    }




}


