package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * T20080204115922Exception generated by hbm2java
 */
@Entity
@Table(name="T20080204_115922_EXCEPTION"
    ,schema="ALLERGEN"
)
public class T20080204115922Exception  implements java.io.Serializable {


     private T20080204115922ExceptionId id;

    public T20080204115922Exception() {
    }

    public T20080204115922Exception(T20080204115922ExceptionId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="variableid", column=@Column(name="VARIABLEID", nullable=false) ), 
        @AttributeOverride(name="description", column=@Column(name="DESCRIPTION") ), 
        @AttributeOverride(name="range", column=@Column(name="RANGE", length=100) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=100) ) } )
    public T20080204115922ExceptionId getId() {
        return this.id;
    }
    
    public void setId(T20080204115922ExceptionId id) {
        this.id = id;
    }




}


