package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * T20080611121455Exception generated by hbm2java
 */
@Entity
@Table(name="T20080611_121455_EXCEPTION"
    ,schema="ALLERGEN"
)
public class T20080611121455Exception  implements java.io.Serializable {


     private T20080611121455ExceptionId id;

    public T20080611121455Exception() {
    }

    public T20080611121455Exception(T20080611121455ExceptionId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="genelinkid", column=@Column(name="GENELINKID", nullable=false) ), 
        @AttributeOverride(name="geneid", column=@Column(name="GENEID", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=50) ), 
        @AttributeOverride(name="url", column=@Column(name="URL", nullable=false, length=250) ), 
        @AttributeOverride(name="sortorder", column=@Column(name="SORTORDER", nullable=false) ) } )
    public T20080611121455ExceptionId getId() {
        return this.id;
    }
    
    public void setId(T20080611121455ExceptionId id) {
        this.id = id;
    }




}


