package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * T20090922141348ExceptionId generated by hbm2java
 */
@Embeddable
public class T20090922141348ExceptionId  implements java.io.Serializable {


     private int controlwellid;
     private int containerid;
     private int row;
     private int column;
     private int controlid;
     private Double volume;
     private String comments;
     private Date created;
     private int createdBy;
     private Date modified;
     private Integer modifiedBy;

    public T20090922141348ExceptionId() {
    }

	
    public T20090922141348ExceptionId(int controlwellid, int containerid, int row, int column, int controlid, String comments, Date created, int createdBy) {
        this.controlwellid = controlwellid;
        this.containerid = containerid;
        this.row = row;
        this.column = column;
        this.controlid = controlid;
        this.comments = comments;
        this.created = created;
        this.createdBy = createdBy;
    }
    public T20090922141348ExceptionId(int controlwellid, int containerid, int row, int column, int controlid, Double volume, String comments, Date created, int createdBy, Date modified, Integer modifiedBy) {
       this.controlwellid = controlwellid;
       this.containerid = containerid;
       this.row = row;
       this.column = column;
       this.controlid = controlid;
       this.volume = volume;
       this.comments = comments;
       this.created = created;
       this.createdBy = createdBy;
       this.modified = modified;
       this.modifiedBy = modifiedBy;
    }
   

    @Column(name="CONTROLWELLID", nullable=false)
    public int getControlwellid() {
        return this.controlwellid;
    }
    
    public void setControlwellid(int controlwellid) {
        this.controlwellid = controlwellid;
    }

    @Column(name="CONTAINERID", nullable=false)
    public int getContainerid() {
        return this.containerid;
    }
    
    public void setContainerid(int containerid) {
        this.containerid = containerid;
    }

    @Column(name="ROW", nullable=false)
    public int getRow() {
        return this.row;
    }
    
    public void setRow(int row) {
        this.row = row;
    }

    @Column(name="COLUMN", nullable=false)
    public int getColumn() {
        return this.column;
    }
    
    public void setColumn(int column) {
        this.column = column;
    }

    @Column(name="CONTROLID", nullable=false)
    public int getControlid() {
        return this.controlid;
    }
    
    public void setControlid(int controlid) {
        this.controlid = controlid;
    }

    @Column(name="VOLUME", precision=53, scale=0)
    public Double getVolume() {
        return this.volume;
    }
    
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    @Column(name="COMMENTS", nullable=false, length=250)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name="CREATED", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name="CREATED_BY", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name="MODIFIED", length=26)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    @Column(name="MODIFIED_BY")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof T20090922141348ExceptionId) ) return false;
		 T20090922141348ExceptionId castOther = ( T20090922141348ExceptionId ) other; 
         
		 return (this.getControlwellid()==castOther.getControlwellid())
 && (this.getContainerid()==castOther.getContainerid())
 && (this.getRow()==castOther.getRow())
 && (this.getColumn()==castOther.getColumn())
 && (this.getControlid()==castOther.getControlid())
 && ( (this.getVolume()==castOther.getVolume()) || ( this.getVolume()!=null && castOther.getVolume()!=null && this.getVolume().equals(castOther.getVolume()) ) )
 && ( (this.getComments()==castOther.getComments()) || ( this.getComments()!=null && castOther.getComments()!=null && this.getComments().equals(castOther.getComments()) ) )
 && ( (this.getCreated()==castOther.getCreated()) || ( this.getCreated()!=null && castOther.getCreated()!=null && this.getCreated().equals(castOther.getCreated()) ) )
 && (this.getCreatedBy()==castOther.getCreatedBy())
 && ( (this.getModified()==castOther.getModified()) || ( this.getModified()!=null && castOther.getModified()!=null && this.getModified().equals(castOther.getModified()) ) )
 && ( (this.getModifiedBy()==castOther.getModifiedBy()) || ( this.getModifiedBy()!=null && castOther.getModifiedBy()!=null && this.getModifiedBy().equals(castOther.getModifiedBy()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getControlwellid();
         result = 37 * result + this.getContainerid();
         result = 37 * result + this.getRow();
         result = 37 * result + this.getColumn();
         result = 37 * result + this.getControlid();
         result = 37 * result + ( getVolume() == null ? 0 : this.getVolume().hashCode() );
         result = 37 * result + ( getComments() == null ? 0 : this.getComments().hashCode() );
         result = 37 * result + ( getCreated() == null ? 0 : this.getCreated().hashCode() );
         result = 37 * result + this.getCreatedBy();
         result = 37 * result + ( getModified() == null ? 0 : this.getModified().hashCode() );
         result = 37 * result + ( getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode() );
         return result;
   }   


}


