package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * T20080204115922 generated by hbm2java
 */
@Entity
@Table(name="T20080204_115922"
    ,schema="ALLERGEN"
)
public class T20080204115922  implements java.io.Serializable {


     private T20080204115922Id id;

    public T20080204115922() {
    }

    public T20080204115922(T20080204115922Id id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="variableid", column=@Column(name="VARIABLEID", nullable=false) ), 
        @AttributeOverride(name="description", column=@Column(name="DESCRIPTION", nullable=false) ), 
        @AttributeOverride(name="range", column=@Column(name="RANGE", nullable=false, length=100) ) } )
    public T20080204115922Id getId() {
        return this.id;
    }
    
    public void setId(T20080204115922Id id) {
        this.id = id;
    }




}


