package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * T20090722170736Exception generated by hbm2java
 */
@Entity
@Table(name="T20090722_170736_EXCEPTION"
    ,schema="ALLERGEN"
)
public class T20090722170736Exception  implements java.io.Serializable {


     private T20090722170736ExceptionId id;

    public T20090722170736Exception() {
    }

    public T20090722170736Exception(T20090722170736ExceptionId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sampleid", column=@Column(name="SAMPLEID", nullable=false) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", nullable=false) ), 
        @AttributeOverride(name="genotypingrunid", column=@Column(name="GENOTYPINGRUNID", nullable=false) ), 
        @AttributeOverride(name="date", column=@Column(name="DATE", nullable=false, length=10) ), 
        @AttributeOverride(name="sampleqcstatusid", column=@Column(name="SAMPLEQCSTATUSID", nullable=false) ) } )
    public T20090722170736ExceptionId getId() {
        return this.id;
    }
    
    public void setId(T20090722170736ExceptionId id) {
        this.id = id;
    }




}


