package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * T20090922141348Exception generated by hbm2java
 */
@Entity
@Table(name="T20090922_141348_EXCEPTION"
    ,schema="ALLERGEN"
)
public class T20090922141348Exception  implements java.io.Serializable {


     private T20090922141348ExceptionId id;

    public T20090922141348Exception() {
    }

    public T20090922141348Exception(T20090922141348ExceptionId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="controlwellid", column=@Column(name="CONTROLWELLID", nullable=false) ), 
        @AttributeOverride(name="containerid", column=@Column(name="CONTAINERID", nullable=false) ), 
        @AttributeOverride(name="row", column=@Column(name="ROW", nullable=false) ), 
        @AttributeOverride(name="column", column=@Column(name="COLUMN", nullable=false) ), 
        @AttributeOverride(name="controlid", column=@Column(name="CONTROLID", nullable=false) ), 
        @AttributeOverride(name="volume", column=@Column(name="VOLUME", precision=53, scale=0) ), 
        @AttributeOverride(name="comments", column=@Column(name="COMMENTS", nullable=false, length=250) ), 
        @AttributeOverride(name="created", column=@Column(name="CREATED", nullable=false, length=26) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY", nullable=false) ), 
        @AttributeOverride(name="modified", column=@Column(name="MODIFIED", length=26) ), 
        @AttributeOverride(name="modifiedBy", column=@Column(name="MODIFIED_BY") ) } )
    public T20090922141348ExceptionId getId() {
        return this.id;
    }
    
    public void setId(T20090922141348ExceptionId id) {
        this.id = id;
    }




}


