package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * T20090722170908ExceptionId generated by hbm2java
 */
@Embeddable
public class T20090722170908ExceptionId  implements java.io.Serializable {


     private int sampleid;
     private short status;
     private int genotypingrunid;
     private Date date;
     private int sampleqcstatusid;

    public T20090722170908ExceptionId() {
    }

    public T20090722170908ExceptionId(int sampleid, short status, int genotypingrunid, Date date, int sampleqcstatusid) {
       this.sampleid = sampleid;
       this.status = status;
       this.genotypingrunid = genotypingrunid;
       this.date = date;
       this.sampleqcstatusid = sampleqcstatusid;
    }
   

    @Column(name="SAMPLEID", nullable=false)
    public int getSampleid() {
        return this.sampleid;
    }
    
    public void setSampleid(int sampleid) {
        this.sampleid = sampleid;
    }

    @Column(name="STATUS", nullable=false)
    public short getStatus() {
        return this.status;
    }
    
    public void setStatus(short status) {
        this.status = status;
    }

    @Column(name="GENOTYPINGRUNID", nullable=false)
    public int getGenotypingrunid() {
        return this.genotypingrunid;
    }
    
    public void setGenotypingrunid(int genotypingrunid) {
        this.genotypingrunid = genotypingrunid;
    }

    @Column(name="DATE", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name="SAMPLEQCSTATUSID", nullable=false)
    public int getSampleqcstatusid() {
        return this.sampleqcstatusid;
    }
    
    public void setSampleqcstatusid(int sampleqcstatusid) {
        this.sampleqcstatusid = sampleqcstatusid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof T20090722170908ExceptionId) ) return false;
		 T20090722170908ExceptionId castOther = ( T20090722170908ExceptionId ) other; 
         
		 return (this.getSampleid()==castOther.getSampleid())
 && (this.getStatus()==castOther.getStatus())
 && (this.getGenotypingrunid()==castOther.getGenotypingrunid())
 && ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) )
 && (this.getSampleqcstatusid()==castOther.getSampleqcstatusid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSampleid();
         result = 37 * result + this.getStatus();
         result = 37 * result + this.getGenotypingrunid();
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         result = 37 * result + this.getSampleqcstatusid();
         return result;
   }   


}


