package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * T20090115124106Exception generated by hbm2java
 */
@Entity
@Table(name="T20090115_124106_EXCEPTION"
    ,schema="ALLERGEN"
)
public class T20090115124106Exception  implements java.io.Serializable {


     private T20090115124106ExceptionId id;

    public T20090115124106Exception() {
    }

    public T20090115124106Exception(T20090115124106ExceptionId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sampleid", column=@Column(name="SAMPLEID", nullable=false) ), 
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=25) ), 
        @AttributeOverride(name="valid", column=@Column(name="VALID") ), 
        @AttributeOverride(name="numcalls", column=@Column(name="NUMCALLS", nullable=false) ), 
        @AttributeOverride(name="location", column=@Column(name="LOCATION", nullable=false, length=100) ), 
        @AttributeOverride(name="numnocalls", column=@Column(name="NUMNOCALLS", nullable=false) ) } )
    public T20090115124106ExceptionId getId() {
        return this.id;
    }
    
    public void setId(T20090115124106ExceptionId id) {
        this.id = id;
    }




}


