package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * T20090804155500ExceptionId generated by hbm2java
 */
@Embeddable
public class T20090804155500ExceptionId  implements java.io.Serializable {


     private int containertypeid;
     private String description;
     private int rows;
     private int columns;
     private int sortorder;
     private Short stock;
     private Short materialtype;

    public T20090804155500ExceptionId() {
    }

	
    public T20090804155500ExceptionId(int containertypeid, String description, int rows, int columns, int sortorder) {
        this.containertypeid = containertypeid;
        this.description = description;
        this.rows = rows;
        this.columns = columns;
        this.sortorder = sortorder;
    }
    public T20090804155500ExceptionId(int containertypeid, String description, int rows, int columns, int sortorder, Short stock, Short materialtype) {
       this.containertypeid = containertypeid;
       this.description = description;
       this.rows = rows;
       this.columns = columns;
       this.sortorder = sortorder;
       this.stock = stock;
       this.materialtype = materialtype;
    }
   

    @Column(name="CONTAINERTYPEID", nullable=false)
    public int getContainertypeid() {
        return this.containertypeid;
    }
    
    public void setContainertypeid(int containertypeid) {
        this.containertypeid = containertypeid;
    }

    @Column(name="DESCRIPTION", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="ROWS", nullable=false)
    public int getRows() {
        return this.rows;
    }
    
    public void setRows(int rows) {
        this.rows = rows;
    }

    @Column(name="COLUMNS", nullable=false)
    public int getColumns() {
        return this.columns;
    }
    
    public void setColumns(int columns) {
        this.columns = columns;
    }

    @Column(name="SORTORDER", nullable=false)
    public int getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(int sortorder) {
        this.sortorder = sortorder;
    }

    @Column(name="STOCK")
    public Short getStock() {
        return this.stock;
    }
    
    public void setStock(Short stock) {
        this.stock = stock;
    }

    @Column(name="MATERIALTYPE")
    public Short getMaterialtype() {
        return this.materialtype;
    }
    
    public void setMaterialtype(Short materialtype) {
        this.materialtype = materialtype;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof T20090804155500ExceptionId) ) return false;
		 T20090804155500ExceptionId castOther = ( T20090804155500ExceptionId ) other; 
         
		 return (this.getContainertypeid()==castOther.getContainertypeid())
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && (this.getRows()==castOther.getRows())
 && (this.getColumns()==castOther.getColumns())
 && (this.getSortorder()==castOther.getSortorder())
 && ( (this.getStock()==castOther.getStock()) || ( this.getStock()!=null && castOther.getStock()!=null && this.getStock().equals(castOther.getStock()) ) )
 && ( (this.getMaterialtype()==castOther.getMaterialtype()) || ( this.getMaterialtype()!=null && castOther.getMaterialtype()!=null && this.getMaterialtype().equals(castOther.getMaterialtype()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContainertypeid();
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + this.getRows();
         result = 37 * result + this.getColumns();
         result = 37 * result + this.getSortorder();
         result = 37 * result + ( getStock() == null ? 0 : this.getStock().hashCode() );
         result = 37 * result + ( getMaterialtype() == null ? 0 : this.getMaterialtype().hashCode() );
         return result;
   }   


}


