package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * T20090723154130Exception generated by hbm2java
 */
@Entity
@Table(name="T20090723_154130_EXCEPTION"
    ,schema="ALLERGEN"
)
public class T20090723154130Exception  implements java.io.Serializable {


     private T20090723154130ExceptionId id;

    public T20090723154130Exception() {
    }

    public T20090723154130Exception(T20090723154130ExceptionId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sampleid", column=@Column(name="SAMPLEID", nullable=false) ), 
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=25) ), 
        @AttributeOverride(name="valid", column=@Column(name="VALID", nullable=false) ), 
        @AttributeOverride(name="numcalls", column=@Column(name="NUMCALLS") ), 
        @AttributeOverride(name="location", column=@Column(name="LOCATION", length=100) ), 
        @AttributeOverride(name="numnocalls", column=@Column(name="NUMNOCALLS") ), 
        @AttributeOverride(name="freezerlocation", column=@Column(name="FREEZERLOCATION", length=45) ), 
        @AttributeOverride(name="concentration", column=@Column(name="CONCENTRATION", precision=53, scale=0) ), 
        @AttributeOverride(name="parent", column=@Column(name="PARENT") ), 
        @AttributeOverride(name="sampletypeid", column=@Column(name="SAMPLETYPEID") ), 
        @AttributeOverride(name="sampleprocessid", column=@Column(name="SAMPLEPROCESSID") ), 
        @AttributeOverride(name="parentid", column=@Column(name="PARENTID") ), 
        @AttributeOverride(name="datecollected", column=@Column(name="DATECOLLECTED", nullable=false, length=10) ), 
        @AttributeOverride(name="comments", column=@Column(name="COMMENTS", length=200) ) } )
    public T20090723154130ExceptionId getId() {
        return this.id;
    }
    
    public void setId(T20090723154130ExceptionId id) {
        this.id = id;
    }




}


