package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblanalysisjobsId generated by hbm2java
 */
@Embeddable
public class TblanalysisjobsId  implements java.io.Serializable {


     private int jobid;
     private String status;
     private Date startdate;
     private Double pvalue;
     private Double oddsratio;
     private String snps;
     private String phenotype;
     private String conditioning;

    public TblanalysisjobsId() {
    }

	
    public TblanalysisjobsId(int jobid, String status, Date startdate) {
        this.jobid = jobid;
        this.status = status;
        this.startdate = startdate;
    }
    public TblanalysisjobsId(int jobid, String status, Date startdate, Double pvalue, Double oddsratio, String snps, String phenotype, String conditioning) {
       this.jobid = jobid;
       this.status = status;
       this.startdate = startdate;
       this.pvalue = pvalue;
       this.oddsratio = oddsratio;
       this.snps = snps;
       this.phenotype = phenotype;
       this.conditioning = conditioning;
    }
   

    @Column(name="JOBID", nullable=false)
    public int getJobid() {
        return this.jobid;
    }
    
    public void setJobid(int jobid) {
        this.jobid = jobid;
    }

    @Column(name="STATUS", nullable=false, length=145)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name="STARTDATE", nullable=false, length=26)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Column(name="PVALUE", precision=53, scale=0)
    public Double getPvalue() {
        return this.pvalue;
    }
    
    public void setPvalue(Double pvalue) {
        this.pvalue = pvalue;
    }

    @Column(name="ODDSRATIO", precision=53, scale=0)
    public Double getOddsratio() {
        return this.oddsratio;
    }
    
    public void setOddsratio(Double oddsratio) {
        this.oddsratio = oddsratio;
    }

    @Column(name="SNPS")
    public String getSnps() {
        return this.snps;
    }
    
    public void setSnps(String snps) {
        this.snps = snps;
    }

    @Column(name="PHENOTYPE", length=45)
    public String getPhenotype() {
        return this.phenotype;
    }
    
    public void setPhenotype(String phenotype) {
        this.phenotype = phenotype;
    }

    @Column(name="CONDITIONING")
    public String getConditioning() {
        return this.conditioning;
    }
    
    public void setConditioning(String conditioning) {
        this.conditioning = conditioning;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblanalysisjobsId) ) return false;
		 TblanalysisjobsId castOther = ( TblanalysisjobsId ) other; 
         
		 return (this.getJobid()==castOther.getJobid())
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getStartdate()==castOther.getStartdate()) || ( this.getStartdate()!=null && castOther.getStartdate()!=null && this.getStartdate().equals(castOther.getStartdate()) ) )
 && ( (this.getPvalue()==castOther.getPvalue()) || ( this.getPvalue()!=null && castOther.getPvalue()!=null && this.getPvalue().equals(castOther.getPvalue()) ) )
 && ( (this.getOddsratio()==castOther.getOddsratio()) || ( this.getOddsratio()!=null && castOther.getOddsratio()!=null && this.getOddsratio().equals(castOther.getOddsratio()) ) )
 && ( (this.getSnps()==castOther.getSnps()) || ( this.getSnps()!=null && castOther.getSnps()!=null && this.getSnps().equals(castOther.getSnps()) ) )
 && ( (this.getPhenotype()==castOther.getPhenotype()) || ( this.getPhenotype()!=null && castOther.getPhenotype()!=null && this.getPhenotype().equals(castOther.getPhenotype()) ) )
 && ( (this.getConditioning()==castOther.getConditioning()) || ( this.getConditioning()!=null && castOther.getConditioning()!=null && this.getConditioning().equals(castOther.getConditioning()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getJobid();
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getStartdate() == null ? 0 : this.getStartdate().hashCode() );
         result = 37 * result + ( getPvalue() == null ? 0 : this.getPvalue().hashCode() );
         result = 37 * result + ( getOddsratio() == null ? 0 : this.getOddsratio().hashCode() );
         result = 37 * result + ( getSnps() == null ? 0 : this.getSnps().hashCode() );
         result = 37 * result + ( getPhenotype() == null ? 0 : this.getPhenotype().hashCode() );
         result = 37 * result + ( getConditioning() == null ? 0 : this.getConditioning().hashCode() );
         return result;
   }   


}


