package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblanalysisjobs generated by hbm2java
 */
@Entity
@Table(name="TBLANALYSISJOBS"
    ,schema="ALLERGEN"
)
public class Tblanalysisjobs  implements java.io.Serializable {


     private TblanalysisjobsId id;

    public Tblanalysisjobs() {
    }

    public Tblanalysisjobs(TblanalysisjobsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="jobid", column=@Column(name="JOBID", nullable=false) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", nullable=false, length=145) ), 
        @AttributeOverride(name="startdate", column=@Column(name="STARTDATE", nullable=false, length=26) ), 
        @AttributeOverride(name="pvalue", column=@Column(name="PVALUE", precision=53, scale=0) ), 
        @AttributeOverride(name="oddsratio", column=@Column(name="ODDSRATIO", precision=53, scale=0) ), 
        @AttributeOverride(name="snps", column=@Column(name="SNPS") ), 
        @AttributeOverride(name="phenotype", column=@Column(name="PHENOTYPE", length=45) ), 
        @AttributeOverride(name="conditioning", column=@Column(name="CONDITIONING") ) } )
    public TblanalysisjobsId getId() {
        return this.id;
    }
    
    public void setId(TblanalysisjobsId id) {
        this.id = id;
    }




}


