package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblcontainercontentsMetaData generated by hbm2java
 */
@Entity
@Table(name="TBLCONTAINERCONTENTS_META_DATA"
    ,schema="ALLERGEN"
)
public class TblcontainercontentsMetaData  implements java.io.Serializable {


     private int sysid;
     private Tblsimsusers tblsimsusers;
     private String propertyName;
     private String shortName;
     private String longName;
     private int viewColumnNumber;
     private int isSortable;
     private int isEditable;
     private int showInReports;
     private int createdBy;
     private Integer modifiedBy;
     private Date created;
     private Date modified;
     private String commentary;

    public TblcontainercontentsMetaData() {
    }

	
    public TblcontainercontentsMetaData(int sysid, Tblsimsusers tblsimsusers, String propertyName, String shortName, String longName, int viewColumnNumber, int isSortable, int isEditable, int showInReports, int createdBy, Date created) {
        this.sysid = sysid;
        this.tblsimsusers = tblsimsusers;
        this.propertyName = propertyName;
        this.shortName = shortName;
        this.longName = longName;
        this.viewColumnNumber = viewColumnNumber;
        this.isSortable = isSortable;
        this.isEditable = isEditable;
        this.showInReports = showInReports;
        this.createdBy = createdBy;
        this.created = created;
    }
    public TblcontainercontentsMetaData(int sysid, Tblsimsusers tblsimsusers, String propertyName, String shortName, String longName, int viewColumnNumber, int isSortable, int isEditable, int showInReports, int createdBy, Integer modifiedBy, Date created, Date modified, String commentary) {
       this.sysid = sysid;
       this.tblsimsusers = tblsimsusers;
       this.propertyName = propertyName;
       this.shortName = shortName;
       this.longName = longName;
       this.viewColumnNumber = viewColumnNumber;
       this.isSortable = isSortable;
       this.isEditable = isEditable;
       this.showInReports = showInReports;
       this.createdBy = createdBy;
       this.modifiedBy = modifiedBy;
       this.created = created;
       this.modified = modified;
       this.commentary = commentary;
    }
   
     @Id 
    
    @Column(name="SYSID", unique=true, nullable=false)
    public int getSysid() {
        return this.sysid;
    }
    
    public void setSysid(int sysid) {
        this.sysid = sysid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERID", nullable=false)
    public Tblsimsusers getTblsimsusers() {
        return this.tblsimsusers;
    }
    
    public void setTblsimsusers(Tblsimsusers tblsimsusers) {
        this.tblsimsusers = tblsimsusers;
    }
    
    @Column(name="PROPERTY_NAME", nullable=false, length=200)
    public String getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }
    
    @Column(name="SHORT_NAME", nullable=false, length=200)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    
    @Column(name="LONG_NAME", nullable=false, length=200)
    public String getLongName() {
        return this.longName;
    }
    
    public void setLongName(String longName) {
        this.longName = longName;
    }
    
    @Column(name="VIEW_COLUMN_NUMBER", nullable=false)
    public int getViewColumnNumber() {
        return this.viewColumnNumber;
    }
    
    public void setViewColumnNumber(int viewColumnNumber) {
        this.viewColumnNumber = viewColumnNumber;
    }
    
    @Column(name="IS_SORTABLE", nullable=false)
    public int getIsSortable() {
        return this.isSortable;
    }
    
    public void setIsSortable(int isSortable) {
        this.isSortable = isSortable;
    }
    
    @Column(name="IS_EDITABLE", nullable=false)
    public int getIsEditable() {
        return this.isEditable;
    }
    
    public void setIsEditable(int isEditable) {
        this.isEditable = isEditable;
    }
    
    @Column(name="SHOW_IN_REPORTS", nullable=false)
    public int getShowInReports() {
        return this.showInReports;
    }
    
    public void setShowInReports(int showInReports) {
        this.showInReports = showInReports;
    }
    
    @Column(name="CREATED_BY", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    
    @Column(name="MODIFIED_BY")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=26)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="COMMENTARY")
    public String getCommentary() {
        return this.commentary;
    }
    
    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }




}


