package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import ca.ubc.icapture.genapha.slims.config.PreventAnyUdate;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblcontainertypes generated by hbm2java
 */
@Entity
@EntityListeners(PreventAnyUdate.class)
@Table(name="TBLCONTAINERTYPES"
    ,schema="ALLERGEN"
)
public class Tblcontainertypes  implements java.io.Serializable {


     private int containertypeid;
     private String description;
     private int rows;
     private int columns;
     private int sortorder;
     @JsonIgnoreProperties("tblcontainertypes")
     private Set<Tblcontainers> tblcontainerses = new HashSet<Tblcontainers>(0);

    public Tblcontainertypes() {
    }

	
    public Tblcontainertypes(int containertypeid, String description, int rows, int columns, int sortorder) {
        this.containertypeid = containertypeid;
        this.description = description;
        this.rows = rows;
        this.columns = columns;
        this.sortorder = sortorder;
    }
    public Tblcontainertypes(int containertypeid, String description, int rows, int columns, int sortorder, Set<Tblcontainers> tblcontainerses) {
       this.containertypeid = containertypeid;
       this.description = description;
       this.rows = rows;
       this.columns = columns;
       this.sortorder = sortorder;
       this.tblcontainerses = tblcontainerses;
    }
   
     @Id 
    
    @Column(name="CONTAINERTYPEID", unique=true, nullable=false)
    public int getContainertypeid() {
        return this.containertypeid;
    }
    
    public void setContainertypeid(int containertypeid) {
        this.containertypeid = containertypeid;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="ROWS", nullable=false)
    public int getRows() {
        return this.rows;
    }
    
    public void setRows(int rows) {
        this.rows = rows;
    }
    
    @Column(name="COLUMNS", nullable=false)
    public int getColumns() {
        return this.columns;
    }
    
    public void setColumns(int columns) {
        this.columns = columns;
    }
    
    @Column(name="SORTORDER", nullable=false)
    public int getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(int sortorder) {
        this.sortorder = sortorder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcontainertypes")
    public Set<Tblcontainers> getTblcontainerses() {
        return this.tblcontainerses;
    }
    
    public void setTblcontainerses(Set<Tblcontainers> tblcontainerses) {
        this.tblcontainerses = tblcontainerses;
    }




}


