package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblcategories generated by hbm2java
 */
@Entity
@Table(name="TBLCATEGORIES"
    ,schema="ALLERGEN"
)
public class Tblcategories  implements java.io.Serializable {


     private TblcategoriesId id;

    public Tblcategories() {
    }

    public Tblcategories(TblcategoriesId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="categoryid", column=@Column(name="CATEGORYID", nullable=false) ), 
        @AttributeOverride(name="parentid", column=@Column(name="PARENTID") ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=100) ), 
        @AttributeOverride(name="description", column=@Column(name="DESCRIPTION", nullable=false) ) } )
    public TblcategoriesId getId() {
        return this.id;
    }
    
    public void setId(TblcategoriesId id) {
        this.id = id;
    }




}


