package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblcohortpopulations generated by hbm2java
 */
@Entity
@Table(name="TBLCOHORTPOPULATIONS"
    ,schema="ALLERGEN"
)
public class Tblcohortpopulations  implements java.io.Serializable {


     private long cohortpopulationid;
     @JsonIgnoreProperties("tblcohortpopulationses")
     private Tblcohortlookup tblcohortlookup;
     private String populationname;

    public Tblcohortpopulations() {
    }

    public Tblcohortpopulations(long cohortpopulationid, Tblcohortlookup tblcohortlookup, String populationname) {
       this.cohortpopulationid = cohortpopulationid;
       this.tblcohortlookup = tblcohortlookup;
       this.populationname = populationname;
    }
   
     @Id 
    
    @Column(name="COHORTPOPULATIONID", unique=true, nullable=false)
    public long getCohortpopulationid() {
        return this.cohortpopulationid;
    }
    
    public void setCohortpopulationid(long cohortpopulationid) {
        this.cohortpopulationid = cohortpopulationid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COHORTID", nullable=false)
    public Tblcohortlookup getTblcohortlookup() {
        return this.tblcohortlookup;
    }
    
    public void setTblcohortlookup(Tblcohortlookup tblcohortlookup) {
        this.tblcohortlookup = tblcohortlookup;
    }
    
    @Column(name="POPULATIONNAME", nullable=false, length=25)
    public String getPopulationname() {
        return this.populationname;
    }
    
    public void setPopulationname(String populationname) {
        this.populationname = populationname;
    }




}


