package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblcontainercontentslog generated by hbm2java
 */
@Entity
@Table(name="TBLCONTAINERCONTENTSLOG"
    ,schema="ALLERGEN"
)
public class Tblcontainercontentslog  implements java.io.Serializable {


     private TblcontainercontentslogId id;

    public Tblcontainercontentslog() {
    }

    public Tblcontainercontentslog(TblcontainercontentslogId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="containerid", column=@Column(name="CONTAINERID", nullable=false) ), 
        @AttributeOverride(name="row", column=@Column(name="ROW", nullable=false) ), 
        @AttributeOverride(name="column", column=@Column(name="COLUMN", nullable=false) ), 
        @AttributeOverride(name="sampleid", column=@Column(name="SAMPLEID", nullable=false) ), 
        @AttributeOverride(name="volume", column=@Column(name="VOLUME", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="concentration", column=@Column(name="CONCENTRATION", nullable=false, precision=53, scale=0) ), 
        @AttributeOverride(name="containercontentsid", column=@Column(name="CONTAINERCONTENTSID", nullable=false) ), 
        @AttributeOverride(name="parentid", column=@Column(name="PARENTID", nullable=false) ), 
        @AttributeOverride(name="contaminated", column=@Column(name="CONTAMINATED", nullable=false) ), 
        @AttributeOverride(name="dilution", column=@Column(name="DILUTION", nullable=false, length=10) ), 
        @AttributeOverride(name="comments", column=@Column(name="COMMENTS", length=300) ), 
        @AttributeOverride(name="created", column=@Column(name="CREATED", nullable=false, length=26) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY", nullable=false) ), 
        @AttributeOverride(name="modified", column=@Column(name="MODIFIED", length=26) ), 
        @AttributeOverride(name="modifiedBy", column=@Column(name="MODIFIED_BY") ), 
        @AttributeOverride(name="quantified", column=@Column(name="QUANTIFIED", length=10) ), 
        @AttributeOverride(name="updated", column=@Column(name="UPDATED", nullable=false, length=26) ) } )
    public TblcontainercontentslogId getId() {
        return this.id;
    }
    
    public void setId(TblcontainercontentslogId id) {
        this.id = id;
    }




}


