package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblcontrol generated by hbm2java
 */
@Entity
@Table(name="TBLCONTROL"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="DESCRIPTION") 
)
public class Tblcontrol  implements java.io.Serializable {


     private int controlid;
     private String description;
     private short type;
     private Set<Tblcontrolwells> tblcontrolwellses = new HashSet<Tblcontrolwells>(0);

    public Tblcontrol() {
    }

	
    public Tblcontrol(int controlid, String description, short type) {
        this.controlid = controlid;
        this.description = description;
        this.type = type;
    }
    public Tblcontrol(int controlid, String description, short type, Set<Tblcontrolwells> tblcontrolwellses) {
       this.controlid = controlid;
       this.description = description;
       this.type = type;
       this.tblcontrolwellses = tblcontrolwellses;
    }
   
     @Id 
    
    @Column(name="CONTROLID", unique=true, nullable=false)
    public int getControlid() {
        return this.controlid;
    }
    
    public void setControlid(int controlid) {
        this.controlid = controlid;
    }
    
    @Column(name="DESCRIPTION", unique=true, nullable=false, length=25)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="TYPE", nullable=false)
    public short getType() {
        return this.type;
    }
    
    public void setType(short type) {
        this.type = type;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcontrol")
    public Set<Tblcontrolwells> getTblcontrolwellses() {
        return this.tblcontrolwellses;
    }
    
    public void setTblcontrolwellses(Set<Tblcontrolwells> tblcontrolwellses) {
        this.tblcontrolwellses = tblcontrolwellses;
    }




}


