package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblcategoriesId generated by hbm2java
 */
@Embeddable
public class TblcategoriesId  implements java.io.Serializable {


     private long categoryid;
     private Long parentid;
     private String name;
     private String description;

    public TblcategoriesId() {
    }

	
    public TblcategoriesId(long categoryid, String name, String description) {
        this.categoryid = categoryid;
        this.name = name;
        this.description = description;
    }
    public TblcategoriesId(long categoryid, Long parentid, String name, String description) {
       this.categoryid = categoryid;
       this.parentid = parentid;
       this.name = name;
       this.description = description;
    }
   

    @Column(name="CATEGORYID", nullable=false)
    public long getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(long categoryid) {
        this.categoryid = categoryid;
    }

    @Column(name="PARENTID")
    public Long getParentid() {
        return this.parentid;
    }
    
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    @Column(name="NAME", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblcategoriesId) ) return false;
		 TblcategoriesId castOther = ( TblcategoriesId ) other; 
         
		 return (this.getCategoryid()==castOther.getCategoryid())
 && ( (this.getParentid()==castOther.getParentid()) || ( this.getParentid()!=null && castOther.getParentid()!=null && this.getParentid().equals(castOther.getParentid()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCategoryid();
         result = 37 * result + ( getParentid() == null ? 0 : this.getParentid().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         return result;
   }   


}


