package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import ca.ubc.icapture.genapha.slims.config.PreventAnyUdate;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tblcontainercontents generated by hbm2java
 */
@Entity
@EntityListeners(PreventAnyUdate.class)
@Table(name="TBLCONTAINERCONTENTS"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames={"CONTAINERID", "ROW", "COLUMN"}) 
)
public class Tblcontainercontents  implements java.io.Serializable {


     private int containercontentsid;
     @JsonIgnore
     private Tblcontainers tblcontainers;
     @JsonIgnore
     private Tblsamples tblsamples;
     @JsonIgnoreProperties("tblcontainercontentses")
     private Tblmaterialtype tblmaterialtype;
     private int row;
     private int column;
     private double volume;
     private double concentration;
     private int parentid;
     private short contaminated;
     private String dilution;
     private String comments;
     private Date created;
     private int createdBy;
     private Date modified;
     private Integer modifiedBy;
     private Date quantified;
     private Date amplificationdate;
     private String barcode;
     @JsonIgnoreProperties("tblcontainercontents")
     private Set<Tblgenotypes> tblgenotypeses = new HashSet<Tblgenotypes>(0);
     @JsonIgnore
     private Set<Tblgenotypingrunsamplestatus> tblgenotypingrunsamplestatuses = new HashSet<Tblgenotypingrunsamplestatus>(0);

    public Tblcontainercontents() {
    }

	
    public Tblcontainercontents(int containercontentsid, Tblcontainers tblcontainers, Tblsamples tblsamples, Tblmaterialtype tblmaterialtype, int row, int column, double volume, double concentration, int parentid, short contaminated, String dilution, Date created, int createdBy) {
        this.containercontentsid = containercontentsid;
        this.tblcontainers = tblcontainers;
        this.tblsamples = tblsamples;
        this.tblmaterialtype = tblmaterialtype;
        this.row = row;
        this.column = column;
        this.volume = volume;
        this.concentration = concentration;
        this.parentid = parentid;
        this.contaminated = contaminated;
        this.dilution = dilution;
        this.created = created;
        this.createdBy = createdBy;
    }
    public Tblcontainercontents(int containercontentsid, Tblcontainers tblcontainers, Tblsamples tblsamples, Tblmaterialtype tblmaterialtype, int row, int column, double volume, double concentration, int parentid, short contaminated, String dilution, String comments, Date created, int createdBy, Date modified, Integer modifiedBy, Date quantified, Date amplificationdate, String barcode, Set<Tblgenotypes> tblgenotypeses, Set<Tblgenotypingrunsamplestatus> tblgenotypingrunsamplestatuses) {
       this.containercontentsid = containercontentsid;
       this.tblcontainers = tblcontainers;
       this.tblsamples = tblsamples;
       this.tblmaterialtype = tblmaterialtype;
       this.row = row;
       this.column = column;
       this.volume = volume;
       this.concentration = concentration;
       this.parentid = parentid;
       this.contaminated = contaminated;
       this.dilution = dilution;
       this.comments = comments;
       this.created = created;
       this.createdBy = createdBy;
       this.modified = modified;
       this.modifiedBy = modifiedBy;
       this.quantified = quantified;
       this.amplificationdate = amplificationdate;
       this.barcode = barcode;
       this.tblgenotypeses = tblgenotypeses;
       this.tblgenotypingrunsamplestatuses = tblgenotypingrunsamplestatuses;
    }
   
     @Id 
    
    @Column(name="CONTAINERCONTENTSID", unique=true, nullable=false)
    public int getContainercontentsid() {
        return this.containercontentsid;
    }
    
    public void setContainercontentsid(int containercontentsid) {
        this.containercontentsid = containercontentsid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTAINERID", nullable=false)
    public Tblcontainers getTblcontainers() {
        return this.tblcontainers;
    }
    
    public void setTblcontainers(Tblcontainers tblcontainers) {
        this.tblcontainers = tblcontainers;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SAMPLEID", nullable=false)
    public Tblsamples getTblsamples() {
        return this.tblsamples;
    }
    
    public void setTblsamples(Tblsamples tblsamples) {
        this.tblsamples = tblsamples;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="MATERIALTYPEID", nullable=false)
    public Tblmaterialtype getTblmaterialtype() {
        return this.tblmaterialtype;
    }
    
    public void setTblmaterialtype(Tblmaterialtype tblmaterialtype) {
        this.tblmaterialtype = tblmaterialtype;
    }
    
    @Column(name="ROW", nullable=false)
    public int getRow() {
        return this.row;
    }
    
    public void setRow(int row) {
        this.row = row;
    }
    
    @Column(name="COLUMN", nullable=false)
    public int getColumn() {
        return this.column;
    }
    
    public void setColumn(int column) {
        this.column = column;
    }
    
    @Column(name="VOLUME", nullable=false, precision=53, scale=0)
    public double getVolume() {
        return this.volume;
    }
    
    public void setVolume(double volume) {
        this.volume = volume;
    }
    
    @Column(name="CONCENTRATION", nullable=false, precision=53, scale=0)
    public double getConcentration() {
        return this.concentration;
    }
    
    public void setConcentration(double concentration) {
        this.concentration = concentration;
    }
    
    @Column(name="PARENTID", nullable=false)
    public int getParentid() {
        return this.parentid;
    }
    
    public void setParentid(int parentid) {
        this.parentid = parentid;
    }
    
    @Column(name="CONTAMINATED", nullable=false)
    public short getContaminated() {
        return this.contaminated;
    }
    
    public void setContaminated(short contaminated) {
        this.contaminated = contaminated;
    }
    
    @Column(name="DILUTION", nullable=false, length=10)
    public String getDilution() {
        return this.dilution;
    }
    
    public void setDilution(String dilution) {
        this.dilution = dilution;
    }
    
    @Column(name="COMMENTS", length=300)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    
    @Column(name="CREATED_BY", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=26)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="MODIFIED_BY")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="QUANTIFIED", length=10)
    public Date getQuantified() {
        return this.quantified;
    }
    
    public void setQuantified(Date quantified) {
        this.quantified = quantified;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="AMPLIFICATIONDATE", length=10)
    public Date getAmplificationdate() {
        return this.amplificationdate;
    }
    
    public void setAmplificationdate(Date amplificationdate) {
        this.amplificationdate = amplificationdate;
    }
    
    @Column(name="BARCODE", length=20)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcontainercontents")
    public Set<Tblgenotypes> getTblgenotypeses() {
        return this.tblgenotypeses;
    }
    
    public void setTblgenotypeses(Set<Tblgenotypes> tblgenotypeses) {
        this.tblgenotypeses = tblgenotypeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcontainercontents")
    public Set<Tblgenotypingrunsamplestatus> getTblgenotypingrunsamplestatuses() {
        return this.tblgenotypingrunsamplestatuses;
    }
    
    public void setTblgenotypingrunsamplestatuses(Set<Tblgenotypingrunsamplestatus> tblgenotypingrunsamplestatuses) {
        this.tblgenotypingrunsamplestatuses = tblgenotypingrunsamplestatuses;
    }




}


