package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblcontrollayoutwells generated by hbm2java
 */
@Entity
@Table(name="TBLCONTROLLAYOUTWELLS"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ROW", "COLUMN", "LAYOUTNAME"}) 
)
public class Tblcontrollayoutwells  implements java.io.Serializable {


     private int controllayoutid;
     private int row;
     private int column;
     private Integer defaultcontrol;
     private String layoutname;

    public Tblcontrollayoutwells() {
    }

	
    public Tblcontrollayoutwells(int controllayoutid, int row, int column, String layoutname) {
        this.controllayoutid = controllayoutid;
        this.row = row;
        this.column = column;
        this.layoutname = layoutname;
    }
    public Tblcontrollayoutwells(int controllayoutid, int row, int column, Integer defaultcontrol, String layoutname) {
       this.controllayoutid = controllayoutid;
       this.row = row;
       this.column = column;
       this.defaultcontrol = defaultcontrol;
       this.layoutname = layoutname;
    }
   
     @Id 
    
    @Column(name="CONTROLLAYOUTID", unique=true, nullable=false)
    public int getControllayoutid() {
        return this.controllayoutid;
    }
    
    public void setControllayoutid(int controllayoutid) {
        this.controllayoutid = controllayoutid;
    }
    
    @Column(name="ROW", nullable=false)
    public int getRow() {
        return this.row;
    }
    
    public void setRow(int row) {
        this.row = row;
    }
    
    @Column(name="COLUMN", nullable=false)
    public int getColumn() {
        return this.column;
    }
    
    public void setColumn(int column) {
        this.column = column;
    }
    
    @Column(name="DEFAULTCONTROL")
    public Integer getDefaultcontrol() {
        return this.defaultcontrol;
    }
    
    public void setDefaultcontrol(Integer defaultcontrol) {
        this.defaultcontrol = defaultcontrol;
    }
    
    @Column(name="LAYOUTNAME", nullable=false, length=100)
    public String getLayoutname() {
        return this.layoutname;
    }
    
    public void setLayoutname(String layoutname) {
        this.layoutname = layoutname;
    }




}


