package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblfrequenciesId generated by hbm2java
 */
@Embeddable
public class TblfrequenciesId  implements java.io.Serializable {


     private long cohortid;
     private long ethnicityid;
     private long snpid;
     private double freq;
     private double hw;
     private double freqParent;
     private double hwParent;
     private String alelle;

    public TblfrequenciesId() {
    }

    public TblfrequenciesId(long cohortid, long ethnicityid, long snpid, double freq, double hw, double freqParent, double hwParent, String alelle) {
       this.cohortid = cohortid;
       this.ethnicityid = ethnicityid;
       this.snpid = snpid;
       this.freq = freq;
       this.hw = hw;
       this.freqParent = freqParent;
       this.hwParent = hwParent;
       this.alelle = alelle;
    }
   

    @Column(name="COHORTID", nullable=false)
    public long getCohortid() {
        return this.cohortid;
    }
    
    public void setCohortid(long cohortid) {
        this.cohortid = cohortid;
    }

    @Column(name="ETHNICITYID", nullable=false)
    public long getEthnicityid() {
        return this.ethnicityid;
    }
    
    public void setEthnicityid(long ethnicityid) {
        this.ethnicityid = ethnicityid;
    }

    @Column(name="SNPID", nullable=false)
    public long getSnpid() {
        return this.snpid;
    }
    
    public void setSnpid(long snpid) {
        this.snpid = snpid;
    }

    @Column(name="FREQ", nullable=false, precision=53, scale=0)
    public double getFreq() {
        return this.freq;
    }
    
    public void setFreq(double freq) {
        this.freq = freq;
    }

    @Column(name="HW", nullable=false, precision=53, scale=0)
    public double getHw() {
        return this.hw;
    }
    
    public void setHw(double hw) {
        this.hw = hw;
    }

    @Column(name="FREQ_PARENT", nullable=false, precision=53, scale=0)
    public double getFreqParent() {
        return this.freqParent;
    }
    
    public void setFreqParent(double freqParent) {
        this.freqParent = freqParent;
    }

    @Column(name="HW_PARENT", nullable=false, precision=53, scale=0)
    public double getHwParent() {
        return this.hwParent;
    }
    
    public void setHwParent(double hwParent) {
        this.hwParent = hwParent;
    }

    @Column(name="ALELLE", nullable=false, length=1)
    public String getAlelle() {
        return this.alelle;
    }
    
    public void setAlelle(String alelle) {
        this.alelle = alelle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblfrequenciesId) ) return false;
		 TblfrequenciesId castOther = ( TblfrequenciesId ) other; 
         
		 return (this.getCohortid()==castOther.getCohortid())
 && (this.getEthnicityid()==castOther.getEthnicityid())
 && (this.getSnpid()==castOther.getSnpid())
 && (this.getFreq()==castOther.getFreq())
 && (this.getHw()==castOther.getHw())
 && (this.getFreqParent()==castOther.getFreqParent())
 && (this.getHwParent()==castOther.getHwParent())
 && ( (this.getAlelle()==castOther.getAlelle()) || ( this.getAlelle()!=null && castOther.getAlelle()!=null && this.getAlelle().equals(castOther.getAlelle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCohortid();
         result = 37 * result + (int) this.getEthnicityid();
         result = 37 * result + (int) this.getSnpid();
         result = 37 * result + (int) this.getFreq();
         result = 37 * result + (int) this.getHw();
         result = 37 * result + (int) this.getFreqParent();
         result = 37 * result + (int) this.getHwParent();
         result = 37 * result + ( getAlelle() == null ? 0 : this.getAlelle().hashCode() );
         return result;
   }   


}


