package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblfamilyoverlap generated by hbm2java
 */
@Entity
@Table(name="TBLFAMILYOVERLAP"
    ,schema="ALLERGEN"
)
public class Tblfamilyoverlap  implements java.io.Serializable {


     private TblfamilyoverlapId id;
     private Tblcohortlookup tblcohortlookup;
     private String removefamid;

    public Tblfamilyoverlap() {
    }

	
    public Tblfamilyoverlap(TblfamilyoverlapId id) {
        this.id = id;
    }
    public Tblfamilyoverlap(TblfamilyoverlapId id, Tblcohortlookup tblcohortlookup, String removefamid) {
       this.id = id;
       this.tblcohortlookup = tblcohortlookup;
       this.removefamid = removefamid;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sagefamilyid", column=@Column(name="SAGEFAMILYID", nullable=false, length=25) ), 
        @AttributeOverride(name="asthmafamilyid", column=@Column(name="ASTHMAFAMILYID", nullable=false, length=25) ) } )
    public TblfamilyoverlapId getId() {
        return this.id;
    }
    
    public void setId(TblfamilyoverlapId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REMOVEFROMCOHORT")
    public Tblcohortlookup getTblcohortlookup() {
        return this.tblcohortlookup;
    }
    
    public void setTblcohortlookup(Tblcohortlookup tblcohortlookup) {
        this.tblcohortlookup = tblcohortlookup;
    }
    
    @Column(name="REMOVEFAMID", length=25)
    public String getRemovefamid() {
        return this.removefamid;
    }
    
    public void setRemovefamid(String removefamid) {
        this.removefamid = removefamid;
    }




}


