package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblfreezers generated by hbm2java
 */
@Entity
@Table(name="TBLFREEZERS"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="DESCRIPTION") 
)
public class Tblfreezers  implements java.io.Serializable {


     private int freezerid;
     private String description;
     private String location;
     private String temperature;
     private int sortorder;
     @JsonIgnoreProperties("tblfreezers")
     private Set<Tblcontainers> tblcontainerses = new HashSet<Tblcontainers>(0);

    public Tblfreezers() {
    }

	
    public Tblfreezers(int freezerid, String description, String location, String temperature, int sortorder) {
        this.freezerid = freezerid;
        this.description = description;
        this.location = location;
        this.temperature = temperature;
        this.sortorder = sortorder;
    }
    public Tblfreezers(int freezerid, String description, String location, String temperature, int sortorder, Set<Tblcontainers> tblcontainerses) {
       this.freezerid = freezerid;
       this.description = description;
       this.location = location;
       this.temperature = temperature;
       this.sortorder = sortorder;
       this.tblcontainerses = tblcontainerses;
    }
   
     @Id 
    
    @Column(name="FREEZERID", unique=true, nullable=false)
    public int getFreezerid() {
        return this.freezerid;
    }
    
    public void setFreezerid(int freezerid) {
        this.freezerid = freezerid;
    }
    
    @Column(name="DESCRIPTION", unique=true, nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="LOCATION", nullable=false, length=100)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    
    @Column(name="TEMPERATURE", nullable=false, length=10)
    public String getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }
    
    @Column(name="SORTORDER", nullable=false)
    public int getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(int sortorder) {
        this.sortorder = sortorder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblfreezers")
    public Set<Tblcontainers> getTblcontainerses() {
        return this.tblcontainerses;
    }
    
    public void setTblcontainerses(Set<Tblcontainers> tblcontainerses) {
        this.tblcontainerses = tblcontainerses;
    }




}


