package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblgenaphasubjects generated by hbm2java
 */
@Entity
@Table(name="TBLGENAPHASUBJECTS"
    ,schema="ALLERGEN"
)
public class Tblgenaphasubjects  implements java.io.Serializable {


     private TblgenaphasubjectsId id;

    public Tblgenaphasubjects() {
    }

    public Tblgenaphasubjects(TblgenaphasubjectsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="genaphaid", column=@Column(name="GENAPHAID", nullable=false) ), 
        @AttributeOverride(name="gender", column=@Column(name="GENDER", length=10) ), 
        @AttributeOverride(name="age", column=@Column(name="AGE", length=10) ) } )
    public TblgenaphasubjectsId getId() {
        return this.id;
    }
    
    public void setId(TblgenaphasubjectsId id) {
        this.id = id;
    }




}


