package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblgenotypingpanel generated by hbm2java
 */
@Entity
@Table(name="TBLGENOTYPINGPANEL"
    ,schema="ALLERGEN"
)
public class Tblgenotypingpanel  implements java.io.Serializable {


     private TblgenotypingpanelId id;

    public Tblgenotypingpanel() {
    }

    public Tblgenotypingpanel(TblgenotypingpanelId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="panelid", column=@Column(name="PANELID", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=25) ) } )
    public TblgenotypingpanelId getId() {
        return this.id;
    }
    
    public void setId(TblgenotypingpanelId id) {
        this.id = id;
    }




}


