package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblgenotypeId generated by hbm2java
 */
@Embeddable
public class TblgenotypeId  implements java.io.Serializable {


     private long sampleid;
     private long snpid;

    public TblgenotypeId() {
    }

    public TblgenotypeId(long sampleid, long snpid) {
       this.sampleid = sampleid;
       this.snpid = snpid;
    }
   

    @Column(name="SAMPLEID", nullable=false)
    public long getSampleid() {
        return this.sampleid;
    }
    
    public void setSampleid(long sampleid) {
        this.sampleid = sampleid;
    }

    @Column(name="SNPID", nullable=false)
    public long getSnpid() {
        return this.snpid;
    }
    
    public void setSnpid(long snpid) {
        this.snpid = snpid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblgenotypeId) ) return false;
		 TblgenotypeId castOther = ( TblgenotypeId ) other; 
         
		 return (this.getSampleid()==castOther.getSampleid())
 && (this.getSnpid()==castOther.getSnpid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getSampleid();
         result = 37 * result + (int) this.getSnpid();
         return result;
   }   


}


