package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblgenesetlookup generated by hbm2java
 */
@Entity
@Table(name="TBLGENESETLOOKUP"
    ,schema="ALLERGEN"
)
public class Tblgenesetlookup  implements java.io.Serializable {


     private long genesetid;
     private String name;
     private Set<Tblgene> tblgenes = new HashSet<Tblgene>(0);

    public Tblgenesetlookup() {
    }

	
    public Tblgenesetlookup(long genesetid, String name) {
        this.genesetid = genesetid;
        this.name = name;
    }
    public Tblgenesetlookup(long genesetid, String name, Set<Tblgene> tblgenes) {
       this.genesetid = genesetid;
       this.name = name;
       this.tblgenes = tblgenes;
    }
   
     @Id 
    
    @Column(name="GENESETID", unique=true, nullable=false)
    public long getGenesetid() {
        return this.genesetid;
    }
    
    public void setGenesetid(long genesetid) {
        this.genesetid = genesetid;
    }
    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="TBLGENESET", schema="ALLERGEN", uniqueConstraints=@UniqueConstraint(columnNames={"GENESETID", "GENEID"}), joinColumns = { 
        @JoinColumn(name="GENESETID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="GENEID", nullable=false, updatable=false) })
    public Set<Tblgene> getTblgenes() {
        return this.tblgenes;
    }
    
    public void setTblgenes(Set<Tblgene> tblgenes) {
        this.tblgenes = tblgenes;
    }




}


