package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblgenealiasId generated by hbm2java
 */
@Embeddable
public class TblgenealiasId  implements java.io.Serializable {


     private int geneid;
     private String genealias;

    public TblgenealiasId() {
    }

    public TblgenealiasId(int geneid, String genealias) {
       this.geneid = geneid;
       this.genealias = genealias;
    }
   

    @Column(name="GENEID", nullable=false)
    public int getGeneid() {
        return this.geneid;
    }
    
    public void setGeneid(int geneid) {
        this.geneid = geneid;
    }

    @Column(name="GENEALIAS", nullable=false, length=25)
    public String getGenealias() {
        return this.genealias;
    }
    
    public void setGenealias(String genealias) {
        this.genealias = genealias;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblgenealiasId) ) return false;
		 TblgenealiasId castOther = ( TblgenealiasId ) other; 
         
		 return (this.getGeneid()==castOther.getGeneid())
 && ( (this.getGenealias()==castOther.getGenealias()) || ( this.getGenealias()!=null && castOther.getGenealias()!=null && this.getGenealias().equals(castOther.getGenealias()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGeneid();
         result = 37 * result + ( getGenealias() == null ? 0 : this.getGenealias().hashCode() );
         return result;
   }   


}


