package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblgenotypes generated by hbm2java
 */
@Entity
@Table(name="TBLGENOTYPES"
    ,schema="ALLERGEN"
)
public class Tblgenotypes  implements java.io.Serializable {

     private TblgenotypesId id;
     @JsonIgnore
     private Tblcontainercontents tblcontainercontents;
     @JsonIgnore
     private Tblgenotypingruns tblgenotypingruns;
     private Tblsnp tblsnp;

    public Tblgenotypes() {
    }

    public Tblgenotypes(TblgenotypesId id, Tblcontainercontents tblcontainercontents, Tblgenotypingruns tblgenotypingruns, Tblsnp tblsnp) {
       this.id = id;
       this.tblcontainercontents = tblcontainercontents;
       this.tblgenotypingruns = tblgenotypingruns;
       this.tblsnp = tblsnp;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="genotypeid", column=@Column(name="GENOTYPEID", nullable=false) ), 
        @AttributeOverride(name="containercontentsid", column=@Column(name="CONTAINERCONTENTSID", nullable=false) ), 
        @AttributeOverride(name="genotypingrunid", column=@Column(name="GENOTYPINGRUNID", nullable=false) ), 
        @AttributeOverride(name="snpid", column=@Column(name="SNPID", nullable=false) ), 
        @AttributeOverride(name="allele1", column=@Column(name="ALLELE1", nullable=false, length=45) ), 
        @AttributeOverride(name="allele2", column=@Column(name="ALLELE2", nullable=false, length=45) ) } )
    public TblgenotypesId getId() {
        return this.id;
    }
    
    public void setId(TblgenotypesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTAINERCONTENTSID", nullable=false, insertable=false, updatable=false)
    public Tblcontainercontents getTblcontainercontents() {
        return this.tblcontainercontents;
    }
    
    public void setTblcontainercontents(Tblcontainercontents tblcontainercontents) {
        this.tblcontainercontents = tblcontainercontents;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENOTYPINGRUNID", nullable=false, insertable=false, updatable=false)
    public Tblgenotypingruns getTblgenotypingruns() {
        return this.tblgenotypingruns;
    }
    
    public void setTblgenotypingruns(Tblgenotypingruns tblgenotypingruns) {
        this.tblgenotypingruns = tblgenotypingruns;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SNPID", nullable=false, insertable=false, updatable=false)
    public Tblsnp getTblsnp() {
        return this.tblsnp;
    }
    
    public void setTblsnp(Tblsnp tblsnp) {
        this.tblsnp = tblsnp;
    }




}


