package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblgenotypingrunsamplestatus generated by hbm2java
 */
@Entity
@Table(name="TBLGENOTYPINGRUNSAMPLESTATUS"
    ,schema="ALLERGEN"
)
public class Tblgenotypingrunsamplestatus  implements java.io.Serializable {


     private TblgenotypingrunsamplestatusId id;
     private Tblcontainercontents tblcontainercontents;
     private Tblgenotypingruns tblgenotypingruns;
     private short valid;
     private double callrate;

    public Tblgenotypingrunsamplestatus() {
    }

    public Tblgenotypingrunsamplestatus(TblgenotypingrunsamplestatusId id, Tblcontainercontents tblcontainercontents, Tblgenotypingruns tblgenotypingruns, short valid, double callrate) {
       this.id = id;
       this.tblcontainercontents = tblcontainercontents;
       this.tblgenotypingruns = tblgenotypingruns;
       this.valid = valid;
       this.callrate = callrate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="genotypingrunid", column=@Column(name="GENOTYPINGRUNID", nullable=false) ), 
        @AttributeOverride(name="containercontentsid", column=@Column(name="CONTAINERCONTENTSID", nullable=false) ) } )
    public TblgenotypingrunsamplestatusId getId() {
        return this.id;
    }
    
    public void setId(TblgenotypingrunsamplestatusId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTAINERCONTENTSID", nullable=false, insertable=false, updatable=false)
    public Tblcontainercontents getTblcontainercontents() {
        return this.tblcontainercontents;
    }
    
    public void setTblcontainercontents(Tblcontainercontents tblcontainercontents) {
        this.tblcontainercontents = tblcontainercontents;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENOTYPINGRUNID", nullable=false, insertable=false, updatable=false)
    public Tblgenotypingruns getTblgenotypingruns() {
        return this.tblgenotypingruns;
    }
    
    public void setTblgenotypingruns(Tblgenotypingruns tblgenotypingruns) {
        this.tblgenotypingruns = tblgenotypingruns;
    }
    
    @Column(name="VALID", nullable=false)
    public short getValid() {
        return this.valid;
    }
    
    public void setValid(short valid) {
        this.valid = valid;
    }
    
    @Column(name="CALLRATE", nullable=false, precision=53, scale=0)
    public double getCallrate() {
        return this.callrate;
    }
    
    public void setCallrate(double callrate) {
        this.callrate = callrate;
    }




}


