package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tblgenaphausers generated by hbm2java
 */
@Entity
@Table(name="TBLGENAPHAUSERS"
    ,schema="ALLERGEN"
)
public class Tblgenaphausers  implements java.io.Serializable {


     private long userid;
     private String firstname;
     private String username;
     private String password;
     private String email;
     private String lastname;
     private Long supervisor;
     private Set<Tblgene> tblgenes = new HashSet<Tblgene>(0);
     private Set<Tblsnp> tblsnps = new HashSet<Tblsnp>(0);

    public Tblgenaphausers() {
    }

	
    public Tblgenaphausers(long userid, String firstname, String username, String password, String email) {
        this.userid = userid;
        this.firstname = firstname;
        this.username = username;
        this.password = password;
        this.email = email;
    }
    public Tblgenaphausers(long userid, String firstname, String username, String password, String email, String lastname, Long supervisor, Set<Tblgene> tblgenes, Set<Tblsnp> tblsnps) {
       this.userid = userid;
       this.firstname = firstname;
       this.username = username;
       this.password = password;
       this.email = email;
       this.lastname = lastname;
       this.supervisor = supervisor;
       this.tblgenes = tblgenes;
       this.tblsnps = tblsnps;
    }
   
     @Id 
    
    @Column(name="USERID", unique=true, nullable=false)
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }
    
    @Column(name="FIRSTNAME", nullable=false, length=50)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="USERNAME", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="PASSWORD", nullable=false, length=15)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="EMAIL", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="LASTNAME", length=50)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    
    @Column(name="SUPERVISOR")
    public Long getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(Long supervisor) {
        this.supervisor = supervisor;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="TBLUSERGENES", schema="ALLERGEN", joinColumns = { 
        @JoinColumn(name="USERID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="GENEID", nullable=false, updatable=false) })
    public Set<Tblgene> getTblgenes() {
        return this.tblgenes;
    }
    
    public void setTblgenes(Set<Tblgene> tblgenes) {
        this.tblgenes = tblgenes;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="TBLUSERSNPS", schema="ALLERGEN", joinColumns = { 
        @JoinColumn(name="USERID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="SNPID", nullable=false, updatable=false) })
    public Set<Tblsnp> getTblsnps() {
        return this.tblsnps;
    }
    
    public void setTblsnps(Set<Tblsnp> tblsnps) {
        this.tblsnps = tblsnps;
    }




}


