package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblgenotypingcentersId generated by hbm2java
 */
@Embeddable
public class TblgenotypingcentersId  implements java.io.Serializable {


     private long genotypinbgcenterid;
     private String description;

    public TblgenotypingcentersId() {
    }

    public TblgenotypingcentersId(long genotypinbgcenterid, String description) {
       this.genotypinbgcenterid = genotypinbgcenterid;
       this.description = description;
    }
   

    @Column(name="GENOTYPINBGCENTERID", nullable=false)
    public long getGenotypinbgcenterid() {
        return this.genotypinbgcenterid;
    }
    
    public void setGenotypinbgcenterid(long genotypinbgcenterid) {
        this.genotypinbgcenterid = genotypinbgcenterid;
    }

    @Column(name="DESCRIPTION", nullable=false, length=25)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblgenotypingcentersId) ) return false;
		 TblgenotypingcentersId castOther = ( TblgenotypingcentersId ) other; 
         
		 return (this.getGenotypinbgcenterid()==castOther.getGenotypinbgcenterid())
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getGenotypinbgcenterid();
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         return result;
   }   


}


