package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblgenaphasubjectsId generated by hbm2java
 */
@Embeddable
public class TblgenaphasubjectsId  implements java.io.Serializable {


     private long genaphaid;
     private String gender;
     private String age;

    public TblgenaphasubjectsId() {
    }

	
    public TblgenaphasubjectsId(long genaphaid) {
        this.genaphaid = genaphaid;
    }
    public TblgenaphasubjectsId(long genaphaid, String gender, String age) {
       this.genaphaid = genaphaid;
       this.gender = gender;
       this.age = age;
    }
   

    @Column(name="GENAPHAID", nullable=false)
    public long getGenaphaid() {
        return this.genaphaid;
    }
    
    public void setGenaphaid(long genaphaid) {
        this.genaphaid = genaphaid;
    }

    @Column(name="GENDER", length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name="AGE", length=10)
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblgenaphasubjectsId) ) return false;
		 TblgenaphasubjectsId castOther = ( TblgenaphasubjectsId ) other; 
         
		 return (this.getGenaphaid()==castOther.getGenaphaid())
 && ( (this.getGender()==castOther.getGender()) || ( this.getGender()!=null && castOther.getGender()!=null && this.getGender().equals(castOther.getGender()) ) )
 && ( (this.getAge()==castOther.getAge()) || ( this.getAge()!=null && castOther.getAge()!=null && this.getAge().equals(castOther.getAge()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getGenaphaid();
         result = 37 * result + ( getGender() == null ? 0 : this.getGender().hashCode() );
         result = 37 * result + ( getAge() == null ? 0 : this.getAge().hashCode() );
         return result;
   }   


}


