package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblgenotypingrunsamplestatusId generated by hbm2java
 */
@Embeddable
public class TblgenotypingrunsamplestatusId  implements java.io.Serializable {


     private int genotypingrunid;
     private int containercontentsid;

    public TblgenotypingrunsamplestatusId() {
    }

    public TblgenotypingrunsamplestatusId(int genotypingrunid, int containercontentsid) {
       this.genotypingrunid = genotypingrunid;
       this.containercontentsid = containercontentsid;
    }
   

    @Column(name="GENOTYPINGRUNID", nullable=false)
    public int getGenotypingrunid() {
        return this.genotypingrunid;
    }
    
    public void setGenotypingrunid(int genotypingrunid) {
        this.genotypingrunid = genotypingrunid;
    }

    @Column(name="CONTAINERCONTENTSID", nullable=false)
    public int getContainercontentsid() {
        return this.containercontentsid;
    }
    
    public void setContainercontentsid(int containercontentsid) {
        this.containercontentsid = containercontentsid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblgenotypingrunsamplestatusId) ) return false;
		 TblgenotypingrunsamplestatusId castOther = ( TblgenotypingrunsamplestatusId ) other; 
         
		 return (this.getGenotypingrunid()==castOther.getGenotypingrunid())
 && (this.getContainercontentsid()==castOther.getContainercontentsid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGenotypingrunid();
         result = 37 * result + this.getContainercontentsid();
         return result;
   }   


}


