package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblgenotypingrunsnpstatusId generated by hbm2java
 */
@Embeddable
public class TblgenotypingrunsnpstatusId  implements java.io.Serializable {


     private int genotypingrunid;
     private int snpid;

    public TblgenotypingrunsnpstatusId() {
    }

    public TblgenotypingrunsnpstatusId(int genotypingrunid, int snpid) {
       this.genotypingrunid = genotypingrunid;
       this.snpid = snpid;
    }
   

    @Column(name="GENOTYPINGRUNID", nullable=false)
    public int getGenotypingrunid() {
        return this.genotypingrunid;
    }
    
    public void setGenotypingrunid(int genotypingrunid) {
        this.genotypingrunid = genotypingrunid;
    }

    @Column(name="SNPID", nullable=false)
    public int getSnpid() {
        return this.snpid;
    }
    
    public void setSnpid(int snpid) {
        this.snpid = snpid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblgenotypingrunsnpstatusId) ) return false;
		 TblgenotypingrunsnpstatusId castOther = ( TblgenotypingrunsnpstatusId ) other; 
         
		 return (this.getGenotypingrunid()==castOther.getGenotypingrunid())
 && (this.getSnpid()==castOther.getSnpid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGenotypingrunid();
         result = 37 * result + this.getSnpid();
         return result;
   }   


}


