package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblgwassnpstatusId generated by hbm2java
 */
@Embeddable
public class TblgwassnpstatusId  implements java.io.Serializable {


     private short gwasdatasetid;
     private String rsnumber;

    public TblgwassnpstatusId() {
    }

    public TblgwassnpstatusId(short gwasdatasetid, String rsnumber) {
       this.gwasdatasetid = gwasdatasetid;
       this.rsnumber = rsnumber;
    }
   

    @Column(name="GWASDATASETID", nullable=false)
    public short getGwasdatasetid() {
        return this.gwasdatasetid;
    }
    
    public void setGwasdatasetid(short gwasdatasetid) {
        this.gwasdatasetid = gwasdatasetid;
    }

    @Column(name="RSNUMBER", nullable=false, length=60)
    public String getRsnumber() {
        return this.rsnumber;
    }
    
    public void setRsnumber(String rsnumber) {
        this.rsnumber = rsnumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblgwassnpstatusId) ) return false;
		 TblgwassnpstatusId castOther = ( TblgwassnpstatusId ) other; 
         
		 return (this.getGwasdatasetid()==castOther.getGwasdatasetid())
 && ( (this.getRsnumber()==castOther.getRsnumber()) || ( this.getRsnumber()!=null && castOther.getRsnumber()!=null && this.getRsnumber().equals(castOther.getRsnumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGwasdatasetid();
         result = 37 * result + ( getRsnumber() == null ? 0 : this.getRsnumber().hashCode() );
         return result;
   }   


}


