package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblkegggenepathways generated by hbm2java
 */
@Entity
@Table(name="TBLKEGGGENEPATHWAYS"
    ,schema="ALLERGEN"
)
public class Tblkegggenepathways  implements java.io.Serializable {


     private TblkegggenepathwaysId id;

    public Tblkegggenepathways() {
    }

    public Tblkegggenepathways(TblkegggenepathwaysId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="geneid", column=@Column(name="GENEID", nullable=false) ), 
        @AttributeOverride(name="pathwayid", column=@Column(name="PATHWAYID", nullable=false, length=5) ) } )
    public TblkegggenepathwaysId getId() {
        return this.id;
    }
    
    public void setId(TblkegggenepathwaysId id) {
        this.id = id;
    }




}


