package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblkeggpathways generated by hbm2java
 */
@Entity
@Table(name="TBLKEGGPATHWAYS"
    ,schema="ALLERGEN"
)
public class Tblkeggpathways  implements java.io.Serializable {


     private String pathwayid;
     private long id;
     private String name;

    public Tblkeggpathways() {
    }

    public Tblkeggpathways(String pathwayid, long id, String name) {
       this.pathwayid = pathwayid;
       this.id = id;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="PATHWAYID", unique=true, nullable=false, length=5)
    public String getPathwayid() {
        return this.pathwayid;
    }
    
    public void setPathwayid(String pathwayid) {
        this.pathwayid = pathwayid;
    }
    
    @Column(name="ID", nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="NAME", nullable=false, length=145)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


