package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblkegggenepathwaysId generated by hbm2java
 */
@Embeddable
public class TblkegggenepathwaysId  implements java.io.Serializable {


     private long geneid;
     private String pathwayid;

    public TblkegggenepathwaysId() {
    }

    public TblkegggenepathwaysId(long geneid, String pathwayid) {
       this.geneid = geneid;
       this.pathwayid = pathwayid;
    }
   

    @Column(name="GENEID", nullable=false)
    public long getGeneid() {
        return this.geneid;
    }
    
    public void setGeneid(long geneid) {
        this.geneid = geneid;
    }

    @Column(name="PATHWAYID", nullable=false, length=5)
    public String getPathwayid() {
        return this.pathwayid;
    }
    
    public void setPathwayid(String pathwayid) {
        this.pathwayid = pathwayid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblkegggenepathwaysId) ) return false;
		 TblkegggenepathwaysId castOther = ( TblkegggenepathwaysId ) other; 
         
		 return (this.getGeneid()==castOther.getGeneid())
 && ( (this.getPathwayid()==castOther.getPathwayid()) || ( this.getPathwayid()!=null && castOther.getPathwayid()!=null && this.getPathwayid().equals(castOther.getPathwayid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getGeneid();
         result = 37 * result + ( getPathwayid() == null ? 0 : this.getPathwayid().hashCode() );
         return result;
   }   


}


