package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblkegggenesId generated by hbm2java
 */
@Embeddable
public class TblkegggenesId  implements java.io.Serializable {


     private long geneid;
     private long ncbiid;

    public TblkegggenesId() {
    }

    public TblkegggenesId(long geneid, long ncbiid) {
       this.geneid = geneid;
       this.ncbiid = ncbiid;
    }
   

    @Column(name="GENEID", nullable=false)
    public long getGeneid() {
        return this.geneid;
    }
    
    public void setGeneid(long geneid) {
        this.geneid = geneid;
    }

    @Column(name="NCBIID", nullable=false)
    public long getNcbiid() {
        return this.ncbiid;
    }
    
    public void setNcbiid(long ncbiid) {
        this.ncbiid = ncbiid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblkegggenesId) ) return false;
		 TblkegggenesId castOther = ( TblkegggenesId ) other; 
         
		 return (this.getGeneid()==castOther.getGeneid())
 && (this.getNcbiid()==castOther.getNcbiid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getGeneid();
         result = 37 * result + (int) this.getNcbiid();
         return result;
   }   


}


