package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tbllituratureassociations generated by hbm2java
 */
@Entity
@Table(name="TBLLITURATUREASSOCIATIONS"
    ,schema="ALLERGEN"
)
public class Tbllituratureassociations  implements java.io.Serializable {


     private TbllituratureassociationsId id;

    public Tbllituratureassociations() {
    }

    public Tbllituratureassociations(TbllituratureassociationsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="snpid", column=@Column(name="SNPID", nullable=false) ), 
        @AttributeOverride(name="refs", column=@Column(name="REFS", nullable=false, length=32700) ) } )
    public TbllituratureassociationsId getId() {
        return this.id;
    }
    
    public void setId(TbllituratureassociationsId id) {
        this.id = id;
    }




}


