package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblmaterialtype generated by hbm2java
 */
@Entity
@Table(name="TBLMATERIALTYPE"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="DESCRIPTION") 
)
public class Tblmaterialtype  implements java.io.Serializable {


     private int materialtypeid;
     private String description;
     @JsonIgnoreProperties("tblmaterialtype")
     private Set<Tblcontainercontents> tblcontainercontentses = new HashSet<Tblcontainercontents>(0);

    public Tblmaterialtype() {
    }

	
    public Tblmaterialtype(int materialtypeid, String description) {
        this.materialtypeid = materialtypeid;
        this.description = description;
    }
    public Tblmaterialtype(int materialtypeid, String description, Set<Tblcontainercontents> tblcontainercontentses) {
       this.materialtypeid = materialtypeid;
       this.description = description;
       this.tblcontainercontentses = tblcontainercontentses;
    }
   
     @Id 
    
    @Column(name="MATERIALTYPEID", unique=true, nullable=false)
    public int getMaterialtypeid() {
        return this.materialtypeid;
    }
    
    public void setMaterialtypeid(int materialtypeid) {
        this.materialtypeid = materialtypeid;
    }
    
    @Column(name="DESCRIPTION", unique=true, nullable=false, length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblmaterialtype")
    public Set<Tblcontainercontents> getTblcontainercontentses() {
        return this.tblcontainercontentses;
    }
    
    public void setTblcontainercontentses(Set<Tblcontainercontents> tblcontainercontentses) {
        this.tblcontainercontentses = tblcontainercontentses;
    }




}


