package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblmztwin generated by hbm2java
 */
@Entity
@Table(name="TBLMZTWIN"
    ,schema="ALLERGEN"
)
public class Tblmztwin  implements java.io.Serializable {


     private TblmztwinId id;
     private Tblcohortlookup tblcohortlookup;

    public Tblmztwin() {
    }

    public Tblmztwin(TblmztwinId id, Tblcohortlookup tblcohortlookup) {
       this.id = id;
       this.tblcohortlookup = tblcohortlookup;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="cohortid", column=@Column(name="COHORTID", nullable=false) ), 
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, length=25) ) } )
    public TblmztwinId getId() {
        return this.id;
    }
    
    public void setId(TblmztwinId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COHORTID", nullable=false, insertable=false, updatable=false)
    public Tblcohortlookup getTblcohortlookup() {
        return this.tblcohortlookup;
    }
    
    public void setTblcohortlookup(Tblcohortlookup tblcohortlookup) {
        this.tblcohortlookup = tblcohortlookup;
    }




}


