package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblmztwinId generated by hbm2java
 */
@Embeddable
public class TblmztwinId  implements java.io.Serializable {


     private long cohortid;
     private String id;

    public TblmztwinId() {
    }

    public TblmztwinId(long cohortid, String id) {
       this.cohortid = cohortid;
       this.id = id;
    }
   

    @Column(name="COHORTID", nullable=false)
    public long getCohortid() {
        return this.cohortid;
    }
    
    public void setCohortid(long cohortid) {
        this.cohortid = cohortid;
    }

    @Column(name="ID", nullable=false, length=25)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblmztwinId) ) return false;
		 TblmztwinId castOther = ( TblmztwinId ) other; 
         
		 return (this.getCohortid()==castOther.getCohortid())
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCohortid();
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         return result;
   }   


}


