package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblphenotypelookup generated by hbm2java
 */
@Entity
@Table(name="TBLPHENOTYPELOOKUP"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class Tblphenotypelookup  implements java.io.Serializable {

     @JsonIgnore
     private int phenotypeid;
     private String name;
     @JsonIgnore
     private short type;
     private String description;
    @JsonIgnore
     private String abreviation;
     @JsonIgnore
     private Set<Tblphenotypes> tblphenotypeses = new HashSet<Tblphenotypes>(0);
     @JsonIgnore
     private Set<Tblphenotyperange> tblphenotyperanges = new HashSet<Tblphenotyperange>(0);
      @JsonIgnore
      private Set<Tblstatus> tblstatuses = new HashSet<Tblstatus>(0);

    public Tblphenotypelookup() {
    }

	
    public Tblphenotypelookup(int phenotypeid, String name, short type) {
        this.phenotypeid = phenotypeid;
        this.name = name;
        this.type = type;
    }
    public Tblphenotypelookup(int phenotypeid, String name, short type, String description, String abreviation, Set<Tblphenotypes> tblphenotypeses, Set<Tblphenotyperange> tblphenotyperanges, Set<Tblstatus> tblstatuses) {
       this.phenotypeid = phenotypeid;
       this.name = name;
       this.type = type;
       this.description = description;
       this.abreviation = abreviation;
       this.tblphenotypeses = tblphenotypeses;
       this.tblphenotyperanges = tblphenotyperanges;
       this.tblstatuses = tblstatuses;
    }
   
     @Id 
    
    @Column(name="PHENOTYPEID", unique=true, nullable=false)
    public int getPhenotypeid() {
        return this.phenotypeid;
    }
    
    public void setPhenotypeid(int phenotypeid) {
        this.phenotypeid = phenotypeid;
    }
    
    @Column(name="NAME", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="TYPE", nullable=false)
    public short getType() {
        return this.type;
    }
    
    public void setType(short type) {
        this.type = type;
    }
    
    @Column(name="DESCRIPTION", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="ABREVIATION", length=10)
    public String getAbreviation() {
        return this.abreviation;
    }
    
    public void setAbreviation(String abreviation) {
        this.abreviation = abreviation;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblphenotypelookup")
    public Set<Tblphenotypes> getTblphenotypeses() {
        return this.tblphenotypeses;
    }
    
    public void setTblphenotypeses(Set<Tblphenotypes> tblphenotypeses) {
        this.tblphenotypeses = tblphenotypeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblphenotypelookup")
    public Set<Tblphenotyperange> getTblphenotyperanges() {
        return this.tblphenotyperanges;
    }
    
    public void setTblphenotyperanges(Set<Tblphenotyperange> tblphenotyperanges) {
        this.tblphenotyperanges = tblphenotyperanges;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblphenotypelookup")
    public Set<Tblstatus> getTblstatuses() {
        return this.tblstatuses;
    }
    
    public void setTblstatuses(Set<Tblstatus> tblstatuses) {
        this.tblstatuses = tblstatuses;
    }




}


