package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblphenotyperange generated by hbm2java
 */
@Entity
@Table(name="TBLPHENOTYPERANGE"
    ,schema="ALLERGEN"
)
public class Tblphenotyperange  implements java.io.Serializable {


     private TblphenotyperangeId id;
     private Tblphenotypelookup tblphenotypelookup;
     private Tblcohortlookup tblcohortlookup;
     private double minimum;
     private double maximum;

    public Tblphenotyperange() {
    }

    public Tblphenotyperange(TblphenotyperangeId id, Tblphenotypelookup tblphenotypelookup, Tblcohortlookup tblcohortlookup, double minimum, double maximum) {
       this.id = id;
       this.tblphenotypelookup = tblphenotypelookup;
       this.tblcohortlookup = tblcohortlookup;
       this.minimum = minimum;
       this.maximum = maximum;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="phenotypeid", column=@Column(name="PHENOTYPEID", nullable=false) ), 
        @AttributeOverride(name="cohortid", column=@Column(name="COHORTID", nullable=false) ) } )
    public TblphenotyperangeId getId() {
        return this.id;
    }
    
    public void setId(TblphenotyperangeId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PHENOTYPEID", nullable=false, insertable=false, updatable=false)
    public Tblphenotypelookup getTblphenotypelookup() {
        return this.tblphenotypelookup;
    }
    
    public void setTblphenotypelookup(Tblphenotypelookup tblphenotypelookup) {
        this.tblphenotypelookup = tblphenotypelookup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COHORTID", nullable=false, insertable=false, updatable=false)
    public Tblcohortlookup getTblcohortlookup() {
        return this.tblcohortlookup;
    }
    
    public void setTblcohortlookup(Tblcohortlookup tblcohortlookup) {
        this.tblcohortlookup = tblcohortlookup;
    }
    
    @Column(name="MINIMUM", nullable=false, precision=53, scale=0)
    public double getMinimum() {
        return this.minimum;
    }
    
    public void setMinimum(double minimum) {
        this.minimum = minimum;
    }
    
    @Column(name="MAXIMUM", nullable=false, precision=53, scale=0)
    public double getMaximum() {
        return this.maximum;
    }
    
    public void setMaximum(double maximum) {
        this.maximum = maximum;
    }




}


