package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblphenotypes generated by hbm2java
 */
@Entity
@Table(name="TBLPHENOTYPES"
    ,schema="ALLERGEN"
)
public class Tblphenotypes  implements java.io.Serializable {


     private TblphenotypesId id;
     
     private Tblphenotypelookup tblphenotypelookup;
     @JsonIgnoreProperties("tblphenotypeses")
     private Tblsubject tblsubject;
     private String value;
     private String abreviation;

    public Tblphenotypes() {
    }

	
    public Tblphenotypes(TblphenotypesId id, Tblphenotypelookup tblphenotypelookup, Tblsubject tblsubject, String value) {
        this.id = id;
        this.tblphenotypelookup = tblphenotypelookup;
        this.tblsubject = tblsubject;
        this.value = value;
    }
    public Tblphenotypes(TblphenotypesId id, Tblphenotypelookup tblphenotypelookup, Tblsubject tblsubject, String value, String abreviation) {
       this.id = id;
       this.tblphenotypelookup = tblphenotypelookup;
       this.tblsubject = tblsubject;
       this.value = value;
       this.abreviation = abreviation;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ), 
        @AttributeOverride(name="phenotypeid", column=@Column(name="PHENOTYPEID", nullable=false) ) } )
    public TblphenotypesId getId() {
        return this.id;
    }
    
    public void setId(TblphenotypesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PHENOTYPEID", nullable=false, insertable=false, updatable=false)
    public Tblphenotypelookup getTblphenotypelookup() {
        return this.tblphenotypelookup;
    }
    
    public void setTblphenotypelookup(Tblphenotypelookup tblphenotypelookup) {
        this.tblphenotypelookup = tblphenotypelookup;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SUBJECTID", nullable=false, insertable=false, updatable=false)
    public Tblsubject getTblsubject() {
        return this.tblsubject;
    }
    
    public void setTblsubject(Tblsubject tblsubject) {
        this.tblsubject = tblsubject;
    }
    
    @Column(name="VALUE", nullable=false, length=25)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="ABREVIATION", length=10)
    public String getAbreviation() {
        return this.abreviation;
    }
    
    public void setAbreviation(String abreviation) {
        this.abreviation = abreviation;
    }




}


