package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblresults generated by hbm2java
 */
@Entity
@Table(name="TBLRESULTS"
    ,schema="ALLERGEN"
)
public class Tblresults  implements java.io.Serializable {


     private TblresultsId id;

    public Tblresults() {
    }

    public Tblresults(TblresultsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="resultid", column=@Column(name="RESULTID", nullable=false) ), 
        @AttributeOverride(name="username", column=@Column(name="USERNAME", length=75) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", nullable=false, length=50) ), 
        @AttributeOverride(name="location", column=@Column(name="LOCATION", length=256) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", length=200) ), 
        @AttributeOverride(name="time", column=@Column(name="TIME", length=26) ) } )
    public TblresultsId getId() {
        return this.id;
    }
    
    public void setId(TblresultsId id) {
        this.id = id;
    }




}


