package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tblreferences generated by hbm2java
 */
@Entity
@Table(name="TBLREFERENCES"
    ,schema="ALLERGEN"
)
public class Tblreferences  implements java.io.Serializable {


     private long referenceid;
     private String reference;
     private Set<Tblsnp> tblsnps = new HashSet<Tblsnp>(0);

    public Tblreferences() {
    }

	
    public Tblreferences(long referenceid, String reference) {
        this.referenceid = referenceid;
        this.reference = reference;
    }
    public Tblreferences(long referenceid, String reference, Set<Tblsnp> tblsnps) {
       this.referenceid = referenceid;
       this.reference = reference;
       this.tblsnps = tblsnps;
    }
   
     @Id 
    
    @Column(name="REFERENCEID", unique=true, nullable=false)
    public long getReferenceid() {
        return this.referenceid;
    }
    
    public void setReferenceid(long referenceid) {
        this.referenceid = referenceid;
    }
    
    @Column(name="REFERENCE", nullable=false, length=500)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblreferenceses")
    public Set<Tblsnp> getTblsnps() {
        return this.tblsnps;
    }
    
    public void setTblsnps(Set<Tblsnp> tblsnps) {
        this.tblsnps = tblsnps;
    }




}


