package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblsampletypes generated by hbm2java
 */
@Entity
@Table(name="TBLSAMPLETYPES"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="DESCRIPTION") 
)
public class Tblsampletypes  implements java.io.Serializable {


     private int sampletypeid;
     private String description;
     private int sortorder;
     @JsonIgnoreProperties("tblsampletypes")
     private Set<Tblsamples> tblsampleses = new HashSet<Tblsamples>(0);

    public Tblsampletypes() {
    }

	
    public Tblsampletypes(int sampletypeid, String description, int sortorder) {
        this.sampletypeid = sampletypeid;
        this.description = description;
        this.sortorder = sortorder;
    }
    public Tblsampletypes(int sampletypeid, String description, int sortorder, Set<Tblsamples> tblsampleses) {
       this.sampletypeid = sampletypeid;
       this.description = description;
       this.sortorder = sortorder;
       this.tblsampleses = tblsampleses;
    }
   
     @Id 
    
    @Column(name="SAMPLETYPEID", unique=true, nullable=false)
    public int getSampletypeid() {
        return this.sampletypeid;
    }
    
    public void setSampletypeid(int sampletypeid) {
        this.sampletypeid = sampletypeid;
    }
    
    @Column(name="DESCRIPTION", unique=true, nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="SORTORDER", nullable=false)
    public int getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(int sortorder) {
        this.sortorder = sortorder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsampletypes")
    public Set<Tblsamples> getTblsampleses() {
        return this.tblsampleses;
    }
    
    public void setTblsampleses(Set<Tblsamples> tblsampleses) {
        this.tblsampleses = tblsampleses;
    }




}


