package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblsampleqcstatus generated by hbm2java
 */
@Entity
@Table(name="TBLSAMPLEQCSTATUS"
    ,schema="ALLERGEN"
)
public class Tblsampleqcstatus  implements java.io.Serializable {


     private int sampleqcstatusid;
     private Tblgenotypingruns tblgenotypingruns;
     private Tblsamples tblsamples;
     private int status;

    public Tblsampleqcstatus() {
    }

    public Tblsampleqcstatus(int sampleqcstatusid, Tblgenotypingruns tblgenotypingruns, Tblsamples tblsamples, int status) {
       this.sampleqcstatusid = sampleqcstatusid;
       this.tblgenotypingruns = tblgenotypingruns;
       this.tblsamples = tblsamples;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="SAMPLEQCSTATUSID", unique=true, nullable=false)
    public int getSampleqcstatusid() {
        return this.sampleqcstatusid;
    }
    
    public void setSampleqcstatusid(int sampleqcstatusid) {
        this.sampleqcstatusid = sampleqcstatusid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENOTYPINGRUNID", nullable=false)
    public Tblgenotypingruns getTblgenotypingruns() {
        return this.tblgenotypingruns;
    }
    
    public void setTblgenotypingruns(Tblgenotypingruns tblgenotypingruns) {
        this.tblgenotypingruns = tblgenotypingruns;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SAMPLEID", nullable=false)
    public Tblsamples getTblsamples() {
        return this.tblsamples;
    }
    
    public void setTblsamples(Tblsamples tblsamples) {
        this.tblsamples = tblsamples;
    }
    
    @Column(name="STATUS", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


