package ca.ubc.icapture.genapha.slims.model;
// Generated May 31, 2017 11:51:43 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tblsubject generated by hbm2java
 */
@Entity
@Table(name="TBLSUBJECT"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames={"COHORTID", "ID"}) 
)
public class Tblsubject  implements java.io.Serializable {


     private int subjectid;
     @JsonIgnore
     private Tblsimsusers tblsimsusersByModifiedBy;
     @JsonIgnore
     private Tblsimsusers tblsimsusersByCreatedBy;
     @JsonManagedReference
     private Tblethnicitylookup tblethnicitylookupByGenEthid;
     @JsonManagedReference
     private Tblethnicitylookup tblethnicitylookupBySelfRepEthid;
     @JsonManagedReference
     private Tblethnicitylookup tblethnicitylookupByEthnicityid;
    @JsonManagedReference
     private Tblethnicitylookup tblethnicitylookupBySelfRepAncEthid;
     @JsonManagedReference
     private Tblcohortlookup tblcohortlookup;
     private String id;
     private String familyid;
     private short gender;
     private short code;
     private short hasconsent;
     private String motherid;
     private String fatherid;
     private short passedqc;
     private int numsamplescollected;
     private Date created;
     private Date modified;
     private String comment;
     
    @JsonIgnore
     private Set<Tblcleangenotypes> tblcleangenotypeses = new HashSet<Tblcleangenotypes>(0);
    @JsonIgnoreProperties("tblsubject")
     private Set<Tblphenotypes> tblphenotypeses = new HashSet<Tblphenotypes>(0);
     @JsonIgnore
     private Set<Tblsubjectalias> tblsubjectaliases = new HashSet<Tblsubjectalias>(0);
     @JsonIgnore
     private Set<Tblsamples> tblsampleses = new HashSet<Tblsamples>(0);
     @JsonIgnore
     private Set<Tblshoppinglistsubjects> tblshoppinglistsubjectses = new HashSet<Tblshoppinglistsubjects>(0);
     @JsonIgnore
     private Set<Tblvariables> tblvariableses = new HashSet<Tblvariables>(0);

 
    public Tblsubject() {
    }

  
    public Tblsubject(int subjectid, Tblsimsusers tblsimsusersByCreatedBy, Tblethnicitylookup tblethnicitylookupByEthnicityid, Tblcohortlookup tblcohortlookup, String id, String familyid, short gender, short code, short hasconsent, String motherid, String fatherid, short passedqc, int numsamplescollected, Date created) {
        this.subjectid = subjectid;
        this.tblsimsusersByCreatedBy = tblsimsusersByCreatedBy;
        this.tblethnicitylookupByEthnicityid = tblethnicitylookupByEthnicityid;
        this.tblcohortlookup = tblcohortlookup;
        this.id = id;
        this.familyid = familyid;
        this.gender = gender;
        this.code = code;
        this.hasconsent = hasconsent;
        this.motherid = motherid;
        this.fatherid = fatherid;
        this.passedqc = passedqc;
        this.numsamplescollected = numsamplescollected;
        this.created = created;
    }

    public Tblsubject(int subjectid, Tblsimsusers tblsimsusersByModifiedBy, Tblsimsusers tblsimsusersByCreatedBy, Tblethnicitylookup tblethnicitylookupByGenEthid, Tblethnicitylookup tblethnicitylookupBySelfRepEthid, Tblethnicitylookup tblethnicitylookupByEthnicityid, Tblethnicitylookup tblethnicitylookupBySelfRepAncEthid, Tblcohortlookup tblcohortlookup, String id, String familyid, short gender, short code, short hasconsent, String motherid, String fatherid, short passedqc, int numsamplescollected, Date created, Date modified, String comment, Set<Tblcleangenotypes> tblcleangenotypeses, Set<Tblphenotypes> tblphenotypeses, Set<Tblsubjectalias> tblsubjectaliases, Set<Tblsamples> tblsampleses, Set<Tblshoppinglistsubjects> tblshoppinglistsubjectses, Set<Tblvariables> tblvariableses) {
       this.subjectid = subjectid;
       this.tblsimsusersByModifiedBy = tblsimsusersByModifiedBy;
       this.tblsimsusersByCreatedBy = tblsimsusersByCreatedBy;
       this.tblethnicitylookupByGenEthid = tblethnicitylookupByGenEthid;
       this.tblethnicitylookupBySelfRepEthid = tblethnicitylookupBySelfRepEthid;
       this.tblethnicitylookupByEthnicityid = tblethnicitylookupByEthnicityid;
       this.tblethnicitylookupBySelfRepAncEthid = tblethnicitylookupBySelfRepAncEthid;
       this.tblcohortlookup = tblcohortlookup;
       this.id = id;
       this.familyid = familyid;
       this.gender = gender;
       this.code = code;
       this.hasconsent = hasconsent;
       this.motherid = motherid;
       this.fatherid = fatherid;
       this.passedqc = passedqc;
       this.numsamplescollected = numsamplescollected;
       this.created = created;
       this.modified = modified;
       this.comment = comment;
       this.tblcleangenotypeses = tblcleangenotypeses;
       this.tblphenotypeses = tblphenotypeses;
       this.tblsubjectaliases = tblsubjectaliases;
       this.tblsampleses = tblsampleses;
       this.tblshoppinglistsubjectses = tblshoppinglistsubjectses;
       this.tblvariableses = tblvariableses;
    }
   
     @Id 
    @Column(name="SUBJECTID", unique=true, nullable=false)
    public int getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(int subjectid) {
        this.subjectid = subjectid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MODIFIED_BY")
    public Tblsimsusers getTblsimsusersByModifiedBy() {
        return this.tblsimsusersByModifiedBy;
    }
    
    public void setTblsimsusersByModifiedBy(Tblsimsusers tblsimsusersByModifiedBy) {
        this.tblsimsusersByModifiedBy = tblsimsusersByModifiedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATED_BY", nullable=false)
    public Tblsimsusers getTblsimsusersByCreatedBy() {
        return this.tblsimsusersByCreatedBy;
    }
    
    public void setTblsimsusersByCreatedBy(Tblsimsusers tblsimsusersByCreatedBy) {
        this.tblsimsusersByCreatedBy = tblsimsusersByCreatedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GEN_ETHID")
    public Tblethnicitylookup getTblethnicitylookupByGenEthid() {
        return this.tblethnicitylookupByGenEthid;
    }
    
    public void setTblethnicitylookupByGenEthid(Tblethnicitylookup tblethnicitylookupByGenEthid) {
        this.tblethnicitylookupByGenEthid = tblethnicitylookupByGenEthid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SELF_REP_ETHID")
    public Tblethnicitylookup getTblethnicitylookupBySelfRepEthid() {
        return this.tblethnicitylookupBySelfRepEthid;
    }
    
    public void setTblethnicitylookupBySelfRepEthid(Tblethnicitylookup tblethnicitylookupBySelfRepEthid) {
        this.tblethnicitylookupBySelfRepEthid = tblethnicitylookupBySelfRepEthid;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ETHNICITYID", nullable=false)
    public Tblethnicitylookup getTblethnicitylookupByEthnicityid() {
        return this.tblethnicitylookupByEthnicityid;
    }
    
    public void setTblethnicitylookupByEthnicityid(Tblethnicitylookup tblethnicitylookupByEthnicityid) {
        this.tblethnicitylookupByEthnicityid = tblethnicitylookupByEthnicityid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SELF_REP_ANC_ETHID")
    public Tblethnicitylookup getTblethnicitylookupBySelfRepAncEthid() {
        return this.tblethnicitylookupBySelfRepAncEthid;
    }
    
    public void setTblethnicitylookupBySelfRepAncEthid(Tblethnicitylookup tblethnicitylookupBySelfRepAncEthid) {
        this.tblethnicitylookupBySelfRepAncEthid = tblethnicitylookupBySelfRepAncEthid;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COHORTID", nullable=false)
    public Tblcohortlookup getTblcohortlookup() {
        return this.tblcohortlookup;
    }
    
    public void setTblcohortlookup(Tblcohortlookup tblcohortlookup) {
        this.tblcohortlookup = tblcohortlookup;
    }
    
    @Column(name="ID", nullable=false, length=25)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="FAMILYID", nullable=false, length=25)
    public String getFamilyid() {
        return this.familyid;
    }
    
    public void setFamilyid(String familyid) {
        this.familyid = familyid;
    }
    
    @Column(name="GENDER", nullable=false)
    public short getGender() {
        return this.gender;
    }
    
    public void setGender(short gender) {
        this.gender = gender;
    }
    
    @Column(name="CODE", nullable=false)
    public short getCode() {
        return this.code;
    }
    
    public void setCode(short code) {
        this.code = code;
    }
    
    @Column(name="HASCONSENT", nullable=false)
    public short getHasconsent() {
        return this.hasconsent;
    }
    
    public void setHasconsent(short hasconsent) {
        this.hasconsent = hasconsent;
    }
    
    @Column(name="MOTHERID", nullable=false, length=25)
    public String getMotherid() {
        return this.motherid;
    }
    
    public void setMotherid(String motherid) {
        this.motherid = motherid;
    }
    
    @Column(name="FATHERID", nullable=false, length=25)
    public String getFatherid() {
        return this.fatherid;
    }
    
    public void setFatherid(String fatherid) {
        this.fatherid = fatherid;
    }
    
    @Column(name="PASSEDQC", nullable=false)
    public short getPassedqc() {
        return this.passedqc;
    }
    
    public void setPassedqc(short passedqc) {
        this.passedqc = passedqc;
    }
    
    @Column(name="NUMSAMPLESCOLLECTED", nullable=false)
    public int getNumsamplescollected() {
        return this.numsamplescollected;
    }
    
    public void setNumsamplescollected(int numsamplescollected) {
        this.numsamplescollected = numsamplescollected;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=26)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="COMMENT", length=100)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsubject")
    public Set<Tblcleangenotypes> getTblcleangenotypeses() {
        return this.tblcleangenotypeses;
    }
    
    public void setTblcleangenotypeses(Set<Tblcleangenotypes> tblcleangenotypeses) {
        this.tblcleangenotypeses = tblcleangenotypeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsubject")
    public Set<Tblphenotypes> getTblphenotypeses() {
        return this.tblphenotypeses;
    }
    
    public void setTblphenotypeses(Set<Tblphenotypes> tblphenotypeses) {
        this.tblphenotypeses = tblphenotypeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsubject")
    public Set<Tblsubjectalias> getTblsubjectaliases() {
        return this.tblsubjectaliases;
    }
    
    public void setTblsubjectaliases(Set<Tblsubjectalias> tblsubjectaliases) {
        this.tblsubjectaliases = tblsubjectaliases;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsubject")
    public Set<Tblsamples> getTblsampleses() {
        return this.tblsampleses;
    }
    
    public void setTblsampleses(Set<Tblsamples> tblsampleses) {
        this.tblsampleses = tblsampleses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsubject")
    public Set<Tblshoppinglistsubjects> getTblshoppinglistsubjectses() {
        return this.tblshoppinglistsubjectses;
    }
    
    public void setTblshoppinglistsubjectses(Set<Tblshoppinglistsubjects> tblshoppinglistsubjectses) {
        this.tblshoppinglistsubjectses = tblshoppinglistsubjectses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsubject")
    public Set<Tblvariables> getTblvariableses() {
        return this.tblvariableses;
    }
    
    public void setTblvariableses(Set<Tblvariables> tblvariableses) {
        this.tblvariableses = tblvariableses;
    }

  @Override
  public boolean equals(Object d) {
    return (getSubjectid() == ((Tblsubject)d).getSubjectid());
}

}


