package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblsnpalternatenamesId generated by hbm2java
 */
@Embeddable
public class TblsnpalternatenamesId  implements java.io.Serializable {


     private int snpid;
     private String name;

    public TblsnpalternatenamesId() {
    }

    public TblsnpalternatenamesId(int snpid, String name) {
       this.snpid = snpid;
       this.name = name;
    }
   

    @Column(name="SNPID", nullable=false)
    public int getSnpid() {
        return this.snpid;
    }
    
    public void setSnpid(int snpid) {
        this.snpid = snpid;
    }

    @Column(name="NAME", unique=true, nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblsnpalternatenamesId) ) return false;
		 TblsnpalternatenamesId castOther = ( TblsnpalternatenamesId ) other; 
         
		 return (this.getSnpid()==castOther.getSnpid())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSnpid();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   


}


