package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblsampleslogId generated by hbm2java
 */
@Embeddable
public class TblsampleslogId  implements java.io.Serializable {


     private long sampleid;
     private long subjectid;
     private String name;
     private short valid;
     private Long parent;
     private Integer sampletypeid;
     private Integer sampleprocessid;
     private Long parentid;
     private Date collectiondate;
     private String comments;
     private Integer sampletypeyear1id;
     private Date extractiondateyear1;
     private Date collectiondateyear1;
     private Date extractiondate;
     private int createdBy;
     private Date created;
     private Integer modifiedBy;
     private Date modified;
     private Date updated;

    public TblsampleslogId() {
    }

	
    public TblsampleslogId(long sampleid, long subjectid, String name, short valid, Date collectiondate, int createdBy, Date created, Date updated) {
        this.sampleid = sampleid;
        this.subjectid = subjectid;
        this.name = name;
        this.valid = valid;
        this.collectiondate = collectiondate;
        this.createdBy = createdBy;
        this.created = created;
        this.updated = updated;
    }
    public TblsampleslogId(long sampleid, long subjectid, String name, short valid, Long parent, Integer sampletypeid, Integer sampleprocessid, Long parentid, Date collectiondate, String comments, Integer sampletypeyear1id, Date extractiondateyear1, Date collectiondateyear1, Date extractiondate, int createdBy, Date created, Integer modifiedBy, Date modified, Date updated) {
       this.sampleid = sampleid;
       this.subjectid = subjectid;
       this.name = name;
       this.valid = valid;
       this.parent = parent;
       this.sampletypeid = sampletypeid;
       this.sampleprocessid = sampleprocessid;
       this.parentid = parentid;
       this.collectiondate = collectiondate;
       this.comments = comments;
       this.sampletypeyear1id = sampletypeyear1id;
       this.extractiondateyear1 = extractiondateyear1;
       this.collectiondateyear1 = collectiondateyear1;
       this.extractiondate = extractiondate;
       this.createdBy = createdBy;
       this.created = created;
       this.modifiedBy = modifiedBy;
       this.modified = modified;
       this.updated = updated;
    }
   

    @Column(name="SAMPLEID", nullable=false)
    public long getSampleid() {
        return this.sampleid;
    }
    
    public void setSampleid(long sampleid) {
        this.sampleid = sampleid;
    }

    @Column(name="SUBJECTID", nullable=false)
    public long getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(long subjectid) {
        this.subjectid = subjectid;
    }

    @Column(name="NAME", nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="VALID", nullable=false)
    public short getValid() {
        return this.valid;
    }
    
    public void setValid(short valid) {
        this.valid = valid;
    }

    @Column(name="PARENT")
    public Long getParent() {
        return this.parent;
    }
    
    public void setParent(Long parent) {
        this.parent = parent;
    }

    @Column(name="SAMPLETYPEID")
    public Integer getSampletypeid() {
        return this.sampletypeid;
    }
    
    public void setSampletypeid(Integer sampletypeid) {
        this.sampletypeid = sampletypeid;
    }

    @Column(name="SAMPLEPROCESSID")
    public Integer getSampleprocessid() {
        return this.sampleprocessid;
    }
    
    public void setSampleprocessid(Integer sampleprocessid) {
        this.sampleprocessid = sampleprocessid;
    }

    @Column(name="PARENTID")
    public Long getParentid() {
        return this.parentid;
    }
    
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    @Column(name="COLLECTIONDATE", nullable=false, length=10)
    public Date getCollectiondate() {
        return this.collectiondate;
    }
    
    public void setCollectiondate(Date collectiondate) {
        this.collectiondate = collectiondate;
    }

    @Column(name="COMMENTS", length=1000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name="SAMPLETYPEYEAR1ID")
    public Integer getSampletypeyear1id() {
        return this.sampletypeyear1id;
    }
    
    public void setSampletypeyear1id(Integer sampletypeyear1id) {
        this.sampletypeyear1id = sampletypeyear1id;
    }

    @Column(name="EXTRACTIONDATEYEAR1", length=10)
    public Date getExtractiondateyear1() {
        return this.extractiondateyear1;
    }
    
    public void setExtractiondateyear1(Date extractiondateyear1) {
        this.extractiondateyear1 = extractiondateyear1;
    }

    @Column(name="COLLECTIONDATEYEAR1", length=10)
    public Date getCollectiondateyear1() {
        return this.collectiondateyear1;
    }
    
    public void setCollectiondateyear1(Date collectiondateyear1) {
        this.collectiondateyear1 = collectiondateyear1;
    }

    @Column(name="EXTRACTIONDATE", length=10)
    public Date getExtractiondate() {
        return this.extractiondate;
    }
    
    public void setExtractiondate(Date extractiondate) {
        this.extractiondate = extractiondate;
    }

    @Column(name="CREATED_BY", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name="CREATED", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name="MODIFIED_BY")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Column(name="MODIFIED", length=26)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    @Column(name="UPDATED", nullable=false, length=26)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblsampleslogId) ) return false;
		 TblsampleslogId castOther = ( TblsampleslogId ) other; 
         
		 return (this.getSampleid()==castOther.getSampleid())
 && (this.getSubjectid()==castOther.getSubjectid())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && (this.getValid()==castOther.getValid())
 && ( (this.getParent()==castOther.getParent()) || ( this.getParent()!=null && castOther.getParent()!=null && this.getParent().equals(castOther.getParent()) ) )
 && ( (this.getSampletypeid()==castOther.getSampletypeid()) || ( this.getSampletypeid()!=null && castOther.getSampletypeid()!=null && this.getSampletypeid().equals(castOther.getSampletypeid()) ) )
 && ( (this.getSampleprocessid()==castOther.getSampleprocessid()) || ( this.getSampleprocessid()!=null && castOther.getSampleprocessid()!=null && this.getSampleprocessid().equals(castOther.getSampleprocessid()) ) )
 && ( (this.getParentid()==castOther.getParentid()) || ( this.getParentid()!=null && castOther.getParentid()!=null && this.getParentid().equals(castOther.getParentid()) ) )
 && ( (this.getCollectiondate()==castOther.getCollectiondate()) || ( this.getCollectiondate()!=null && castOther.getCollectiondate()!=null && this.getCollectiondate().equals(castOther.getCollectiondate()) ) )
 && ( (this.getComments()==castOther.getComments()) || ( this.getComments()!=null && castOther.getComments()!=null && this.getComments().equals(castOther.getComments()) ) )
 && ( (this.getSampletypeyear1id()==castOther.getSampletypeyear1id()) || ( this.getSampletypeyear1id()!=null && castOther.getSampletypeyear1id()!=null && this.getSampletypeyear1id().equals(castOther.getSampletypeyear1id()) ) )
 && ( (this.getExtractiondateyear1()==castOther.getExtractiondateyear1()) || ( this.getExtractiondateyear1()!=null && castOther.getExtractiondateyear1()!=null && this.getExtractiondateyear1().equals(castOther.getExtractiondateyear1()) ) )
 && ( (this.getCollectiondateyear1()==castOther.getCollectiondateyear1()) || ( this.getCollectiondateyear1()!=null && castOther.getCollectiondateyear1()!=null && this.getCollectiondateyear1().equals(castOther.getCollectiondateyear1()) ) )
 && ( (this.getExtractiondate()==castOther.getExtractiondate()) || ( this.getExtractiondate()!=null && castOther.getExtractiondate()!=null && this.getExtractiondate().equals(castOther.getExtractiondate()) ) )
 && (this.getCreatedBy()==castOther.getCreatedBy())
 && ( (this.getCreated()==castOther.getCreated()) || ( this.getCreated()!=null && castOther.getCreated()!=null && this.getCreated().equals(castOther.getCreated()) ) )
 && ( (this.getModifiedBy()==castOther.getModifiedBy()) || ( this.getModifiedBy()!=null && castOther.getModifiedBy()!=null && this.getModifiedBy().equals(castOther.getModifiedBy()) ) )
 && ( (this.getModified()==castOther.getModified()) || ( this.getModified()!=null && castOther.getModified()!=null && this.getModified().equals(castOther.getModified()) ) )
 && ( (this.getUpdated()==castOther.getUpdated()) || ( this.getUpdated()!=null && castOther.getUpdated()!=null && this.getUpdated().equals(castOther.getUpdated()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getSampleid();
         result = 37 * result + (int) this.getSubjectid();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + this.getValid();
         result = 37 * result + ( getParent() == null ? 0 : this.getParent().hashCode() );
         result = 37 * result + ( getSampletypeid() == null ? 0 : this.getSampletypeid().hashCode() );
         result = 37 * result + ( getSampleprocessid() == null ? 0 : this.getSampleprocessid().hashCode() );
         result = 37 * result + ( getParentid() == null ? 0 : this.getParentid().hashCode() );
         result = 37 * result + ( getCollectiondate() == null ? 0 : this.getCollectiondate().hashCode() );
         result = 37 * result + ( getComments() == null ? 0 : this.getComments().hashCode() );
         result = 37 * result + ( getSampletypeyear1id() == null ? 0 : this.getSampletypeyear1id().hashCode() );
         result = 37 * result + ( getExtractiondateyear1() == null ? 0 : this.getExtractiondateyear1().hashCode() );
         result = 37 * result + ( getCollectiondateyear1() == null ? 0 : this.getCollectiondateyear1().hashCode() );
         result = 37 * result + ( getExtractiondate() == null ? 0 : this.getExtractiondate().hashCode() );
         result = 37 * result + this.getCreatedBy();
         result = 37 * result + ( getCreated() == null ? 0 : this.getCreated().hashCode() );
         result = 37 * result + ( getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode() );
         result = 37 * result + ( getModified() == null ? 0 : this.getModified().hashCode() );
         result = 37 * result + ( getUpdated() == null ? 0 : this.getUpdated().hashCode() );
         return result;
   }   


}


