package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tblsimsusers generated by hbm2java
 */
@Entity
@Table(name="TBLSIMSUSERS"
    ,schema="ALLERGEN"
    , uniqueConstraints = {@UniqueConstraint(columnNames="INITIALS"), @UniqueConstraint(columnNames="LOGIN")} 
)
public class Tblsimsusers  implements java.io.Serializable {


     private int sysid;
     private Tblusertypes tblusertypes;
     private String fullname;
     private String login;
     private String passw;
     private String rights;
     private Date created;
     private Date modified;
     private String commentary;
     private Integer partner;
     private String initials;
     private Set<Tblshoppinglists> tblshoppinglistsesForModifiedBy = new HashSet<Tblshoppinglists>(0);
     private Set<Tblcontainers> tblcontainersesForModifiedBy = new HashSet<Tblcontainers>(0);
     private Set<Tblcontainers> tblcontainersesForCreatedBy = new HashSet<Tblcontainers>(0);
     private Set<TblcontainercontentsMetaData> tblcontainercontentsMetaDatas = new HashSet<TblcontainercontentsMetaData>(0);
     private Set<Tblcontrolwells> tblcontrolwellsesForModifiedBy = new HashSet<Tblcontrolwells>(0);
     private Set<Tblshoppinglists> tblshoppinglistsesForCreatedBy = new HashSet<Tblshoppinglists>(0);
     private Set<Tblsubject> tblsubjectsForCreatedBy = new HashSet<Tblsubject>(0);
     private Set<Tblsamples> tblsamplesesForModifiedBy = new HashSet<Tblsamples>(0);
     private Set<Tblsamples> tblsamplesesForCreatedBy = new HashSet<Tblsamples>(0);
     private Set<Tblsubject> tblsubjectsForModifiedBy = new HashSet<Tblsubject>(0);
     private Set<Tblcontrolwells> tblcontrolwellsesForCreatedBy = new HashSet<Tblcontrolwells>(0);

    public Tblsimsusers() {
    }

	
    public Tblsimsusers(int sysid, Tblusertypes tblusertypes, String login, String passw, String rights, Date created, String initials) {
        this.sysid = sysid;
        this.tblusertypes = tblusertypes;
        this.login = login;
        this.passw = passw;
        this.rights = rights;
        this.created = created;
        this.initials = initials;
    }
    public Tblsimsusers(int sysid, Tblusertypes tblusertypes, String fullname, String login, String passw, String rights, Date created, Date modified, String commentary, Integer partner, String initials, Set<Tblshoppinglists> tblshoppinglistsesForModifiedBy, Set<Tblcontainers> tblcontainersesForModifiedBy, Set<Tblcontainers> tblcontainersesForCreatedBy, Set<TblcontainercontentsMetaData> tblcontainercontentsMetaDatas, Set<Tblcontrolwells> tblcontrolwellsesForModifiedBy, Set<Tblshoppinglists> tblshoppinglistsesForCreatedBy, Set<Tblsubject> tblsubjectsForCreatedBy, Set<Tblsamples> tblsamplesesForModifiedBy, Set<Tblsamples> tblsamplesesForCreatedBy, Set<Tblsubject> tblsubjectsForModifiedBy, Set<Tblcontrolwells> tblcontrolwellsesForCreatedBy) {
       this.sysid = sysid;
       this.tblusertypes = tblusertypes;
       this.fullname = fullname;
       this.login = login;
       this.passw = passw;
       this.rights = rights;
       this.created = created;
       this.modified = modified;
       this.commentary = commentary;
       this.partner = partner;
       this.initials = initials;
       this.tblshoppinglistsesForModifiedBy = tblshoppinglistsesForModifiedBy;
       this.tblcontainersesForModifiedBy = tblcontainersesForModifiedBy;
       this.tblcontainersesForCreatedBy = tblcontainersesForCreatedBy;
       this.tblcontainercontentsMetaDatas = tblcontainercontentsMetaDatas;
       this.tblcontrolwellsesForModifiedBy = tblcontrolwellsesForModifiedBy;
       this.tblshoppinglistsesForCreatedBy = tblshoppinglistsesForCreatedBy;
       this.tblsubjectsForCreatedBy = tblsubjectsForCreatedBy;
       this.tblsamplesesForModifiedBy = tblsamplesesForModifiedBy;
       this.tblsamplesesForCreatedBy = tblsamplesesForCreatedBy;
       this.tblsubjectsForModifiedBy = tblsubjectsForModifiedBy;
       this.tblcontrolwellsesForCreatedBy = tblcontrolwellsesForCreatedBy;
    }
   
     @Id 
    
    @Column(name="SYSID", unique=true, nullable=false)
    public int getSysid() {
        return this.sysid;
    }
    
    public void setSysid(int sysid) {
        this.sysid = sysid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERTYPEID", nullable=false)
    public Tblusertypes getTblusertypes() {
        return this.tblusertypes;
    }
    
    public void setTblusertypes(Tblusertypes tblusertypes) {
        this.tblusertypes = tblusertypes;
    }
    
    @Column(name="FULLNAME", length=200)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    
    @Column(name="LOGIN", unique=true, nullable=false, length=200)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="PASSW", nullable=false)
    public String getPassw() {
        return this.passw;
    }
    
    public void setPassw(String passw) {
        this.passw = passw;
    }
    
    @Column(name="RIGHTS", nullable=false, length=200)
    public String getRights() {
        return this.rights;
    }
    
    public void setRights(String rights) {
        this.rights = rights;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=26)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="COMMENTARY")
    public String getCommentary() {
        return this.commentary;
    }
    
    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }
    
    @Column(name="PARTNER")
    public Integer getPartner() {
        return this.partner;
    }
    
    public void setPartner(Integer partner) {
        this.partner = partner;
    }
    
    @Column(name="INITIALS", unique=true, nullable=false, length=10)
    public String getInitials() {
        return this.initials;
    }
    
    public void setInitials(String initials) {
        this.initials = initials;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByModifiedBy")
    public Set<Tblshoppinglists> getTblshoppinglistsesForModifiedBy() {
        return this.tblshoppinglistsesForModifiedBy;
    }
    
    public void setTblshoppinglistsesForModifiedBy(Set<Tblshoppinglists> tblshoppinglistsesForModifiedBy) {
        this.tblshoppinglistsesForModifiedBy = tblshoppinglistsesForModifiedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByModifiedBy")
    public Set<Tblcontainers> getTblcontainersesForModifiedBy() {
        return this.tblcontainersesForModifiedBy;
    }
    
    public void setTblcontainersesForModifiedBy(Set<Tblcontainers> tblcontainersesForModifiedBy) {
        this.tblcontainersesForModifiedBy = tblcontainersesForModifiedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByCreatedBy")
    public Set<Tblcontainers> getTblcontainersesForCreatedBy() {
        return this.tblcontainersesForCreatedBy;
    }
    
    public void setTblcontainersesForCreatedBy(Set<Tblcontainers> tblcontainersesForCreatedBy) {
        this.tblcontainersesForCreatedBy = tblcontainersesForCreatedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusers")
    public Set<TblcontainercontentsMetaData> getTblcontainercontentsMetaDatas() {
        return this.tblcontainercontentsMetaDatas;
    }
    
    public void setTblcontainercontentsMetaDatas(Set<TblcontainercontentsMetaData> tblcontainercontentsMetaDatas) {
        this.tblcontainercontentsMetaDatas = tblcontainercontentsMetaDatas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByModifiedBy")
    public Set<Tblcontrolwells> getTblcontrolwellsesForModifiedBy() {
        return this.tblcontrolwellsesForModifiedBy;
    }
    
    public void setTblcontrolwellsesForModifiedBy(Set<Tblcontrolwells> tblcontrolwellsesForModifiedBy) {
        this.tblcontrolwellsesForModifiedBy = tblcontrolwellsesForModifiedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByCreatedBy")
    public Set<Tblshoppinglists> getTblshoppinglistsesForCreatedBy() {
        return this.tblshoppinglistsesForCreatedBy;
    }
    
    public void setTblshoppinglistsesForCreatedBy(Set<Tblshoppinglists> tblshoppinglistsesForCreatedBy) {
        this.tblshoppinglistsesForCreatedBy = tblshoppinglistsesForCreatedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByCreatedBy")
    public Set<Tblsubject> getTblsubjectsForCreatedBy() {
        return this.tblsubjectsForCreatedBy;
    }
    
    public void setTblsubjectsForCreatedBy(Set<Tblsubject> tblsubjectsForCreatedBy) {
        this.tblsubjectsForCreatedBy = tblsubjectsForCreatedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByModifiedBy")
    public Set<Tblsamples> getTblsamplesesForModifiedBy() {
        return this.tblsamplesesForModifiedBy;
    }
    
    public void setTblsamplesesForModifiedBy(Set<Tblsamples> tblsamplesesForModifiedBy) {
        this.tblsamplesesForModifiedBy = tblsamplesesForModifiedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByCreatedBy")
    public Set<Tblsamples> getTblsamplesesForCreatedBy() {
        return this.tblsamplesesForCreatedBy;
    }
    
    public void setTblsamplesesForCreatedBy(Set<Tblsamples> tblsamplesesForCreatedBy) {
        this.tblsamplesesForCreatedBy = tblsamplesesForCreatedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByModifiedBy")
    public Set<Tblsubject> getTblsubjectsForModifiedBy() {
        return this.tblsubjectsForModifiedBy;
    }
    
    public void setTblsubjectsForModifiedBy(Set<Tblsubject> tblsubjectsForModifiedBy) {
        this.tblsubjectsForModifiedBy = tblsubjectsForModifiedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsimsusersByCreatedBy")
    public Set<Tblcontrolwells> getTblcontrolwellsesForCreatedBy() {
        return this.tblcontrolwellsesForCreatedBy;
    }
    
    public void setTblcontrolwellsesForCreatedBy(Set<Tblcontrolwells> tblcontrolwellsesForCreatedBy) {
        this.tblcontrolwellsesForCreatedBy = tblcontrolwellsesForCreatedBy;
    }




}


