package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblshoppinglistsubjects generated by hbm2java
 */
@Entity
@Table(name="TBLSHOPPINGLISTSUBJECTS"
    ,schema="ALLERGEN"
)
public class Tblshoppinglistsubjects  implements java.io.Serializable {


     private TblshoppinglistsubjectsId id;
     private Tblsubject tblsubject;

    public Tblshoppinglistsubjects() {
    }

    public Tblshoppinglistsubjects(TblshoppinglistsubjectsId id, Tblsubject tblsubject) {
       this.id = id;
       this.tblsubject = tblsubject;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="listid", column=@Column(name="LISTID", nullable=false) ), 
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ) } )
    public TblshoppinglistsubjectsId getId() {
        return this.id;
    }
    
    public void setId(TblshoppinglistsubjectsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SUBJECTID", nullable=false, insertable=false, updatable=false)
    public Tblsubject getTblsubject() {
        return this.tblsubject;
    }
    
    public void setTblsubject(Tblsubject tblsubject) {
        this.tblsubject = tblsubject;
    }




}


