package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblsubjectalias generated by hbm2java
 */
@Entity
@Table(name="TBLSUBJECTALIAS"
    ,schema="ALLERGEN"
)
public class Tblsubjectalias  implements java.io.Serializable {


     private String alias;
     private Tblsubject tblsubject;

    public Tblsubjectalias() {
    }

    public Tblsubjectalias(String alias, Tblsubject tblsubject) {
       this.alias = alias;
       this.tblsubject = tblsubject;
    }
   
     @Id 
    
    @Column(name="ALIAS", unique=true, nullable=false, length=75)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SUBJECTID", nullable=false)
    public Tblsubject getTblsubject() {
        return this.tblsubject;
    }
    
    public void setTblsubject(Tblsubject tblsubject) {
        this.tblsubject = tblsubject;
    }




}


