package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblshoppinglistcontainersId generated by hbm2java
 */
@Embeddable
public class TblshoppinglistcontainersId  implements java.io.Serializable {


     private int listid;
     private int containerid;

    public TblshoppinglistcontainersId() {
    }

    public TblshoppinglistcontainersId(int listid, int containerid) {
       this.listid = listid;
       this.containerid = containerid;
    }
   

    @Column(name="LISTID", nullable=false)
    public int getListid() {
        return this.listid;
    }
    
    public void setListid(int listid) {
        this.listid = listid;
    }

    @Column(name="CONTAINERID", nullable=false)
    public int getContainerid() {
        return this.containerid;
    }
    
    public void setContainerid(int containerid) {
        this.containerid = containerid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblshoppinglistcontainersId) ) return false;
		 TblshoppinglistcontainersId castOther = ( TblshoppinglistcontainersId ) other; 
         
		 return (this.getListid()==castOther.getListid())
 && (this.getContainerid()==castOther.getContainerid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getListid();
         result = 37 * result + this.getContainerid();
         return result;
   }   


}


