package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblsnpwithlowcallrateincleandataset generated by hbm2java
 */
@Entity
@Table(name="TBLSNPWITHLOWCALLRATEINCLEANDATASET"
    ,schema="ALLERGEN"
)
public class Tblsnpwithlowcallrateincleandataset  implements java.io.Serializable {


     private String rsnumber;
     private String description;

    public Tblsnpwithlowcallrateincleandataset() {
    }

    public Tblsnpwithlowcallrateincleandataset(String rsnumber, String description) {
       this.rsnumber = rsnumber;
       this.description = description;
    }
   
     @Id 
    
    @Column(name="RSNUMBER", unique=true, nullable=false, length=20)
    public String getRsnumber() {
        return this.rsnumber;
    }
    
    public void setRsnumber(String rsnumber) {
        this.rsnumber = rsnumber;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


