package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblsnpstatus generated by hbm2java
 */
@Entity
@Table(name="TBLSNPSTATUS"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames={"SNPID", "COHORTID"}) 
)
public class Tblsnpstatus  implements java.io.Serializable {


     private TblsnpstatusId id;
     private Tblcohortlookup tblcohortlookup;
     private Tblsnp tblsnp;

    public Tblsnpstatus() {
    }

    public Tblsnpstatus(TblsnpstatusId id, Tblcohortlookup tblcohortlookup, Tblsnp tblsnp) {
       this.id = id;
       this.tblcohortlookup = tblcohortlookup;
       this.tblsnp = tblsnp;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="snpid", column=@Column(name="SNPID", nullable=false) ), 
        @AttributeOverride(name="cohortid", column=@Column(name="COHORTID", nullable=false) ), 
        @AttributeOverride(name="callrate", column=@Column(name="CALLRATE", precision=53, scale=0) ), 
        @AttributeOverride(name="maf", column=@Column(name="MAF", precision=53, scale=0) ), 
        @AttributeOverride(name="valid", column=@Column(name="VALID") ), 
        @AttributeOverride(name="panelid", column=@Column(name="PANELID", nullable=false) ) } )
    public TblsnpstatusId getId() {
        return this.id;
    }
    
    public void setId(TblsnpstatusId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COHORTID", nullable=false, insertable=false, updatable=false)
    public Tblcohortlookup getTblcohortlookup() {
        return this.tblcohortlookup;
    }
    
    public void setTblcohortlookup(Tblcohortlookup tblcohortlookup) {
        this.tblcohortlookup = tblcohortlookup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SNPID", nullable=false, insertable=false, updatable=false)
    public Tblsnp getTblsnp() {
        return this.tblsnp;
    }
    
    public void setTblsnp(Tblsnp tblsnp) {
        this.tblsnp = tblsnp;
    }




}


