package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblstatus generated by hbm2java
 */
@Entity
@Table(name="TBLSTATUS"
    ,schema="ALLERGEN"
)
public class Tblstatus  implements java.io.Serializable {


     private TblstatusId id;
     private Tblphenotypelookup tblphenotypelookup;
     private Tblstatustype tblstatustype;
     private Tblethnicitylookup tblethnicitylookup;
     private Tblcohortlookup tblcohortlookup;

    public Tblstatus() {
    }

	
    public Tblstatus(TblstatusId id, Tblstatustype tblstatustype, Tblcohortlookup tblcohortlookup) {
        this.id = id;
        this.tblstatustype = tblstatustype;
        this.tblcohortlookup = tblcohortlookup;
    }
    public Tblstatus(TblstatusId id, Tblphenotypelookup tblphenotypelookup, Tblstatustype tblstatustype, Tblethnicitylookup tblethnicitylookup, Tblcohortlookup tblcohortlookup) {
       this.id = id;
       this.tblphenotypelookup = tblphenotypelookup;
       this.tblstatustype = tblstatustype;
       this.tblethnicitylookup = tblethnicitylookup;
       this.tblcohortlookup = tblcohortlookup;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="cohortid", column=@Column(name="COHORTID", nullable=false) ), 
        @AttributeOverride(name="statustypeid", column=@Column(name="STATUSTYPEID", nullable=false) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", nullable=false) ), 
        @AttributeOverride(name="phenotypeid", column=@Column(name="PHENOTYPEID") ), 
        @AttributeOverride(name="ethnicityid", column=@Column(name="ETHNICITYID") ), 
        @AttributeOverride(name="code", column=@Column(name="CODE") ) } )
    public TblstatusId getId() {
        return this.id;
    }
    
    public void setId(TblstatusId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PHENOTYPEID", insertable=false, updatable=false)
    public Tblphenotypelookup getTblphenotypelookup() {
        return this.tblphenotypelookup;
    }
    
    public void setTblphenotypelookup(Tblphenotypelookup tblphenotypelookup) {
        this.tblphenotypelookup = tblphenotypelookup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUSTYPEID", nullable=false, insertable=false, updatable=false)
    public Tblstatustype getTblstatustype() {
        return this.tblstatustype;
    }
    
    public void setTblstatustype(Tblstatustype tblstatustype) {
        this.tblstatustype = tblstatustype;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ETHNICITYID", insertable=false, updatable=false)
    public Tblethnicitylookup getTblethnicitylookup() {
        return this.tblethnicitylookup;
    }
    
    public void setTblethnicitylookup(Tblethnicitylookup tblethnicitylookup) {
        this.tblethnicitylookup = tblethnicitylookup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COHORTID", nullable=false, insertable=false, updatable=false)
    public Tblcohortlookup getTblcohortlookup() {
        return this.tblcohortlookup;
    }
    
    public void setTblcohortlookup(Tblcohortlookup tblcohortlookup) {
        this.tblcohortlookup = tblcohortlookup;
    }




}


