package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblshoppinglistcontainers generated by hbm2java
 */
@Entity
@Table(name="TBLSHOPPINGLISTCONTAINERS"
    ,schema="ALLERGEN"
)
public class Tblshoppinglistcontainers  implements java.io.Serializable {


     private TblshoppinglistcontainersId id;

    public Tblshoppinglistcontainers() {
    }

    public Tblshoppinglistcontainers(TblshoppinglistcontainersId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="listid", column=@Column(name="LISTID", nullable=false) ), 
        @AttributeOverride(name="containerid", column=@Column(name="CONTAINERID", nullable=false) ) } )
    public TblshoppinglistcontainersId getId() {
        return this.id;
    }
    
    public void setId(TblshoppinglistcontainersId id) {
        this.id = id;
    }




}


