package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblsampleslog generated by hbm2java
 */
@Entity
@Table(name="TBLSAMPLESLOG"
    ,schema="ALLERGEN"
)
public class Tblsampleslog  implements java.io.Serializable {


     private TblsampleslogId id;

    public Tblsampleslog() {
    }

    public Tblsampleslog(TblsampleslogId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sampleid", column=@Column(name="SAMPLEID", nullable=false) ), 
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=25) ), 
        @AttributeOverride(name="valid", column=@Column(name="VALID", nullable=false) ), 
        @AttributeOverride(name="parent", column=@Column(name="PARENT") ), 
        @AttributeOverride(name="sampletypeid", column=@Column(name="SAMPLETYPEID") ), 
        @AttributeOverride(name="sampleprocessid", column=@Column(name="SAMPLEPROCESSID") ), 
        @AttributeOverride(name="parentid", column=@Column(name="PARENTID") ), 
        @AttributeOverride(name="collectiondate", column=@Column(name="COLLECTIONDATE", nullable=false, length=10) ), 
        @AttributeOverride(name="comments", column=@Column(name="COMMENTS", length=1000) ), 
        @AttributeOverride(name="sampletypeyear1id", column=@Column(name="SAMPLETYPEYEAR1ID") ), 
        @AttributeOverride(name="extractiondateyear1", column=@Column(name="EXTRACTIONDATEYEAR1", length=10) ), 
        @AttributeOverride(name="collectiondateyear1", column=@Column(name="COLLECTIONDATEYEAR1", length=10) ), 
        @AttributeOverride(name="extractiondate", column=@Column(name="EXTRACTIONDATE", length=10) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY", nullable=false) ), 
        @AttributeOverride(name="created", column=@Column(name="CREATED", nullable=false, length=26) ), 
        @AttributeOverride(name="modifiedBy", column=@Column(name="MODIFIED_BY") ), 
        @AttributeOverride(name="modified", column=@Column(name="MODIFIED", length=26) ), 
        @AttributeOverride(name="updated", column=@Column(name="UPDATED", nullable=false, length=26) ) } )
    public TblsampleslogId getId() {
        return this.id;
    }
    
    public void setId(TblsampleslogId id) {
        this.id = id;
    }




}


