package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblshipcontId generated by hbm2java
 */
@Embeddable
public class TblshipcontId  implements java.io.Serializable {


     private long shipcontid;
     private long shipmentid;
     private long containerid;

    public TblshipcontId() {
    }

    public TblshipcontId(long shipcontid, long shipmentid, long containerid) {
       this.shipcontid = shipcontid;
       this.shipmentid = shipmentid;
       this.containerid = containerid;
    }
   

    @Column(name="SHIPCONTID", nullable=false)
    public long getShipcontid() {
        return this.shipcontid;
    }
    
    public void setShipcontid(long shipcontid) {
        this.shipcontid = shipcontid;
    }

    @Column(name="SHIPMENTID", nullable=false)
    public long getShipmentid() {
        return this.shipmentid;
    }
    
    public void setShipmentid(long shipmentid) {
        this.shipmentid = shipmentid;
    }

    @Column(name="CONTAINERID", nullable=false)
    public long getContainerid() {
        return this.containerid;
    }
    
    public void setContainerid(long containerid) {
        this.containerid = containerid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblshipcontId) ) return false;
		 TblshipcontId castOther = ( TblshipcontId ) other; 
         
		 return (this.getShipcontid()==castOther.getShipcontid())
 && (this.getShipmentid()==castOther.getShipmentid())
 && (this.getContainerid()==castOther.getContainerid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getShipcontid();
         result = 37 * result + (int) this.getShipmentid();
         result = 37 * result + (int) this.getContainerid();
         return result;
   }   


}


