package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblsubjectlog generated by hbm2java
 */
@Entity
@Table(name="TBLSUBJECTLOG"
    ,schema="ALLERGEN"
)
public class Tblsubjectlog  implements java.io.Serializable {


     private TblsubjectlogId id;

    public Tblsubjectlog() {
    }

    public Tblsubjectlog(TblsubjectlogId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ), 
        @AttributeOverride(name="cohortid", column=@Column(name="COHORTID", nullable=false) ), 
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, length=25) ), 
        @AttributeOverride(name="familyid", column=@Column(name="FAMILYID", nullable=false, length=25) ), 
        @AttributeOverride(name="gender", column=@Column(name="GENDER", nullable=false) ), 
        @AttributeOverride(name="code", column=@Column(name="CODE", nullable=false) ), 
        @AttributeOverride(name="hasconsent", column=@Column(name="HASCONSENT", nullable=false) ), 
        @AttributeOverride(name="motherid", column=@Column(name="MOTHERID", nullable=false, length=25) ), 
        @AttributeOverride(name="fatherid", column=@Column(name="FATHERID", nullable=false, length=25) ), 
        @AttributeOverride(name="ethnicityid", column=@Column(name="ETHNICITYID", nullable=false) ), 
        @AttributeOverride(name="passedqc", column=@Column(name="PASSEDQC", nullable=false) ), 
        @AttributeOverride(name="numsamplescollected", column=@Column(name="NUMSAMPLESCOLLECTED", nullable=false) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY", nullable=false) ), 
        @AttributeOverride(name="created", column=@Column(name="CREATED", nullable=false, length=26) ), 
        @AttributeOverride(name="modifiedBy", column=@Column(name="MODIFIED_BY") ), 
        @AttributeOverride(name="modified", column=@Column(name="MODIFIED", length=26) ), 
        @AttributeOverride(name="updated", column=@Column(name="UPDATED", nullable=false, length=26) ) } )
    public TblsubjectlogId getId() {
        return this.id;
    }
    
    public void setId(TblsubjectlogId id) {
        this.id = id;
    }




}


