package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblsampledocumentsId generated by hbm2java
 */
@Embeddable
public class TblsampledocumentsId  implements java.io.Serializable {


     private long sampledocumentid;
     private long sampleid;
     private String filename;
     private Blob document;
     private String comments;
     private int createdBy;
     private Date created;
     private Integer modifiedBy;
     private Date modified;

    public TblsampledocumentsId() {
    }

	
    public TblsampledocumentsId(long sampledocumentid, long sampleid, Blob document, int createdBy, Date created) {
        this.sampledocumentid = sampledocumentid;
        this.sampleid = sampleid;
        this.document = document;
        this.createdBy = createdBy;
        this.created = created;
    }
    public TblsampledocumentsId(long sampledocumentid, long sampleid, String filename, Blob document, String comments, int createdBy, Date created, Integer modifiedBy, Date modified) {
       this.sampledocumentid = sampledocumentid;
       this.sampleid = sampleid;
       this.filename = filename;
       this.document = document;
       this.comments = comments;
       this.createdBy = createdBy;
       this.created = created;
       this.modifiedBy = modifiedBy;
       this.modified = modified;
    }
   

    @Column(name="SAMPLEDOCUMENTID", nullable=false)
    public long getSampledocumentid() {
        return this.sampledocumentid;
    }
    
    public void setSampledocumentid(long sampledocumentid) {
        this.sampledocumentid = sampledocumentid;
    }

    @Column(name="SAMPLEID", nullable=false)
    public long getSampleid() {
        return this.sampleid;
    }
    
    public void setSampleid(long sampleid) {
        this.sampleid = sampleid;
    }

    @Column(name="FILENAME")
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Column(name="DOCUMENT", nullable=false)
    public Blob getDocument() {
        return this.document;
    }
    
    public void setDocument(Blob document) {
        this.document = document;
    }

    @Column(name="COMMENTS", length=1000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name="CREATED_BY", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name="CREATED", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name="MODIFIED_BY")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Column(name="MODIFIED", length=26)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblsampledocumentsId) ) return false;
		 TblsampledocumentsId castOther = ( TblsampledocumentsId ) other; 
         
		 return (this.getSampledocumentid()==castOther.getSampledocumentid())
 && (this.getSampleid()==castOther.getSampleid())
 && ( (this.getFilename()==castOther.getFilename()) || ( this.getFilename()!=null && castOther.getFilename()!=null && this.getFilename().equals(castOther.getFilename()) ) )
 && ( (this.getDocument()==castOther.getDocument()) || ( this.getDocument()!=null && castOther.getDocument()!=null && this.getDocument().equals(castOther.getDocument()) ) )
 && ( (this.getComments()==castOther.getComments()) || ( this.getComments()!=null && castOther.getComments()!=null && this.getComments().equals(castOther.getComments()) ) )
 && (this.getCreatedBy()==castOther.getCreatedBy())
 && ( (this.getCreated()==castOther.getCreated()) || ( this.getCreated()!=null && castOther.getCreated()!=null && this.getCreated().equals(castOther.getCreated()) ) )
 && ( (this.getModifiedBy()==castOther.getModifiedBy()) || ( this.getModifiedBy()!=null && castOther.getModifiedBy()!=null && this.getModifiedBy().equals(castOther.getModifiedBy()) ) )
 && ( (this.getModified()==castOther.getModified()) || ( this.getModified()!=null && castOther.getModified()!=null && this.getModified().equals(castOther.getModified()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getSampledocumentid();
         result = 37 * result + (int) this.getSampleid();
         result = 37 * result + ( getFilename() == null ? 0 : this.getFilename().hashCode() );
         result = 37 * result + ( getDocument() == null ? 0 : this.getDocument().hashCode() );
         result = 37 * result + ( getComments() == null ? 0 : this.getComments().hashCode() );
         result = 37 * result + this.getCreatedBy();
         result = 37 * result + ( getCreated() == null ? 0 : this.getCreated().hashCode() );
         result = 37 * result + ( getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode() );
         result = 37 * result + ( getModified() == null ? 0 : this.getModified().hashCode() );
         return result;
   }   


}


