package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblsnpalternatenames generated by hbm2java
 */
@Entity
@Table(name="TBLSNPALTERNATENAMES"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class Tblsnpalternatenames  implements java.io.Serializable {


     private TblsnpalternatenamesId id;
     private Tblsnp tblsnp;

    public Tblsnpalternatenames() {
    }

    public Tblsnpalternatenames(TblsnpalternatenamesId id, Tblsnp tblsnp) {
       this.id = id;
       this.tblsnp = tblsnp;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="snpid", column=@Column(name="SNPID", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", unique=true, nullable=false, length=25) ) } )
    public TblsnpalternatenamesId getId() {
        return this.id;
    }
    
    public void setId(TblsnpalternatenamesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SNPID", nullable=false, insertable=false, updatable=false)
    public Tblsnp getTblsnp() {
        return this.tblsnp;
    }
    
    public void setTblsnp(Tblsnp tblsnp) {
        this.tblsnp = tblsnp;
    }




}


