package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblshipcont generated by hbm2java
 */
@Entity
@Table(name="TBLSHIPCONT"
    ,schema="ALLERGEN"
)
public class Tblshipcont  implements java.io.Serializable {


     private TblshipcontId id;

    public Tblshipcont() {
    }

    public Tblshipcont(TblshipcontId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="shipcontid", column=@Column(name="SHIPCONTID", nullable=false) ), 
        @AttributeOverride(name="shipmentid", column=@Column(name="SHIPMENTID", nullable=false) ), 
        @AttributeOverride(name="containerid", column=@Column(name="CONTAINERID", nullable=false) ) } )
    public TblshipcontId getId() {
        return this.id;
    }
    
    public void setId(TblshipcontId id) {
        this.id = id;
    }




}


