package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblsubjectpopulation generated by hbm2java
 */
@Entity
@Table(name="TBLSUBJECTPOPULATION"
    ,schema="ALLERGEN"
)
public class Tblsubjectpopulation  implements java.io.Serializable {


     private TblsubjectpopulationId id;

    public Tblsubjectpopulation() {
    }

    public Tblsubjectpopulation(TblsubjectpopulationId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ), 
        @AttributeOverride(name="cohortpopulationid", column=@Column(name="COHORTPOPULATIONID", nullable=false) ) } )
    public TblsubjectpopulationId getId() {
        return this.id;
    }
    
    public void setId(TblsubjectpopulationId id) {
        this.id = id;
    }




}


