package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tblsamples generated by hbm2java
 */
@Entity
@Table(name="TBLSAMPLES"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class Tblsamples  implements java.io.Serializable {


     private long sampleid;
     @JsonIgnoreProperties("tblsampleses")
     private Tblsampletypes tblsampletypes;
     @JsonIgnore
     private Tblsimsusers tblsimsusersByModifiedBy;
     @JsonIgnore
     private Tblsimsusers tblsimsusersByCreatedBy;
     @JsonIgnore
     private Tblsampleprocessing tblsampleprocessing;
     @JsonIgnoreProperties("tblsampleses")
     private Tblsubject tblsubject;
     private String name;
     private short valid;
     private Integer numcalls;
     private String location;
     private Integer numnocalls;
     private String freezerlocation;
     private Double concentration;
     private Long parent;
     private Long parentid;
     private Date collectiondate;
     private String comments;
     private Integer sampletypeyear1id;
     private Date extractiondateyear1;
     private Date collectiondateyear1;
     private Date extractiondate;
     private Date created;
     private Date modified;
    @JsonIgnoreProperties("tblsamples")
     private Set<Tblcontainercontents> tblcontainercontentses = new HashSet<Tblcontainercontents>(0);
     @JsonIgnore
     private Set<Tblsampleqcstatus> tblsampleqcstatuses = new HashSet<Tblsampleqcstatus>(0);
     @JsonIgnore
     private Set<Tblshoppinglistsamples> tblshoppinglistsampleses = new HashSet<Tblshoppinglistsamples>(0);

    public Tblsamples() {
    }

	
    public Tblsamples(long sampleid, Tblsimsusers tblsimsusersByCreatedBy, Tblsubject tblsubject, String name, short valid, Date collectiondate, Date created) {
        this.sampleid = sampleid;
        this.tblsimsusersByCreatedBy = tblsimsusersByCreatedBy;
        this.tblsubject = tblsubject;
        this.name = name;
        this.valid = valid;
        this.collectiondate = collectiondate;
        this.created = created;
    }
    public Tblsamples(long sampleid, Tblsampletypes tblsampletypes, Tblsimsusers tblsimsusersByModifiedBy, Tblsimsusers tblsimsusersByCreatedBy, Tblsampleprocessing tblsampleprocessing, Tblsubject tblsubject, String name, short valid, Integer numcalls, String location, Integer numnocalls, String freezerlocation, Double concentration, Long parent, Long parentid, Date collectiondate, String comments, Integer sampletypeyear1id, Date extractiondateyear1, Date collectiondateyear1, Date extractiondate, Date created, Date modified, Set<Tblcontainercontents> tblcontainercontentses, Set<Tblsampleqcstatus> tblsampleqcstatuses, Set<Tblshoppinglistsamples> tblshoppinglistsampleses) {
       this.sampleid = sampleid;
       this.tblsampletypes = tblsampletypes;
       this.tblsimsusersByModifiedBy = tblsimsusersByModifiedBy;
       this.tblsimsusersByCreatedBy = tblsimsusersByCreatedBy;
       this.tblsampleprocessing = tblsampleprocessing;
       this.tblsubject = tblsubject;
       this.name = name;
       this.valid = valid;
       this.numcalls = numcalls;
       this.location = location;
       this.numnocalls = numnocalls;
       this.freezerlocation = freezerlocation;
       this.concentration = concentration;
       this.parent = parent;
       this.parentid = parentid;
       this.collectiondate = collectiondate;
       this.comments = comments;
       this.sampletypeyear1id = sampletypeyear1id;
       this.extractiondateyear1 = extractiondateyear1;
       this.collectiondateyear1 = collectiondateyear1;
       this.extractiondate = extractiondate;
       this.created = created;
       this.modified = modified;
       this.tblcontainercontentses = tblcontainercontentses;
       this.tblsampleqcstatuses = tblsampleqcstatuses;
       this.tblshoppinglistsampleses = tblshoppinglistsampleses;
    }
   
     @Id 
    
    @Column(name="SAMPLEID", unique=true, nullable=false)
    public long getSampleid() {
        return this.sampleid;
    }
    
    public void setSampleid(long sampleid) {
        this.sampleid = sampleid;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SAMPLETYPEID")
    public Tblsampletypes getTblsampletypes() {
        return this.tblsampletypes;
    }
    
    public void setTblsampletypes(Tblsampletypes tblsampletypes) {
        this.tblsampletypes = tblsampletypes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MODIFIED_BY")
    public Tblsimsusers getTblsimsusersByModifiedBy() {
        return this.tblsimsusersByModifiedBy;
    }
    
    public void setTblsimsusersByModifiedBy(Tblsimsusers tblsimsusersByModifiedBy) {
        this.tblsimsusersByModifiedBy = tblsimsusersByModifiedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATED_BY", nullable=false)
    public Tblsimsusers getTblsimsusersByCreatedBy() {
        return this.tblsimsusersByCreatedBy;
    }
    
    public void setTblsimsusersByCreatedBy(Tblsimsusers tblsimsusersByCreatedBy) {
        this.tblsimsusersByCreatedBy = tblsimsusersByCreatedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SAMPLEPROCESSID")
    public Tblsampleprocessing getTblsampleprocessing() {
        return this.tblsampleprocessing;
    }
    
    public void setTblsampleprocessing(Tblsampleprocessing tblsampleprocessing) {
        this.tblsampleprocessing = tblsampleprocessing;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SUBJECTID", nullable=false)
    public Tblsubject getTblsubject() {
        return this.tblsubject;
    }
    
    public void setTblsubject(Tblsubject tblsubject) {
        this.tblsubject = tblsubject;
    }
    
    @Column(name="NAME", unique=true, nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="VALID", nullable=false)
    public short getValid() {
        return this.valid;
    }
    
    public void setValid(short valid) {
        this.valid = valid;
    }
    
    @Column(name="NUMCALLS")
    public Integer getNumcalls() {
        return this.numcalls;
    }
    
    public void setNumcalls(Integer numcalls) {
        this.numcalls = numcalls;
    }
    
    @Column(name="LOCATION", length=100)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    
    @Column(name="NUMNOCALLS")
    public Integer getNumnocalls() {
        return this.numnocalls;
    }
    
    public void setNumnocalls(Integer numnocalls) {
        this.numnocalls = numnocalls;
    }
    
    @Column(name="FREEZERLOCATION", length=45)
    public String getFreezerlocation() {
        return this.freezerlocation;
    }
    
    public void setFreezerlocation(String freezerlocation) {
        this.freezerlocation = freezerlocation;
    }
    
    @Column(name="CONCENTRATION", precision=53, scale=0)
    public Double getConcentration() {
        return this.concentration;
    }
    
    public void setConcentration(Double concentration) {
        this.concentration = concentration;
    }
    
    @Column(name="PARENT")
    public Long getParent() {
        return this.parent;
    }
    
    public void setParent(Long parent) {
        this.parent = parent;
    }
    
    @Column(name="PARENTID")
    public Long getParentid() {
        return this.parentid;
    }
    
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="COLLECTIONDATE", nullable=false, length=10)
    public Date getCollectiondate() {
        return this.collectiondate;
    }
    
    public void setCollectiondate(Date collectiondate) {
        this.collectiondate = collectiondate;
    }
    
    @Column(name="COMMENTS", length=1000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    
    @Column(name="SAMPLETYPEYEAR1ID")
    public Integer getSampletypeyear1id() {
        return this.sampletypeyear1id;
    }
    
    public void setSampletypeyear1id(Integer sampletypeyear1id) {
        this.sampletypeyear1id = sampletypeyear1id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EXTRACTIONDATEYEAR1", length=10)
    public Date getExtractiondateyear1() {
        return this.extractiondateyear1;
    }
    
    public void setExtractiondateyear1(Date extractiondateyear1) {
        this.extractiondateyear1 = extractiondateyear1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="COLLECTIONDATEYEAR1", length=10)
    public Date getCollectiondateyear1() {
        return this.collectiondateyear1;
    }
    
    public void setCollectiondateyear1(Date collectiondateyear1) {
        this.collectiondateyear1 = collectiondateyear1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EXTRACTIONDATE", length=10)
    public Date getExtractiondate() {
        return this.extractiondate;
    }
    
    public void setExtractiondate(Date extractiondate) {
        this.extractiondate = extractiondate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=26)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsamples")
    public Set<Tblcontainercontents> getTblcontainercontentses() {
        return this.tblcontainercontentses;
    }
    
    public void setTblcontainercontentses(Set<Tblcontainercontents> tblcontainercontentses) {
        this.tblcontainercontentses = tblcontainercontentses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsamples")
    public Set<Tblsampleqcstatus> getTblsampleqcstatuses() {
        return this.tblsampleqcstatuses;
    }
    
    public void setTblsampleqcstatuses(Set<Tblsampleqcstatus> tblsampleqcstatuses) {
        this.tblsampleqcstatuses = tblsampleqcstatuses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsamples")
    public Set<Tblshoppinglistsamples> getTblshoppinglistsampleses() {
        return this.tblshoppinglistsampleses;
    }
    
    public void setTblshoppinglistsampleses(Set<Tblshoppinglistsamples> tblshoppinglistsampleses) {
        this.tblshoppinglistsampleses = tblshoppinglistsampleses;
    }




}


