package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblshipment generated by hbm2java
 */
@Entity
@Table(name="TBLSHIPMENT"
    ,schema="ALLERGEN"
)
public class Tblshipment  implements java.io.Serializable {


     private TblshipmentId id;

    public Tblshipment() {
    }

    public Tblshipment(TblshipmentId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="shipmentid", column=@Column(name="SHIPMENTID", nullable=false) ), 
        @AttributeOverride(name="shipmentname", column=@Column(name="SHIPMENTNAME") ), 
        @AttributeOverride(name="shipdate", column=@Column(name="SHIPDATE", length=10) ), 
        @AttributeOverride(name="shippedtoid", column=@Column(name="SHIPPEDTOID") ), 
        @AttributeOverride(name="shipaction", column=@Column(name="SHIPACTION") ), 
        @AttributeOverride(name="comments", column=@Column(name="COMMENTS", length=1000) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY", nullable=false) ), 
        @AttributeOverride(name="created", column=@Column(name="CREATED", nullable=false, length=26) ), 
        @AttributeOverride(name="modifiedBy", column=@Column(name="MODIFIED_BY") ), 
        @AttributeOverride(name="modified", column=@Column(name="MODIFIED", length=26) ) } )
    public TblshipmentId getId() {
        return this.id;
    }
    
    public void setId(TblshipmentId id) {
        this.id = id;
    }




}


