package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblsampledocuments generated by hbm2java
 */
@Entity
@Table(name="TBLSAMPLEDOCUMENTS"
    ,schema="ALLERGEN"
)
public class Tblsampledocuments  implements java.io.Serializable {


     private TblsampledocumentsId id;

    public Tblsampledocuments() {
    }

    public Tblsampledocuments(TblsampledocumentsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sampledocumentid", column=@Column(name="SAMPLEDOCUMENTID", nullable=false) ), 
        @AttributeOverride(name="sampleid", column=@Column(name="SAMPLEID", nullable=false) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME") ), 
        @AttributeOverride(name="document", column=@Column(name="DOCUMENT", nullable=false) ), 
        @AttributeOverride(name="comments", column=@Column(name="COMMENTS", length=1000) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY", nullable=false) ), 
        @AttributeOverride(name="created", column=@Column(name="CREATED", nullable=false, length=26) ), 
        @AttributeOverride(name="modifiedBy", column=@Column(name="MODIFIED_BY") ), 
        @AttributeOverride(name="modified", column=@Column(name="MODIFIED", length=26) ) } )
    public TblsampledocumentsId getId() {
        return this.id;
    }
    
    public void setId(TblsampledocumentsId id) {
        this.id = id;
    }




}


