package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblshippedto generated by hbm2java
 */
@Entity
@Table(name="TBLSHIPPEDTO"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="DESCRIPTION") 
)
public class Tblshippedto  implements java.io.Serializable {


     private int shippedtoid;
     private String description;
     private int sortorder;
     @JsonIgnoreProperties("tblshippedto")
     private Set<Tblcontainers> tblcontainerses = new HashSet<Tblcontainers>(0);

    public Tblshippedto() {
    }

	
    public Tblshippedto(int shippedtoid, String description, int sortorder) {
        this.shippedtoid = shippedtoid;
        this.description = description;
        this.sortorder = sortorder;
    }
    public Tblshippedto(int shippedtoid, String description, int sortorder, Set<Tblcontainers> tblcontainerses) {
       this.shippedtoid = shippedtoid;
       this.description = description;
       this.sortorder = sortorder;
       this.tblcontainerses = tblcontainerses;
    }
   
     @Id 
    
    @Column(name="SHIPPEDTOID", unique=true, nullable=false)
    public int getShippedtoid() {
        return this.shippedtoid;
    }
    
    public void setShippedtoid(int shippedtoid) {
        this.shippedtoid = shippedtoid;
    }
    
    @Column(name="DESCRIPTION", unique=true, nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="SORTORDER", nullable=false)
    public int getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(int sortorder) {
        this.sortorder = sortorder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblshippedto")
    public Set<Tblcontainers> getTblcontainerses() {
        return this.tblcontainerses;
    }
    
    public void setTblcontainerses(Set<Tblcontainers> tblcontainerses) {
        this.tblcontainerses = tblcontainerses;
    }




}


