package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblsnp generated by hbm2java
 */
@Entity
@Table(name="TBLSNP"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="RSNUMBER") 
)
public class Tblsnp  implements java.io.Serializable {


     private int snpid;
     private Tblgene tblgene;
     private String rsnumber;
     private String chromosome;
     private Integer pos;
     private String majorallele;
     private String minorallele;
     private String strand;
     private String fxnClass;
     @JsonIgnore
     private Set<Tblgenotype> tblgenotypes = new HashSet<Tblgenotype>(0);
     @JsonIgnore
     private Set<Tblgenotypingrunsnpstatus> tblgenotypingrunsnpstatuses = new HashSet<Tblgenotypingrunsnpstatus>(0);
     @JsonIgnore
     private Set<Tblcleangenotypes> tblcleangenotypeses = new HashSet<Tblcleangenotypes>(0);
     @JsonIgnore
     private Set<Tblreferences> tblreferenceses = new HashSet<Tblreferences>(0);
     @JsonIgnore
     private Set<Tblsnpstatus> tblsnpstatuses = new HashSet<Tblsnpstatus>(0);
     @JsonIgnore
     private Set<Tblsnpsetlookup> tblsnpsetlookups = new HashSet<Tblsnpsetlookup>(0);
     @JsonIgnore
     private Set<Tblsnpalternatenames> tblsnpalternatenameses = new HashSet<Tblsnpalternatenames>(0);
     @JsonBackReference
     private Set<Tblfrequencies> tblfrequencieses = new HashSet<Tblfrequencies>(0);
     @JsonIgnore
     private Set<Tblgenaphausers> tblgenaphauserses = new HashSet<Tblgenaphausers>(0);
     @JsonIgnore
     private Set<Tblgenotypes> tblgenotypeses = new HashSet<Tblgenotypes>(0);
    @JsonIgnore 
    private Set<Tblethnicityfrequency> tblethnicityfrequencies = new HashSet<Tblethnicityfrequency>(0);
    @JsonIgnore
    private Set<Tblvalues> tblvalueses = new HashSet<Tblvalues>(0);

    public Tblsnp() {
    }

	
    public Tblsnp(int snpid, String rsnumber, String strand) {
        this.snpid = snpid;
        this.rsnumber = rsnumber;
        this.strand = strand;
    }
    public Tblsnp(int snpid, Tblgene tblgene, String rsnumber, String chromosome, Integer pos, String majorallele, String minorallele, String strand, String fxnClass, Set<Tblgenotype> tblgenotypes, Set<Tblgenotypingrunsnpstatus> tblgenotypingrunsnpstatuses, Set<Tblcleangenotypes> tblcleangenotypeses, Set<Tblreferences> tblreferenceses, Set<Tblsnpstatus> tblsnpstatuses, Set<Tblsnpsetlookup> tblsnpsetlookups, Set<Tblsnpalternatenames> tblsnpalternatenameses, Set<Tblfrequencies> tblfrequencieses, Set<Tblgenaphausers> tblgenaphauserses, Set<Tblgenotypes> tblgenotypeses, Set<Tblethnicityfrequency> tblethnicityfrequencies, Set<Tblvalues> tblvalueses) {
       this.snpid = snpid;
       this.tblgene = tblgene;
       this.rsnumber = rsnumber;
       this.chromosome = chromosome;
       this.pos = pos;
       this.majorallele = majorallele;
       this.minorallele = minorallele;
       this.strand = strand;
       this.fxnClass = fxnClass;
       this.tblgenotypes = tblgenotypes;
       this.tblgenotypingrunsnpstatuses = tblgenotypingrunsnpstatuses;
       this.tblcleangenotypeses = tblcleangenotypeses;
       this.tblreferenceses = tblreferenceses;
       this.tblsnpstatuses = tblsnpstatuses;
       this.tblsnpsetlookups = tblsnpsetlookups;
       this.tblsnpalternatenameses = tblsnpalternatenameses;
       this.tblfrequencieses = tblfrequencieses;
       this.tblgenaphauserses = tblgenaphauserses;
       this.tblgenotypeses = tblgenotypeses;
       this.tblethnicityfrequencies = tblethnicityfrequencies;
       this.tblvalueses = tblvalueses;
    }
   
     @Id 
    
    @Column(name="SNPID", unique=true, nullable=false)
    public int getSnpid() {
        return this.snpid;
    }
    
    public void setSnpid(int snpid) {
        this.snpid = snpid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENEID")
    public Tblgene getTblgene() {
        return this.tblgene;
    }
    
    public void setTblgene(Tblgene tblgene) {
        this.tblgene = tblgene;
    }
    
    @Column(name="RSNUMBER", unique=true, nullable=false, length=25)
    public String getRsnumber() {
        return this.rsnumber;
    }
    
    public void setRsnumber(String rsnumber) {
        this.rsnumber = rsnumber;
    }
    
    @Column(name="CHROMOSOME", length=2)
    public String getChromosome() {
        return this.chromosome;
    }
    
    public void setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }
    
    @Column(name="POS")
    public Integer getPos() {
        return this.pos;
    }
    
    public void setPos(Integer pos) {
        this.pos = pos;
    }
    
    @Column(name="MAJORALLELE", length=1)
    public String getMajorallele() {
        return this.majorallele;
    }
    
    public void setMajorallele(String majorallele) {
        this.majorallele = majorallele;
    }
    
    @Column(name="MINORALLELE", length=1)
    public String getMinorallele() {
        return this.minorallele;
    }
    
    public void setMinorallele(String minorallele) {
        this.minorallele = minorallele;
    }
    
    @Column(name="STRAND", nullable=false, length=1)
    public String getStrand() {
        return this.strand;
    }
    
    public void setStrand(String strand) {
        this.strand = strand;
    }
    
    @Column(name="FXN_CLASS", length=50)
    public String getFxnClass() {
        return this.fxnClass;
    }
    
    public void setFxnClass(String fxnClass) {
        this.fxnClass = fxnClass;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblgenotype> getTblgenotypes() {
        return this.tblgenotypes;
    }
    
    public void setTblgenotypes(Set<Tblgenotype> tblgenotypes) {
        this.tblgenotypes = tblgenotypes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblgenotypingrunsnpstatus> getTblgenotypingrunsnpstatuses() {
        return this.tblgenotypingrunsnpstatuses;
    }
    
    public void setTblgenotypingrunsnpstatuses(Set<Tblgenotypingrunsnpstatus> tblgenotypingrunsnpstatuses) {
        this.tblgenotypingrunsnpstatuses = tblgenotypingrunsnpstatuses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblcleangenotypes> getTblcleangenotypeses() {
        return this.tblcleangenotypeses;
    }
    
    public void setTblcleangenotypeses(Set<Tblcleangenotypes> tblcleangenotypeses) {
        this.tblcleangenotypeses = tblcleangenotypeses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="TBLSNPREFERENCES", schema="ALLERGEN", joinColumns = { 
        @JoinColumn(name="SNPID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="REFERENCEID", nullable=false, updatable=false) })
    public Set<Tblreferences> getTblreferenceses() {
        return this.tblreferenceses;
    }
    
    public void setTblreferenceses(Set<Tblreferences> tblreferenceses) {
        this.tblreferenceses = tblreferenceses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblsnpstatus> getTblsnpstatuses() {
        return this.tblsnpstatuses;
    }
    
    public void setTblsnpstatuses(Set<Tblsnpstatus> tblsnpstatuses) {
        this.tblsnpstatuses = tblsnpstatuses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnps")
    public Set<Tblsnpsetlookup> getTblsnpsetlookups() {
        return this.tblsnpsetlookups;
    }
    
    public void setTblsnpsetlookups(Set<Tblsnpsetlookup> tblsnpsetlookups) {
        this.tblsnpsetlookups = tblsnpsetlookups;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblsnpalternatenames> getTblsnpalternatenameses() {
        return this.tblsnpalternatenameses;
    }
    
    public void setTblsnpalternatenameses(Set<Tblsnpalternatenames> tblsnpalternatenameses) {
        this.tblsnpalternatenameses = tblsnpalternatenameses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblfrequencies> getTblfrequencieses() {
        return this.tblfrequencieses;
    }
    
    public void setTblfrequencieses(Set<Tblfrequencies> tblfrequencieses) {
        this.tblfrequencieses = tblfrequencieses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnps")
    public Set<Tblgenaphausers> getTblgenaphauserses() {
        return this.tblgenaphauserses;
    }
    
    public void setTblgenaphauserses(Set<Tblgenaphausers> tblgenaphauserses) {
        this.tblgenaphauserses = tblgenaphauserses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblgenotypes> getTblgenotypeses() {
        return this.tblgenotypeses;
    }
    
    public void setTblgenotypeses(Set<Tblgenotypes> tblgenotypeses) {
        this.tblgenotypeses = tblgenotypeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblethnicityfrequency> getTblethnicityfrequencies() {
        return this.tblethnicityfrequencies;
    }
    
    public void setTblethnicityfrequencies(Set<Tblethnicityfrequency> tblethnicityfrequencies) {
        this.tblethnicityfrequencies = tblethnicityfrequencies;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsnp")
    public Set<Tblvalues> getTblvalueses() {
        return this.tblvalueses;
    }
    
    public void setTblvalueses(Set<Tblvalues> tblvalueses) {
        this.tblvalueses = tblvalueses;
    }




}


