package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblstatustype generated by hbm2java
 */
@Entity
@Table(name="TBLSTATUSTYPE"
    ,schema="ALLERGEN"
)
public class Tblstatustype  implements java.io.Serializable {


     private long statustypeid;
     private String description;
     private Set<Tblstatus> tblstatuses = new HashSet<Tblstatus>(0);

    public Tblstatustype() {
    }

	
    public Tblstatustype(long statustypeid, String description) {
        this.statustypeid = statustypeid;
        this.description = description;
    }
    public Tblstatustype(long statustypeid, String description, Set<Tblstatus> tblstatuses) {
       this.statustypeid = statustypeid;
       this.description = description;
       this.tblstatuses = tblstatuses;
    }
   
     @Id 
    
    @Column(name="STATUSTYPEID", unique=true, nullable=false)
    public long getStatustypeid() {
        return this.statustypeid;
    }
    
    public void setStatustypeid(long statustypeid) {
        this.statustypeid = statustypeid;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=75)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblstatustype")
    public Set<Tblstatus> getTblstatuses() {
        return this.tblstatuses;
    }
    
    public void setTblstatuses(Set<Tblstatus> tblstatuses) {
        this.tblstatuses = tblstatuses;
    }




}


