package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblsnpstatusId generated by hbm2java
 */
@Embeddable
public class TblsnpstatusId  implements java.io.Serializable {


     private int snpid;
     private int cohortid;
     private Double callrate;
     private Double maf;
     private Short valid;
     private long panelid;

    public TblsnpstatusId() {
    }

	
    public TblsnpstatusId(int snpid, int cohortid, long panelid) {
        this.snpid = snpid;
        this.cohortid = cohortid;
        this.panelid = panelid;
    }
    public TblsnpstatusId(int snpid, int cohortid, Double callrate, Double maf, Short valid, long panelid) {
       this.snpid = snpid;
       this.cohortid = cohortid;
       this.callrate = callrate;
       this.maf = maf;
       this.valid = valid;
       this.panelid = panelid;
    }
   

    @Column(name="SNPID", nullable=false)
    public int getSnpid() {
        return this.snpid;
    }
    
    public void setSnpid(int snpid) {
        this.snpid = snpid;
    }

    @Column(name="COHORTID", nullable=false)
    public int getCohortid() {
        return this.cohortid;
    }
    
    public void setCohortid(int cohortid) {
        this.cohortid = cohortid;
    }

    @Column(name="CALLRATE", precision=53, scale=0)
    public Double getCallrate() {
        return this.callrate;
    }
    
    public void setCallrate(Double callrate) {
        this.callrate = callrate;
    }

    @Column(name="MAF", precision=53, scale=0)
    public Double getMaf() {
        return this.maf;
    }
    
    public void setMaf(Double maf) {
        this.maf = maf;
    }

    @Column(name="VALID")
    public Short getValid() {
        return this.valid;
    }
    
    public void setValid(Short valid) {
        this.valid = valid;
    }

    @Column(name="PANELID", nullable=false)
    public long getPanelid() {
        return this.panelid;
    }
    
    public void setPanelid(long panelid) {
        this.panelid = panelid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblsnpstatusId) ) return false;
		 TblsnpstatusId castOther = ( TblsnpstatusId ) other; 
         
		 return (this.getSnpid()==castOther.getSnpid())
 && (this.getCohortid()==castOther.getCohortid())
 && ( (this.getCallrate()==castOther.getCallrate()) || ( this.getCallrate()!=null && castOther.getCallrate()!=null && this.getCallrate().equals(castOther.getCallrate()) ) )
 && ( (this.getMaf()==castOther.getMaf()) || ( this.getMaf()!=null && castOther.getMaf()!=null && this.getMaf().equals(castOther.getMaf()) ) )
 && ( (this.getValid()==castOther.getValid()) || ( this.getValid()!=null && castOther.getValid()!=null && this.getValid().equals(castOther.getValid()) ) )
 && (this.getPanelid()==castOther.getPanelid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSnpid();
         result = 37 * result + this.getCohortid();
         result = 37 * result + ( getCallrate() == null ? 0 : this.getCallrate().hashCode() );
         result = 37 * result + ( getMaf() == null ? 0 : this.getMaf().hashCode() );
         result = 37 * result + ( getValid() == null ? 0 : this.getValid().hashCode() );
         result = 37 * result + (int) this.getPanelid();
         return result;
   }   


}


