package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblusertypes generated by hbm2java
 */
@Entity
@Table(name="TBLUSERTYPES"
    ,schema="ALLERGEN"
)
public class Tblusertypes  implements java.io.Serializable {


     private int usertypeid;
     private String description;
     private Set<Tblsimsusers> tblsimsuserses = new HashSet<Tblsimsusers>(0);

    public Tblusertypes() {
    }

	
    public Tblusertypes(int usertypeid, String description) {
        this.usertypeid = usertypeid;
        this.description = description;
    }
    public Tblusertypes(int usertypeid, String description, Set<Tblsimsusers> tblsimsuserses) {
       this.usertypeid = usertypeid;
       this.description = description;
       this.tblsimsuserses = tblsimsuserses;
    }
   
     @Id 
    
    @Column(name="USERTYPEID", unique=true, nullable=false)
    public int getUsertypeid() {
        return this.usertypeid;
    }
    
    public void setUsertypeid(int usertypeid) {
        this.usertypeid = usertypeid;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblusertypes")
    public Set<Tblsimsusers> getTblsimsuserses() {
        return this.tblsimsuserses;
    }
    
    public void setTblsimsuserses(Set<Tblsimsusers> tblsimsuserses) {
        this.tblsimsuserses = tblsimsuserses;
    }




}


