package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblvariabledescription generated by hbm2java
 */
@Entity
@Table(name="TBLVARIABLEDESCRIPTION"
    ,schema="ALLERGEN"
)
public class Tblvariabledescription  implements java.io.Serializable {


     private TblvariabledescriptionId id;

    public Tblvariabledescription() {
    }

    public Tblvariabledescription(TblvariabledescriptionId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="variableid", column=@Column(name="VARIABLEID", nullable=false) ), 
        @AttributeOverride(name="description", column=@Column(name="DESCRIPTION") ), 
        @AttributeOverride(name="range", column=@Column(name="RANGE", length=100) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=100) ) } )
    public TblvariabledescriptionId getId() {
        return this.id;
    }
    
    public void setId(TblvariabledescriptionId id) {
        this.id = id;
    }




}


