package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblvaluesId generated by hbm2java
 */
@Embeddable
public class TblvaluesId  implements java.io.Serializable {


     private long snpid;
     private long cohortid;
     private Double uncorrpvalue;
     private Double corrpvalue;
     private Integer phenotypeid;
     private Long experimentid;
     private Double oddsratio;
     private String allele;

    public TblvaluesId() {
    }

	
    public TblvaluesId(long snpid, long cohortid) {
        this.snpid = snpid;
        this.cohortid = cohortid;
    }
    public TblvaluesId(long snpid, long cohortid, Double uncorrpvalue, Double corrpvalue, Integer phenotypeid, Long experimentid, Double oddsratio, String allele) {
       this.snpid = snpid;
       this.cohortid = cohortid;
       this.uncorrpvalue = uncorrpvalue;
       this.corrpvalue = corrpvalue;
       this.phenotypeid = phenotypeid;
       this.experimentid = experimentid;
       this.oddsratio = oddsratio;
       this.allele = allele;
    }
   

    @Column(name="SNPID", nullable=false)
    public long getSnpid() {
        return this.snpid;
    }
    
    public void setSnpid(long snpid) {
        this.snpid = snpid;
    }

    @Column(name="COHORTID", nullable=false)
    public long getCohortid() {
        return this.cohortid;
    }
    
    public void setCohortid(long cohortid) {
        this.cohortid = cohortid;
    }

    @Column(name="UNCORRPVALUE", precision=53, scale=0)
    public Double getUncorrpvalue() {
        return this.uncorrpvalue;
    }
    
    public void setUncorrpvalue(Double uncorrpvalue) {
        this.uncorrpvalue = uncorrpvalue;
    }

    @Column(name="CORRPVALUE", precision=53, scale=0)
    public Double getCorrpvalue() {
        return this.corrpvalue;
    }
    
    public void setCorrpvalue(Double corrpvalue) {
        this.corrpvalue = corrpvalue;
    }

    @Column(name="PHENOTYPEID")
    public Integer getPhenotypeid() {
        return this.phenotypeid;
    }
    
    public void setPhenotypeid(Integer phenotypeid) {
        this.phenotypeid = phenotypeid;
    }

    @Column(name="EXPERIMENTID")
    public Long getExperimentid() {
        return this.experimentid;
    }
    
    public void setExperimentid(Long experimentid) {
        this.experimentid = experimentid;
    }

    @Column(name="ODDSRATIO", precision=53, scale=0)
    public Double getOddsratio() {
        return this.oddsratio;
    }
    
    public void setOddsratio(Double oddsratio) {
        this.oddsratio = oddsratio;
    }

    @Column(name="ALLELE", length=10)
    public String getAllele() {
        return this.allele;
    }
    
    public void setAllele(String allele) {
        this.allele = allele;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblvaluesId) ) return false;
		 TblvaluesId castOther = ( TblvaluesId ) other; 
         
		 return (this.getSnpid()==castOther.getSnpid())
 && (this.getCohortid()==castOther.getCohortid())
 && ( (this.getUncorrpvalue()==castOther.getUncorrpvalue()) || ( this.getUncorrpvalue()!=null && castOther.getUncorrpvalue()!=null && this.getUncorrpvalue().equals(castOther.getUncorrpvalue()) ) )
 && ( (this.getCorrpvalue()==castOther.getCorrpvalue()) || ( this.getCorrpvalue()!=null && castOther.getCorrpvalue()!=null && this.getCorrpvalue().equals(castOther.getCorrpvalue()) ) )
 && ( (this.getPhenotypeid()==castOther.getPhenotypeid()) || ( this.getPhenotypeid()!=null && castOther.getPhenotypeid()!=null && this.getPhenotypeid().equals(castOther.getPhenotypeid()) ) )
 && ( (this.getExperimentid()==castOther.getExperimentid()) || ( this.getExperimentid()!=null && castOther.getExperimentid()!=null && this.getExperimentid().equals(castOther.getExperimentid()) ) )
 && ( (this.getOddsratio()==castOther.getOddsratio()) || ( this.getOddsratio()!=null && castOther.getOddsratio()!=null && this.getOddsratio().equals(castOther.getOddsratio()) ) )
 && ( (this.getAllele()==castOther.getAllele()) || ( this.getAllele()!=null && castOther.getAllele()!=null && this.getAllele().equals(castOther.getAllele()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getSnpid();
         result = 37 * result + (int) this.getCohortid();
         result = 37 * result + ( getUncorrpvalue() == null ? 0 : this.getUncorrpvalue().hashCode() );
         result = 37 * result + ( getCorrpvalue() == null ? 0 : this.getCorrpvalue().hashCode() );
         result = 37 * result + ( getPhenotypeid() == null ? 0 : this.getPhenotypeid().hashCode() );
         result = 37 * result + ( getExperimentid() == null ? 0 : this.getExperimentid().hashCode() );
         result = 37 * result + ( getOddsratio() == null ? 0 : this.getOddsratio().hashCode() );
         result = 37 * result + ( getAllele() == null ? 0 : this.getAllele().hashCode() );
         return result;
   }   


}


