package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tblvariablesetlookup generated by hbm2java
 */
@Entity
@Table(name="TBLVARIABLESETLOOKUP"
    ,schema="ALLERGEN"
)
public class Tblvariablesetlookup  implements java.io.Serializable {


     private long variablesetid;
     private String name;
     private Set<Tblvariablelookup> tblvariablelookups = new HashSet<Tblvariablelookup>(0);

    public Tblvariablesetlookup() {
    }

	
    public Tblvariablesetlookup(long variablesetid, String name) {
        this.variablesetid = variablesetid;
        this.name = name;
    }
    public Tblvariablesetlookup(long variablesetid, String name, Set<Tblvariablelookup> tblvariablelookups) {
       this.variablesetid = variablesetid;
       this.name = name;
       this.tblvariablelookups = tblvariablelookups;
    }
   
     @Id 
    
    @Column(name="VARIABLESETID", unique=true, nullable=false)
    public long getVariablesetid() {
        return this.variablesetid;
    }
    
    public void setVariablesetid(long variablesetid) {
        this.variablesetid = variablesetid;
    }
    
    @Column(name="NAME", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="TBLVARIABLESET", schema="ALLERGEN", joinColumns = { 
        @JoinColumn(name="VARIABLESETID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="VARIABLEID", nullable=false, updatable=false) })
    public Set<Tblvariablelookup> getTblvariablelookups() {
        return this.tblvariablelookups;
    }
    
    public void setTblvariablelookups(Set<Tblvariablelookup> tblvariablelookups) {
        this.tblvariablelookups = tblvariablelookups;
    }




}


