package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblvariablelookup generated by hbm2java
 */
@Entity
@Table(name="TBLVARIABLELOOKUP"
    ,schema="ALLERGEN"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class Tblvariablelookup  implements java.io.Serializable {


     private long variableid;
     private String name;
     private String description;
     private Set<Tblvariables> tblvariableses = new HashSet<Tblvariables>(0);
     private Set<Tblvariablesetlookup> tblvariablesetlookups = new HashSet<Tblvariablesetlookup>(0);

    public Tblvariablelookup() {
    }

	
    public Tblvariablelookup(long variableid, String name, String description) {
        this.variableid = variableid;
        this.name = name;
        this.description = description;
    }
    public Tblvariablelookup(long variableid, String name, String description, Set<Tblvariables> tblvariableses, Set<Tblvariablesetlookup> tblvariablesetlookups) {
       this.variableid = variableid;
       this.name = name;
       this.description = description;
       this.tblvariableses = tblvariableses;
       this.tblvariablesetlookups = tblvariablesetlookups;
    }
   
     @Id 
    
    @Column(name="VARIABLEID", unique=true, nullable=false)
    public long getVariableid() {
        return this.variableid;
    }
    
    public void setVariableid(long variableid) {
        this.variableid = variableid;
    }
    
    @Column(name="NAME", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=1500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblvariablelookup")
    public Set<Tblvariables> getTblvariableses() {
        return this.tblvariableses;
    }
    
    public void setTblvariableses(Set<Tblvariables> tblvariableses) {
        this.tblvariableses = tblvariableses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblvariablelookups")
    public Set<Tblvariablesetlookup> getTblvariablesetlookups() {
        return this.tblvariablesetlookups;
    }
    
    public void setTblvariablesetlookups(Set<Tblvariablesetlookup> tblvariablesetlookups) {
        this.tblvariablesetlookups = tblvariablesetlookups;
    }




}


