package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblvariabledescriptionId generated by hbm2java
 */
@Embeddable
public class TblvariabledescriptionId  implements java.io.Serializable {


     private long variableid;
     private String description;
     private String range;
     private String name;

    public TblvariabledescriptionId() {
    }

	
    public TblvariabledescriptionId(long variableid, String name) {
        this.variableid = variableid;
        this.name = name;
    }
    public TblvariabledescriptionId(long variableid, String description, String range, String name) {
       this.variableid = variableid;
       this.description = description;
       this.range = range;
       this.name = name;
    }
   

    @Column(name="VARIABLEID", nullable=false)
    public long getVariableid() {
        return this.variableid;
    }
    
    public void setVariableid(long variableid) {
        this.variableid = variableid;
    }

    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="RANGE", length=100)
    public String getRange() {
        return this.range;
    }
    
    public void setRange(String range) {
        this.range = range;
    }

    @Column(name="NAME", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblvariabledescriptionId) ) return false;
		 TblvariabledescriptionId castOther = ( TblvariabledescriptionId ) other; 
         
		 return (this.getVariableid()==castOther.getVariableid())
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getRange()==castOther.getRange()) || ( this.getRange()!=null && castOther.getRange()!=null && this.getRange().equals(castOther.getRange()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getVariableid();
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getRange() == null ? 0 : this.getRange().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   


}


