package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblvariablehistoryId generated by hbm2java
 */
@Embeddable
public class TblvariablehistoryId  implements java.io.Serializable {


     private long subjectid;
     private long variableid;
     private String file;
     private Date date;

    public TblvariablehistoryId() {
    }

    public TblvariablehistoryId(long subjectid, long variableid, String file, Date date) {
       this.subjectid = subjectid;
       this.variableid = variableid;
       this.file = file;
       this.date = date;
    }
   

    @Column(name="SUBJECTID", nullable=false)
    public long getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(long subjectid) {
        this.subjectid = subjectid;
    }

    @Column(name="VARIABLEID", nullable=false)
    public long getVariableid() {
        return this.variableid;
    }
    
    public void setVariableid(long variableid) {
        this.variableid = variableid;
    }

    @Column(name="FILE", nullable=false, length=200)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }

    @Column(name="DATE", nullable=false, length=26)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblvariablehistoryId) ) return false;
		 TblvariablehistoryId castOther = ( TblvariablehistoryId ) other; 
         
		 return (this.getSubjectid()==castOther.getSubjectid())
 && (this.getVariableid()==castOther.getVariableid())
 && ( (this.getFile()==castOther.getFile()) || ( this.getFile()!=null && castOther.getFile()!=null && this.getFile().equals(castOther.getFile()) ) )
 && ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getSubjectid();
         result = 37 * result + (int) this.getVariableid();
         result = 37 * result + ( getFile() == null ? 0 : this.getFile().hashCode() );
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         return result;
   }   


}


