package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblvariables generated by hbm2java
 */
@Entity
@Table(name="TBLVARIABLES"
    ,schema="ALLERGEN"
)
public class Tblvariables  implements java.io.Serializable {


     private TblvariablesId id;
     private Tblvariablelookup tblvariablelookup;
     private Tblsubject tblsubject;
     private String value;

    public Tblvariables() {
    }

    public Tblvariables(TblvariablesId id, Tblvariablelookup tblvariablelookup, Tblsubject tblsubject, String value) {
       this.id = id;
       this.tblvariablelookup = tblvariablelookup;
       this.tblsubject = tblsubject;
       this.value = value;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="variableid", column=@Column(name="VARIABLEID", nullable=false) ), 
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ) } )
    public TblvariablesId getId() {
        return this.id;
    }
    
    public void setId(TblvariablesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VARIABLEID", nullable=false, insertable=false, updatable=false)
    public Tblvariablelookup getTblvariablelookup() {
        return this.tblvariablelookup;
    }
    
    public void setTblvariablelookup(Tblvariablelookup tblvariablelookup) {
        this.tblvariablelookup = tblvariablelookup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SUBJECTID", nullable=false, insertable=false, updatable=false)
    public Tblsubject getTblsubject() {
        return this.tblsubject;
    }
    
    public void setTblsubject(Tblsubject tblsubject) {
        this.tblsubject = tblsubject;
    }
    
    @Column(name="VALUE", nullable=false, length=100)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


