package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblvariablesId generated by hbm2java
 */
@Embeddable
public class TblvariablesId  implements java.io.Serializable {


     private long variableid;
     private long subjectid;

    public TblvariablesId() {
    }

    public TblvariablesId(long variableid, long subjectid) {
       this.variableid = variableid;
       this.subjectid = subjectid;
    }
   

    @Column(name="VARIABLEID", nullable=false)
    public long getVariableid() {
        return this.variableid;
    }
    
    public void setVariableid(long variableid) {
        this.variableid = variableid;
    }

    @Column(name="SUBJECTID", nullable=false)
    public long getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(long subjectid) {
        this.subjectid = subjectid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblvariablesId) ) return false;
		 TblvariablesId castOther = ( TblvariablesId ) other; 
         
		 return (this.getVariableid()==castOther.getVariableid())
 && (this.getSubjectid()==castOther.getSubjectid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getVariableid();
         result = 37 * result + (int) this.getSubjectid();
         return result;
   }   


}


