package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblvalues generated by hbm2java
 */
@Entity
@Table(name="TBLVALUES"
    ,schema="ALLERGEN"
)
public class Tblvalues  implements java.io.Serializable {


     private TblvaluesId id;
     private Tblexperiments tblexperiments;
     private Tblcohortlookup tblcohortlookup;
     private Tblsnp tblsnp;

    public Tblvalues() {
    }

	
    public Tblvalues(TblvaluesId id, Tblcohortlookup tblcohortlookup, Tblsnp tblsnp) {
        this.id = id;
        this.tblcohortlookup = tblcohortlookup;
        this.tblsnp = tblsnp;
    }
    public Tblvalues(TblvaluesId id, Tblexperiments tblexperiments, Tblcohortlookup tblcohortlookup, Tblsnp tblsnp) {
       this.id = id;
       this.tblexperiments = tblexperiments;
       this.tblcohortlookup = tblcohortlookup;
       this.tblsnp = tblsnp;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="snpid", column=@Column(name="SNPID", nullable=false) ), 
        @AttributeOverride(name="cohortid", column=@Column(name="COHORTID", nullable=false) ), 
        @AttributeOverride(name="uncorrpvalue", column=@Column(name="UNCORRPVALUE", precision=53, scale=0) ), 
        @AttributeOverride(name="corrpvalue", column=@Column(name="CORRPVALUE", precision=53, scale=0) ), 
        @AttributeOverride(name="phenotypeid", column=@Column(name="PHENOTYPEID") ), 
        @AttributeOverride(name="experimentid", column=@Column(name="EXPERIMENTID") ), 
        @AttributeOverride(name="oddsratio", column=@Column(name="ODDSRATIO", precision=53, scale=0) ), 
        @AttributeOverride(name="allele", column=@Column(name="ALLELE", length=10) ) } )
    public TblvaluesId getId() {
        return this.id;
    }
    
    public void setId(TblvaluesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EXPERIMENTID", insertable=false, updatable=false)
    public Tblexperiments getTblexperiments() {
        return this.tblexperiments;
    }
    
    public void setTblexperiments(Tblexperiments tblexperiments) {
        this.tblexperiments = tblexperiments;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COHORTID", nullable=false, insertable=false, updatable=false)
    public Tblcohortlookup getTblcohortlookup() {
        return this.tblcohortlookup;
    }
    
    public void setTblcohortlookup(Tblcohortlookup tblcohortlookup) {
        this.tblcohortlookup = tblcohortlookup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SNPID", nullable=false, insertable=false, updatable=false)
    public Tblsnp getTblsnp() {
        return this.tblsnp;
    }
    
    public void setTblsnp(Tblsnp tblsnp) {
        this.tblsnp = tblsnp;
    }




}


