package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblvariablehistory generated by hbm2java
 */
@Entity
@Table(name="TBLVARIABLEHISTORY"
    ,schema="ALLERGEN"
)
public class Tblvariablehistory  implements java.io.Serializable {


     private TblvariablehistoryId id;
     private String value;

    public Tblvariablehistory() {
    }

	
    public Tblvariablehistory(TblvariablehistoryId id) {
        this.id = id;
    }
    public Tblvariablehistory(TblvariablehistoryId id, String value) {
       this.id = id;
       this.value = value;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false) ), 
        @AttributeOverride(name="variableid", column=@Column(name="VARIABLEID", nullable=false) ), 
        @AttributeOverride(name="file", column=@Column(name="FILE", nullable=false, length=200) ), 
        @AttributeOverride(name="date", column=@Column(name="DATE", nullable=false, length=26) ) } )
    public TblvariablehistoryId getId() {
        return this.id;
    }
    
    public void setId(TblvariablehistoryId id) {
        this.id = id;
    }
    
    @Column(name="VALUE", length=100)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


