package ca.ubc.icapture.genapha.slims.model;
// Generated May 30, 2017 4:12:31 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vwkeggpathways generated by hbm2java
 */
@Entity
@Table(name="VWKEGGPATHWAYS"
    ,schema="ALLERGEN"
)
public class Vwkeggpathways  implements java.io.Serializable {


     private VwkeggpathwaysId id;

    public Vwkeggpathways() {
    }

    public Vwkeggpathways(VwkeggpathwaysId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="pathwayid", column=@Column(name="PATHWAYID", nullable=false, length=5) ), 
        @AttributeOverride(name="pathwayname", column=@Column(name="PATHWAYNAME", nullable=false, length=145) ), 
        @AttributeOverride(name="kegggeneid", column=@Column(name="KEGGGENEID", nullable=false) ), 
        @AttributeOverride(name="geneid", column=@Column(name="GENEID", nullable=false) ), 
        @AttributeOverride(name="genename", column=@Column(name="GENENAME", nullable=false, length=25) ) } )
    public VwkeggpathwaysId getId() {
        return this.id;
    }
    
    public void setId(VwkeggpathwaysId id) {
        this.id = id;
    }




}


